/- Generated by Triptych from `triptych Graph`. -/

import Triptych.Architecture.GeneratedLinter
import Triptych.Architecture.Denote
import Triptych.Architecture.Derivation
import Triptych.Architecture.Value
import Triptych.Architecture.Constraint
import Triptych.Architecture.Assemble
import Triptych.Theorems.Reconcile
import Triptych.Theorems.Value
import Triptych.Archive.DecodeLemmas
import Triptych.Theorems.Derivation
import Triptych.Theorems.Scanner
import Outputs.Graph.spec
import Inputs.Graph

open Triptych
open GraphExample

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false

/- ══════════════════════════════ engine ══════════════════════════════
The executable counterpart of the spec. A verified scanner extracts captured
components and stops at the first complete parse. The archived reference `decode`
is used only in the agreement proof, not as a runtime fallback. `computeValue`
evaluates the value function on those captures. Generated `DecidablePred` instances
make the readable `IsWf` and `IsValid` predicates directly executable.
`decodeView` packages the exact input and value/constraint captures as a typed `View`.

The public format API stays capitalized: use `#eval decide (IsValid s)` and
`#eval computeValue s`. The equivalence section below proves that these readable
predicates execute through the generic Triptych interpreter. -/

instance Graph.Derivation.Order.instDecidableValid : DecidablePred Graph.Derivation.Order.Valid := fun d => by
  cases d <;> simp only [Graph.Derivation.Order.Valid] <;> infer_instance

def Graph.Derivation.Order.capturesWith (qual : String) : Graph.Derivation.Order → Triptych.CaptureMap
  | .alt0 part0 => ([] ++ [])

instance Graph.Derivation.Cells.instDecidableValid : DecidablePred Graph.Derivation.Cells.Valid := fun d => by
  cases d <;> simp only [Graph.Derivation.Cells.Valid] <;> infer_instance

def Graph.Derivation.Cells.capturesWith (qual : String) : Graph.Derivation.Cells → Triptych.CaptureMap
  | .alt0 => ([] ++ [])
  | .alt1 part0 => ([] ++ [])

instance Graph.Derivation.Graph.instDecidableValid : DecidablePred Graph.Derivation.Graph.Valid := fun d => by
  cases d <;> simp only [Graph.Derivation.Graph.Valid] <;> infer_instance

def Graph.Derivation.Graph.capturesWith (qual : String) : Graph.Derivation.Graph → Triptych.CaptureMap
  | .alt0 part0 part2 =>
    (Triptych.referenceCaptures qual "Order" (Graph.Derivation.Order.render part0) ++
        Graph.Derivation.Order.capturesWith "Order" part0 ++
      ([] ++
        (Triptych.referenceCaptures qual "Cells" (Graph.Derivation.Cells.render part2) ++
            Graph.Derivation.Cells.capturesWith "Cells" part2 ++
          [])))

def Graph.valueFn := fun m : Triptych.CaptureMap =>
  toGraph ((Triptych.CaptureMap.toEnv m "Order").getD "") ((Triptych.CaptureMap.toEnv m "Cells").getD "")

def Graph.constraints : List ConstraintEntry :=
  [ConstraintEntry.opaqueMap ConstraintPhase.wellFormed
      (fun m : CaptureMap =>
        ((Triptych.CaptureMap.toEnv m "Cells").getD "").length ==
          upperTriangleSize ((Triptych.CaptureMap.toEnv m "Order").getD ""))]

def Graph.computeValue (s : String) :=
  Triptych.scannerComputeValueMap Graph.grammar Graph.valueFn s

def Graph.View.ofMap (input : String) (m : Triptych.CaptureMap) : Graph.View :=
  Graph.View.mk input ((Triptych.CaptureMap.toEnv m "Order").getD "") ((Triptych.CaptureMap.toEnv m "Cells").getD "")

def Graph.decodeView (s : String) : Option Graph.View :=
  (scan Graph.grammar s).map (Graph.View.ofMap s)

def Graph.Derivation.Graph.toView (d : Graph.Derivation.Graph) : Graph.View :=
  Graph.View.ofMap (Graph.Derivation.Graph.render d) (Graph.Derivation.Graph.capturesWith "" d)

/- ════════════════════════════ equivalence ════════════════════════════
The auto-discharged guarantees relating the readable surface to the executable
engine: `IsWfGrammar_equiv` proves grammar-layout agreement and `IsWf_equiv`
proves full well-formedness agreement. `computeValue_eq` proves the values agree,
while `decodeView_input`, `IsValid_view`, and `computeValue_view` expose the typed
parse view. Derived `DecidablePred` instances make the surface predicates executable
via the engine. No `sorry`. -/

theorem Graph.Derivation.Order.matches (qual : String) (fuel : Nat) (d : Graph.Derivation.Order)
    (hvalid : Graph.Derivation.Order.Valid d) :
    Triptych.ProdMatch Graph.grammar qual (fuel + 1)
      (Production.mk "Order" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.atLeastOne)) false]])
      (Graph.Derivation.Order.render d) (Graph.Derivation.Order.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [Graph.Derivation.Order.Valid] at hvalid
    have hpart0 := hvalid
    simp only [Graph.Derivation.Order.render, Graph.Derivation.Order.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.term TokClass.digit (LenSpec.atLeastOne)) false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          · exact Triptych.symMatch_term Graph.grammar qual (fuel + 1) TokClass.digit (LenSpec.atLeastOne) part0 hpart0
          · exact Triptych.seqMatch_nil Graph.grammar qual (fuel + 1))

theorem Graph.Derivation.Cells.matches (qual : String) (fuel : Nat) (d : Graph.Derivation.Cells)
    (hvalid : Graph.Derivation.Cells.Valid d) :
    Triptych.ProdMatch Graph.grammar qual (fuel + 1)
      (Production.mk "Cells"
        [[SymItem.mk (Sym.lit "") false], [SymItem.mk (Sym.term TokClass.bit (LenSpec.atLeastOne)) false]])
      (Graph.Derivation.Cells.render d) (Graph.Derivation.Cells.capturesWith qual d) :=
  by
  cases d with
  | alt0 =>
    simp only [Graph.Derivation.Cells.Valid] at hvalid
    clear hvalid
    simp only [Graph.Derivation.Cells.render, Graph.Derivation.Cells.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.lit "") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          · exact Triptych.symMatch_lit Graph.grammar qual (fuel + 1) ""
          · exact Triptych.seqMatch_nil Graph.grammar qual (fuel + 1))
  | alt1 part0 =>
    simp only [Graph.Derivation.Cells.Valid] at hvalid
    have hpart0 := hvalid
    simp only [Graph.Derivation.Cells.render, Graph.Derivation.Cells.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.term TokClass.bit (LenSpec.atLeastOne)) false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          · exact Triptych.symMatch_term Graph.grammar qual (fuel + 1) TokClass.bit (LenSpec.atLeastOne) part0 hpart0
          · exact Triptych.seqMatch_nil Graph.grammar qual (fuel + 1))

theorem Graph.Derivation.Graph.matches (qual : String) (fuel : Nat) (d : Graph.Derivation.Graph)
    (hvalid : Graph.Derivation.Graph.Valid d) :
    Triptych.ProdMatch Graph.grammar qual (fuel + 2)
      (Production.mk "Graph"
        [[SymItem.mk (Sym.ref "Order") false, SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "Cells") false]])
      (Graph.Derivation.Graph.render d) (Graph.Derivation.Graph.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 part2 =>
    simp only [Graph.Derivation.Graph.Valid] at hvalid
    rcases hvalid with ⟨hpart0, hpart2⟩
    simp only [Graph.Derivation.Graph.render, Graph.Derivation.Graph.capturesWith]
    apply
      Triptych.prodMatch_of_alt (alt :=
        [SymItem.mk (Sym.ref "Order") false, SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "Cells") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              (by
                simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                  (Triptych.symMatch_ref Graph.grammar qual (((fuel + 0)) + 1) "Order"
                    (Production.mk "Order" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.atLeastOne)) false]]) (by rfl)
                    (Graph.Derivation.Order.render part0) (Graph.Derivation.Order.capturesWith "Order" part0)
                    (Graph.Derivation.Order.matches "Order" (fuel + 0) part0 hpart0)))
          ·
            exact
              (by
                apply Triptych.seqMatch_required
                · exact Triptych.symMatch_lit Graph.grammar qual (fuel + 2) ":"
                ·
                  exact
                    (by
                      apply Triptych.seqMatch_required
                      ·
                        exact
                          (by
                            simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                              (Triptych.symMatch_ref Graph.grammar qual (((fuel + 0)) + 1) "Cells"
                                (Production.mk "Cells"
                                  [[SymItem.mk (Sym.lit "") false],
                                    [SymItem.mk (Sym.term TokClass.bit (LenSpec.atLeastOne)) false]])
                                (by rfl) (Graph.Derivation.Cells.render part2)
                                (Graph.Derivation.Cells.capturesWith "Cells" part2)
                                (Graph.Derivation.Cells.matches "Cells" (fuel + 0) part2 hpart2)))
                      · exact Triptych.seqMatch_nil Graph.grammar qual (fuel + 2))))

theorem Graph.Derivation.Graph.mem_fullParses (d : Graph.Derivation.Graph) (hvalid : Graph.Derivation.Graph.Valid d) :
    Graph.Derivation.Graph.capturesWith "" d ∈ Triptych.fullParses Graph.grammar (Graph.Derivation.Graph.render d) :=
  by
  apply
    Triptych.prodMatch_mem_fullParses Graph.grammar
      (Production.mk "Graph"
        [[SymItem.mk (Sym.ref "Order") false, SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "Cells") false]])
      (by rfl)
  simpa [Graph.grammar] using (Graph.Derivation.Graph.matches "" 1 d hvalid)

theorem Graph.Derivation.Graph.decode_render_of_captureFunctional
    (hfunctional : Triptych.GrammarCaptureFunctional Graph.grammar) (d : Graph.Derivation.Graph)
    (hvalid : Graph.Derivation.Graph.Valid d) :
    Triptych.decode Graph.grammar (Graph.Derivation.Graph.render d) = some (Graph.Derivation.Graph.capturesWith "" d) :=
  Triptych.decode_eq_of_mem_fullParses hfunctional (mem_fullParses d hvalid)

theorem Graph.decodeView_input {s : String} {v : Graph.View} (h : Graph.decodeView s = some v) :
    Graph.View.input v = s := by
  unfold Graph.decodeView at h
  rw [Option.map_eq_some_iff] at h
  obtain ⟨m, _, hv⟩ := h
  subst v
  rfl

theorem Graph.Derivation.Graph.decodeView_render_of_captureFunctional
    (hfunctional : Triptych.GrammarCaptureFunctional Graph.grammar) (d : Graph.Derivation.Graph)
    (hvalid : Graph.Derivation.Graph.Valid d) :
    Graph.decodeView (Graph.Derivation.Graph.render d) = some (Graph.Derivation.Graph.toView d) :=
  by
  unfold Graph.decodeView Graph.Derivation.Graph.toView
  rw [Triptych.scan_eq_decode]
  rw [Graph.Derivation.Graph.decode_render_of_captureFunctional hfunctional d hvalid]
  rfl

theorem Graph.SatisfiesWfConstraints_of_decode {s : String} {m : Triptych.CaptureMap}
    (h : decode Graph.grammar s = some m) :
    Graph.SatisfiesWfConstraints s ↔
      Graph.WfConstraints ((Triptych.CaptureMap.toEnv m "Cells").getD "")
        ((Triptych.CaptureMap.toEnv m "Order").getD "") :=
  by
  unfold Graph.SatisfiesWfConstraints
  simp only [Triptych.component_eq_of_decode h "Cells", Triptych.component_eq_of_decode h "Order"]

theorem Graph.Internal.matchesRef.Order (fuel : Nat) (s : String) :
    matchesSym Graph.grammar (fuel + 1) (Sym.ref "Order") s ↔ Graph.IsWf.Order s :=
  by
  rw [matchesSym,
    show
      (Graph.grammar).prod? "Order" =
        some (Production.mk "Order" [[SymItem.mk (Sym.term TokClass.digit LenSpec.atLeastOne) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Graph.IsWf.Order
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Graph.Internal.matchesRef.Cells (fuel : Nat) (s : String) :
    matchesSym Graph.grammar (fuel + 1) (Sym.ref "Cells") s ↔ Graph.IsWf.Cells s :=
  by
  rw [matchesSym,
    show
      (Graph.grammar).prod? "Cells" =
        some
          (Production.mk "Cells"
            [[SymItem.mk (Sym.lit "") false], [SymItem.mk (Sym.term TokClass.bit LenSpec.atLeastOne) false]])
      from rfl]
  dsimp only
  unfold matchesProd Graph.IsWf.Cells
  simp (config := { maxSteps := 1000000 }) only [List.mem_cons, List.mem_singleton, List.not_mem_nil,
    Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_or_imp, exists_eq_left, exists_eq_left, if_true,
    if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsBits_matchesTerm,
    IsFixedBits_matchesTerm, IsBitsBetween_matchesTerm]
  repeat'
    first
    | apply or_congr
    | ( simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left,
          ← and_assoc, exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
        try grind [String.append_assoc, String.append_empty])

theorem Graph.Internal.matchesRef.Graph (fuel : Nat) (s : String) :
    matchesSym Graph.grammar (fuel + 2) (Sym.ref "Graph") s ↔ Graph.IsWf.Graph s :=
  by
  rw [matchesSym,
    show
      (Graph.grammar).prod? "Graph" =
        some
          (Production.mk "Graph"
            [[SymItem.mk (Sym.ref "Order") false, SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "Cells") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Graph.IsWf.Graph
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym,
    Graph.Internal.matchesRef.Order, Graph.Internal.matchesRef.Cells]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Graph.IsWfGrammar_equiv (s : String) : Triptych.IsWf Graph.grammar s ↔ Graph.IsWf.Graph s :=
  by
  rw [isWf_eq_isWfProd_start, IsWfProd,
    show
      (Graph.grammar).prod? (Graph.grammar).start =
        some
          (Production.mk "Graph"
            [[SymItem.mk (Sym.ref "Order") false, SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "Cells") false]])
      from rfl]
  have hstart :
    ∀ n,
      matchesProd Graph.grammar n
          (Production.mk "Graph"
            [[SymItem.mk (Sym.ref "Order") false, SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "Cells") false]])
          s =
        matchesSym Graph.grammar (n + 1) (Sym.ref "Graph") s :=
    by
    intro n
    rw [matchesSym,
      show
        (Graph.grammar).prod? "Graph" =
          some
            (Production.mk "Graph"
              [[SymItem.mk (Sym.ref "Order") false, SymItem.mk (Sym.lit ":") false,
                  SymItem.mk (Sym.ref "Cells") false]])
        from rfl]
  show
    matchesProd Graph.grammar (Graph.grammar).prods.length
        (Production.mk "Graph"
          [[SymItem.mk (Sym.ref "Order") false, SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "Cells") false]])
        s ↔
      _
  rw [hstart]
  exact Graph.Internal.matchesRef.Graph _ s

theorem Graph.IsWf_equiv (s : String) : Graph.IsWf s ↔ Triptych.isWf Graph.grammar Graph.constraints s :=
  by
  unfold Graph.IsWf Triptych.isWf
  rw [Triptych.scan_eq_decode]
  rw [← Graph.IsWfGrammar_equiv, ← decodeSome_iff_IsWf Graph.grammar (by decide)]
  unfold Graph.SatisfiesWfConstraints Graph.WfConstraints Graph.constraints
  simp only [Triptych.component, Triptych.componentList, Triptych.envOf, Triptych.captureMapOf, Triptych.scan_eq_decode,
    List.forall_mem_cons, List.forall_mem_singleton, List.not_mem_nil, forall_const, ConstraintEntry.wfPart,
    Constraint.eval, ValExpr.eval, presentCount, natOf_getD, intOf_getD, lenOf_getD, countOf_getD, signOf_getD,
    Env.countVal, and_true, true_and, false_implies, implies_true, Bool.false_eq_true]
  try grind

theorem Graph.IsValid_equiv (s : String) :
    Graph.IsValid s ↔
      Triptych.isWf Graph.grammar Graph.constraints s ∧
        Triptych.satisfiesConstraints Graph.grammar Graph.constraints s :=
  by
  unfold Graph.IsValid
  rw [(Graph.IsWf_equiv s)]
  unfold Triptych.satisfiesConstraints Triptych.captureMapOf Graph.constraints
  simp only [List.forall_mem_cons, List.forall_mem_singleton, List.not_mem_nil, ConstraintEntry.valPart, false_implies,
    true_and, and_true]
  constructor
  · intro h
    exact ⟨h, fun _ => True.intro⟩
  · exact And.left

instance Graph.instDecidableGrammar : DecidablePred Graph.IsWf.Graph := fun s =>
  @decidable_of_iff _ _ (Graph.IsWfGrammar_equiv s) (Triptych.decIsWfScanner Graph.grammar (by decide) s)

instance Graph.instDecidableIsWf : DecidablePred Graph.IsWf := fun s =>
  @decidable_of_iff _ _ (Graph.IsWf_equiv s).symm inferInstance

instance Graph.instDecidableIsValid : DecidablePred Graph.IsValid := fun s => inferInstance

theorem Graph.View.wfConstraints_of_decode {s : String} {m : Triptych.CaptureMap}
    (h : decode Graph.grammar s = some m) :
    Graph.SatisfiesWfConstraints s ↔ Graph.View.WfConstraints (Graph.View.ofMap s m) :=
  by
  rw [Graph.SatisfiesWfConstraints_of_decode h]
  rfl

theorem Graph.IsValid_view (s : String) :
    Graph.IsValid s ↔ ∃ v : Graph.View, Graph.decodeView s = some v ∧ Graph.View.Valid v :=
  by
  constructor
  · intro hvalid
    have hengine := (Graph.IsValid_equiv s).mp hvalid
    have hsome : (decode Graph.grammar s).isSome = true := by simpa only [Triptych.scan_eq_decode] using hengine.1.1
    obtain ⟨m, hm⟩ := Option.isSome_iff_exists.mp hsome
    have hmDecode : decode Graph.grammar s = some m := hm
    refine ⟨Graph.View.ofMap s m, ?_, ?_⟩
    · unfold Graph.decodeView
      simp [Triptych.scan_eq_decode, hmDecode]
    · exact (Graph.View.wfConstraints_of_decode hmDecode).mp hvalid.2
  · rintro ⟨v, hview, hvalid⟩
    unfold Graph.decodeView at hview
    rw [Option.map_eq_some_iff] at hview
    obtain ⟨m, hm, hv⟩ := hview
    subst v
    have hmDecode : decode Graph.grammar s = some m := by simpa only [Triptych.scan_eq_decode] using hm
    have hdecoded : (decode Graph.grammar s).isSome = true := by simp [hmDecode]
    have hgrammar := (Graph.IsWfGrammar_equiv s).mp ((decodeSome_iff_IsWf Graph.grammar (by decide) s).mp hdecoded)
    exact ⟨hgrammar, (Graph.View.wfConstraints_of_decode hmDecode).mpr hvalid⟩

theorem Graph.computeValue_eq (s : String) :
    Graph.computeValue s =
      (decode Graph.grammar s).map
        (fun _ =>
          Graph.value (Triptych.component Graph.grammar s "Order") (Triptych.component Graph.grammar s "Cells")) :=
  by
  unfold Graph.computeValue Triptych.scannerComputeValueMap Triptych.component Triptych.envOf Triptych.captureMapOf
    Graph.value Graph.valueFn
  rw [Triptych.scan_eq_decode]
  cases h : decode Graph.grammar s with
  | none => simp [h]
  | some m => simp [h, natOf_getD, intOf_getD, lenOf_getD, countOf_getD, signOf_getD, Env.countVal, ValExpr.eval]

theorem Graph.computeValue_of_decode {s : String} {m : Triptych.CaptureMap} (h : decode Graph.grammar s = some m) :
    Graph.computeValue s =
      some
        (Graph.value ((Triptych.CaptureMap.toEnv m "Order").getD "") ((Triptych.CaptureMap.toEnv m "Cells").getD "")) :=
  by
  rw [Graph.computeValue_eq, h]
  simp only [Option.map_some, Triptych.component_eq_of_decode h "Order", Triptych.component_eq_of_decode h "Cells"]

theorem Graph.computeValue_view (s : String) : Graph.computeValue s = (Graph.decodeView s).map Graph.View.denotation :=
  by
  unfold Graph.decodeView
  rw [Triptych.scan_eq_decode]
  cases h : decode Graph.grammar s with
  |
    none =>
    rw [show Graph.computeValue s = none by
        rw [Graph.computeValue_eq, h]
        rfl]
    rfl
  | some m =>
    rw [Graph.computeValue_of_decode h]
    simp only [Option.map_some]
    rfl

/- ═══════════════════════════════ parser ══════════════════════════════
The generated correct-by-construction parser `parse` scans once, checks constraints
on that capture map, and computes the result from the same captures. `parse_eq_gated`
proves equality with the readable validity-gated presentation. Its correctness and
search-cost guarantees — `parse_sound`, `parse_complete`, `parse_reject`,
`parse_profile_result`, `parse_candidateChecks_le`, `parse_view`, and typed
`parse_eq_some_iff_view` / `parse_eq_none_iff_view` normal forms — are all
AUTO-DISCHARGED here.
When an external parser is declared, `checkedExtParse` additionally validates each
external result against this parser and ships an AUTO-DISCHARGED soundness theorem.
A verified parser, no `sorry`. -/

theorem Graph.computeValue_isSome (s : String) : Graph.IsValid s → (Graph.computeValue s).isSome :=
  by
  intro h
  have hengine := (Graph.IsValid_equiv s).mp h
  unfold Triptych.isWf at hengine
  unfold Graph.computeValue Triptych.scannerComputeValueMap
  rw [Option.isSome_map]
  exact hengine.1.1

def Graph.parse (s : String) :=
  Triptych.scannerParseMap Graph.grammar Graph.constraints Graph.valueFn id s

theorem Graph.parse_eq_gated (s : String) : Graph.parse s = Triptych.gatedParse Graph.IsValid Graph.computeValue s :=
  by
  unfold Graph.parse Graph.computeValue
  exact
    Triptych.scannerParseMap_eq_surfaceGated Graph.grammar Graph.constraints Graph.valueFn Graph.IsValid
      Graph.IsValid_equiv s

theorem Graph.parse_profile_result (s : String) :
    (Triptych.scannerParseMapProfile Graph.grammar Graph.constraints Graph.valueFn id s).result = Graph.parse s :=
  by
  unfold Graph.parse
  exact Triptych.scannerParseMapProfile_result Graph.grammar Graph.constraints Graph.valueFn id s

theorem Graph.parse_candidateChecks_le (s : String) :
    (Triptych.scannerParseMapProfile Graph.grammar Graph.constraints Graph.valueFn id s).candidateChecks ≤
      Triptych.scannerCandidateBudget Graph.grammar s :=
  Triptych.scannerParseMap_candidateChecks_le Graph.grammar Graph.constraints Graph.valueFn id s

theorem Graph.parse_candidateChecks_eq_zero_of_fastScan (s : String) (hunique : (Graph.grammar).staticUnique = true)
    {captures : Triptych.CaptureMap} (hscan : Triptych.fastScan Graph.grammar s = some captures) :
    (Triptych.scannerParseMapProfile Graph.grammar Graph.constraints Graph.valueFn id s).candidateChecks = 0 :=
  Triptych.scannerParseMap_candidateChecks_eq_zero_of_fastScan Graph.grammar Graph.constraints Graph.valueFn id s
    hunique hscan

theorem Graph.parse_sound (s : String) (g : Graph) :
    Graph.parse s = some g → Graph.IsValid s ∧ Graph.computeValue s = some g :=
  by
  rw [Graph.parse_eq_gated]
  exact Triptych.gatedParse_sound _ _ s g

theorem Graph.parse_complete (s : String) (g : Graph) :
    Graph.IsValid s → Graph.computeValue s = some g → Graph.parse s = some g :=
  by
  rw [Graph.parse_eq_gated]
  exact Triptych.gatedParse_complete _ _ s g

theorem Graph.parse_reject (s : String) : Graph.parse s = none ↔ ¬Graph.IsValid s :=
  by
  rw [Graph.parse_eq_gated]
  exact Triptych.gatedParse_reject _ _ Graph.computeValue_isSome s

theorem Graph.parse_view (s : String) :
    Graph.parse s = if decide (Graph.IsValid s) then (Graph.decodeView s).map Graph.View.denotation else none :=
  by
  rw [Graph.parse_eq_gated]
  unfold Triptych.gatedParse
  rw [Graph.computeValue_view]

theorem Graph.parse_eq_some_iff_view (s : String) (g : Graph) :
    Graph.parse s = some g ↔
      ∃ decodedView : Graph.View,
        Graph.decodeView s = some decodedView ∧ Graph.View.Valid decodedView ∧ Graph.View.denotation decodedView = g :=
  by
  constructor
  · intro hparse
    obtain ⟨hvalid, hvalue⟩ := Graph.parse_sound s g hparse
    obtain ⟨decodedView, hview, hvalidView⟩ := (Graph.IsValid_view s).mp hvalid
    refine ⟨decodedView, hview, hvalidView, ?_⟩
    rw [Graph.computeValue_view, hview] at hvalue
    exact Option.some.inj hvalue
  · rintro ⟨decodedView, hview, hvalidView, hvalue⟩
    apply Graph.parse_complete s g
    · exact (Graph.IsValid_view s).mpr ⟨decodedView, hview, hvalidView⟩
    · rw [Graph.computeValue_view, hview]
      exact congrArg some hvalue

theorem Graph.parse_eq_none_iff_view (s : String) :
    Graph.parse s = none ↔ ¬∃ v : Graph.View, Graph.decodeView s = some v ∧ Graph.View.Valid v :=
  by
  rw [Graph.parse_reject]
  constructor
  · intro hinvalid ⟨v, hview, hvalidView⟩
    exact hinvalid ((Graph.IsValid_view s).mpr ⟨v, hview, hvalidView⟩)
  · intro hnoview hvalid
    exact hnoview ((Graph.IsValid_view s).mp hvalid)
