/- Generated by Triptych from `triptych Graph`. -/

import Triptych.Architecture.Denote
import Triptych.Architecture.Derivation
import Triptych.Architecture.Value
import Triptych.Architecture.Constraint
import Triptych.Architecture.Assemble
import Triptych.Theorems.Reconcile
import Triptych.Theorems.Value
import Inputs.Graph

open Triptych
open GraphExample

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ═══════════════════════════════ spec ═══════════════════════════════
The more readable specification. Each production of the input grammar becomes an
inlined well-formedness predicate `IsWf.*` written as a plain existential over the
named captures, so you can read it side-by-side with the grammar and check that it
says the same thing. When present, `WfConstraints` contains capture-derived format
conditions and `Constraints` contains conditions that explicitly mention the final
`value`. Empty phases are omitted; `IsWf` and `IsValid` specialize accordingly.
This file is proof-free — it is what you cite. -/

def Graph.grammar : Grammar :=
  Grammar.mk "Graph"
    [Production.mk "Graph"
        [[SymItem.mk (Sym.ref "Order") false, SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "Cells") false]],
      Production.mk "Order" [[SymItem.mk (Sym.term TokClass.digit LenSpec.atLeastOne) false]],
      Production.mk "Cells"
        [[SymItem.mk (Sym.lit "") false], [SymItem.mk (Sym.term TokClass.bit LenSpec.atLeastOne) false]]]

inductive Graph.Derivation.Order where
  | alt0 (part0 : String)
  deriving Repr, DecidableEq

def Graph.Derivation.Order.render : Graph.Derivation.Order → String
  | .alt0 part0 => (part0 ++ "")

def Graph.Derivation.Order.Valid : Graph.Derivation.Order → Prop
  | .alt0 part0 => matchesTerm TokClass.digit (LenSpec.atLeastOne) part0

inductive Graph.Derivation.Cells where
  | alt0
  | alt1 (part0 : String)
  deriving Repr, DecidableEq

def Graph.Derivation.Cells.render : Graph.Derivation.Cells → String
  | .alt0 => ("" ++ "")
  | .alt1 part0 => (part0 ++ "")

def Graph.Derivation.Cells.Valid : Graph.Derivation.Cells → Prop
  | .alt0 => True
  | .alt1 part0 => matchesTerm TokClass.bit (LenSpec.atLeastOne) part0

inductive Graph.Derivation.Graph where
  | alt0 (part0 : Graph.Derivation.Order) (part2 : Graph.Derivation.Cells)
  deriving Repr, DecidableEq

def Graph.Derivation.Graph.render : Graph.Derivation.Graph → String
  | .alt0 part0 part2 => (Graph.Derivation.Order.render part0 ++ (":" ++ (Graph.Derivation.Cells.render part2 ++ "")))

def Graph.Derivation.Graph.Valid : Graph.Derivation.Graph → Prop
  | .alt0 part0 part2 => (Graph.Derivation.Order.Valid part0 ∧ Graph.Derivation.Cells.Valid part2)

def Graph.IsWf.Order (s : String) : Prop :=
  IsDigits s

def Graph.IsWf.Cells (s : String) : Prop :=
  s = "" ∨ IsBits s

def Graph.IsWf.Graph (s : String) : Prop :=
  ∃ order cells, (s = order ++ ":" ++ cells ∧ Graph.IsWf.Order order) ∧ Graph.IsWf.Cells cells

def Graph.value (order : String) (cells : String) :=
  toGraph order cells

def Graph.WfConstraints (cells : String) (order : String) : Prop :=
  (cells).length = upperTriangleSize order

def Graph.SatisfiesWfConstraints (s : String) : Prop :=
  Graph.WfConstraints (Triptych.component Graph.grammar s "Cells") (Triptych.component Graph.grammar s "Order")

abbrev Graph.IsWf (s : String) : Prop :=
  Graph.IsWf.Graph s ∧ Graph.SatisfiesWfConstraints s

abbrev Graph.IsValid (s : String) : Prop :=
  Graph.IsWf s

structure Graph.View where
  input : String
  order : String
  cells : String

def Graph.View.WfConstraints (v : Graph.View) : Prop :=
  Graph.WfConstraints (Graph.View.cells v) (Graph.View.order v)

abbrev Graph.View.Valid (v : Graph.View) : Prop :=
  Graph.View.WfConstraints v

def Graph.View.denotation (v : Graph.View) :=
  Graph.value (Graph.View.order v) (Graph.View.cells v)
