/- Generated by Triptych from `format_spec Datetime`. -/

import Triptych.Architecture.Denote
import Triptych.Architecture.Value
import Triptych.Architecture.Constraint
import Triptych.Architecture.Assemble
import Triptych.Theorems.Reconcile
import Triptych.Examples.Datetime.spec
import Triptych.Examples.Datetime.grammar

open Triptych
open Triptych.Examples.Datetime

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ══════════════════════════════ engine ══════════════════════════════
The executable counterpart of the spec. `decode` walks the grammar over an input
string and returns its captured components; `computeValue` then evaluates the value
function on those captures, and `isWf`/`isValid` decide well-formedness/acceptance.

Naming convention: CAPITALIZED `IsWf.*`/`IsValid` are the surface `Prop`s you READ
and reason about; lowercase `isWf`/`isValid` are the engine's executable deciders you
RUN (`#eval isValid s`, `#eval computeValue s`). The `equivalence` section below
proves the two describe the same language and value. -/

def Datetime.valueFn := fun env : Env =>
  epochMillis (((env : Env) "YYYY").getD "") (((env : Env) "MM").getD "") (((env : Env) "DD").getD "")
    (((env : Env) "Time.hh").getD "") (((env : Env) "Time.mm").getD "") (((env : Env) "ss").getD "")
    (((env : Env) "SSS").getD "") (((env : Env) "Offset.hh").getD "") (((env : Env) "Offset.mm").getD "")
    (((env : Env) "Offset").getD "")

def Datetime.constraints : List ConstraintEntry :=
  [ConstraintEntry.dsl
      (Constraint.and (Constraint.le (ValExpr.lit 1) (ValExpr.nat "MM"))
        (Constraint.le (ValExpr.nat "MM") (ValExpr.lit 12))),
    ConstraintEntry.dsl
      (Constraint.and (Constraint.le (ValExpr.lit 0) (ValExpr.nat "Time.hh"))
        (Constraint.le (ValExpr.nat "Time.hh") (ValExpr.lit 23))),
    ConstraintEntry.dsl
      (Constraint.and (Constraint.le (ValExpr.lit 0) (ValExpr.nat "Time.mm"))
        (Constraint.le (ValExpr.nat "Time.mm") (ValExpr.lit 59))),
    ConstraintEntry.dsl
      (Constraint.and (Constraint.le (ValExpr.lit 0) (ValExpr.nat "ss"))
        (Constraint.le (ValExpr.nat "ss") (ValExpr.lit 59))),
    ConstraintEntry.dsl
      (Constraint.and (Constraint.le (ValExpr.lit 0) (ValExpr.nat "Offset.hh"))
        (Constraint.le (ValExpr.nat "Offset.hh") (ValExpr.lit 23))),
    ConstraintEntry.dsl
      (Constraint.and (Constraint.le (ValExpr.lit 0) (ValExpr.nat "Offset.mm"))
        (Constraint.le (ValExpr.nat "Offset.mm") (ValExpr.lit 59))),
    ConstraintEntry.opaque fun env : Env =>
      dayBound (((env : Env) "YYYY").getD "") (((env : Env) "MM").getD "") (((env : Env) "DD").getD "")]

abbrev Datetime.isWf (s : String) : Prop :=
  Triptych.isWf Datetime.grammar Datetime.constraints s

abbrev Datetime.satisfiesConstraints (s : String) : Prop :=
  Triptych.satisfiesConstraints Datetime.grammar Datetime.constraints s

abbrev Datetime.isValid (s : String) : Prop :=
  Datetime.isWf s ∧ Datetime.satisfiesConstraints s

def Datetime.computeValue (s : String) :=
  Triptych.computeValueF Datetime.grammar Datetime.valueFn s

/- ════════════════════════════ equivalence ════════════════════════════
The auto-discharged guarantees relating the readable surface to the executable
engine: `IsWf_equiv` (+ its `Internal.matchesRef.*` lemmas) proves recognition
agrees, `computeValue_eq` proves the values agree, and the derived `DecidablePred`
instances make the surface predicates executable via the engine. No `sorry`. -/

theorem Datetime.Internal.matchesRef.YYYY (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "YYYY") s ↔ Datetime.IsWf.YYYY s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "YYYY" =
        some (Production.mk "YYYY" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 4)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.YYYY
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.MM (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "MM") s ↔ Datetime.IsWf.MM s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "MM" =
        some (Production.mk "MM" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.MM
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.DD (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "DD") s ↔ Datetime.IsWf.DD s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "DD" =
        some (Production.mk "DD" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.DD
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.Date (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 2) (Sym.ref "Date") s ↔ Datetime.IsWf.Date s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "Date" =
        some
          (Production.mk "Date"
            [[SymItem.mk (Sym.ref "YYYY") false, SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "MM") false,
                SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "DD") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.Date
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym,
    Datetime.Internal.matchesRef.YYYY, Datetime.Internal.matchesRef.MM, Datetime.Internal.matchesRef.DD]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.hh (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "hh") s ↔ Datetime.IsWf.hh s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "hh" =
        some (Production.mk "hh" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.hh
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.mm (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "mm") s ↔ Datetime.IsWf.mm s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "mm" =
        some (Production.mk "mm" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.mm
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.ss (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "ss") s ↔ Datetime.IsWf.ss s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "ss" =
        some (Production.mk "ss" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.ss
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.Time (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 2) (Sym.ref "Time") s ↔ Datetime.IsWf.Time s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "Time" =
        some
          (Production.mk "Time"
            [[SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "mm") false,
                SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "ss") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.Time
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym,
    Datetime.Internal.matchesRef.hh, Datetime.Internal.matchesRef.mm, Datetime.Internal.matchesRef.ss]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.SSS (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "SSS") s ↔ Datetime.IsWf.SSS s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "SSS" =
        some (Production.mk "SSS" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 3)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.SSS
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.Offset (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 2) (Sym.ref "Offset") s ↔ Datetime.IsWf.Offset s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "Offset" =
        some
          (Production.mk "Offset"
            [[SymItem.mk (Sym.lit "+") false, SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.ref "mm") false],
              [SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.ref "mm") false]])
      from rfl]
  dsimp only
  unfold matchesProd Datetime.IsWf.Offset
  simp (config := { maxSteps := 1000000 }) only [List.mem_cons, List.mem_singleton, List.not_mem_nil,
    Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_or_imp, exists_eq_left, exists_eq_left, if_true,
    if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, Datetime.Internal.matchesRef.hh,
    Datetime.Internal.matchesRef.mm]
  repeat'
    first
    | apply or_congr
    | ( simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left,
          ← and_assoc, exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
        try grind [String.append_assoc, String.append_empty])

theorem Datetime.Internal.matchesRef.Datetime (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 3) (Sym.ref "Datetime") s ↔ Datetime.IsWf.Datetime s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "Datetime" =
        some
          (Production.mk "Datetime"
            [[SymItem.mk (Sym.ref "Date") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.ref "Offset") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false]])
      from rfl]
  dsimp only
  unfold matchesProd Datetime.IsWf.Datetime
  simp (config := { maxSteps := 1000000 }) only [List.mem_cons, List.mem_singleton, List.not_mem_nil,
    Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_or_imp, exists_eq_left, exists_eq_left, if_true,
    if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, Datetime.Internal.matchesRef.Date,
    Datetime.Internal.matchesRef.Time, Datetime.Internal.matchesRef.SSS, Datetime.Internal.matchesRef.Offset]
  repeat'
    first
    | apply or_congr
    | ( simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left,
          ← and_assoc, exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
        try grind [String.append_assoc, String.append_empty])

theorem Datetime.IsWf_equiv (s : String) : IsWf Datetime.grammar s ↔ Datetime.IsWf.Datetime s :=
  by
  rw [isWf_eq_isWfProd_start, IsWfProd,
    show
      (Datetime.grammar).prod? (Datetime.grammar).start =
        some
          (Production.mk "Datetime"
            [[SymItem.mk (Sym.ref "Date") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.ref "Offset") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false]])
      from rfl]
  have hstart :
    ∀ n,
      matchesProd Datetime.grammar n
          (Production.mk "Datetime"
            [[SymItem.mk (Sym.ref "Date") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.ref "Offset") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false]])
          s =
        matchesSym Datetime.grammar (n + 1) (Sym.ref "Datetime") s :=
    by
    intro n
    rw [matchesSym,
      show
        (Datetime.grammar).prod? "Datetime" =
          some
            (Production.mk "Datetime"
              [[SymItem.mk (Sym.ref "Date") false],
                [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                  SymItem.mk (Sym.lit "Z") false],
                [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                  SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
                [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                  SymItem.mk (Sym.ref "Offset") false],
                [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                  SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false,
                  SymItem.mk (Sym.ref "Offset") false]])
        from rfl]
  show
    matchesProd Datetime.grammar (Datetime.grammar).prods.length
        (Production.mk "Datetime"
          [[SymItem.mk (Sym.ref "Date") false],
            [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
              SymItem.mk (Sym.lit "Z") false],
            [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
              SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
            [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
              SymItem.mk (Sym.ref "Offset") false],
            [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
              SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false]])
        s ↔
      _
  rw [hstart]
  exact Datetime.Internal.matchesRef.Datetime _ s

instance Datetime.instDecidableIsWf : DecidablePred Datetime.IsWf.Datetime := fun s =>
  @decidable_of_iff _ _ (Datetime.IsWf_equiv s) (Triptych.decIsWf Datetime.grammar (by decide) s)

instance Datetime.instDecidableSatisfiesConstraints : DecidablePred Datetime.SatisfiesConstraints := fun s => by
  simp only [Datetime.SatisfiesConstraints, Datetime.Constraints]; exact inferInstance

instance Datetime.instDecidableIsValid : DecidablePred Datetime.IsValid := fun s => inferInstanceAs (Decidable (_ ∧ _))

theorem Datetime.IsValid_equiv (s : String) : Datetime.IsValid s ↔ Datetime.isValid s :=
  by
  unfold Datetime.IsValid Datetime.isValid Datetime.isWf Datetime.satisfiesConstraints
  unfold Triptych.isWf Triptych.satisfiesConstraints
  rw [← Datetime.IsWf_equiv, ← decodeSome_iff_IsWf Datetime.grammar (by decide)]
  unfold Datetime.SatisfiesConstraints Datetime.Constraints Datetime.constraints
  simp only [Triptych.component, List.forall_mem_cons, List.forall_mem_singleton, List.not_mem_nil, forall_const,
    if_true, if_false, ConstraintEntry.wfPart, ConstraintEntry.valPart, Constraint.wfPart, Constraint.valPart,
    Constraint.isValueDependent, Constraint.eval, ValExpr.eval, presentCount, natOf_getD, intOf_getD, lenOf_getD,
    signOf_getD, and_true, true_and, false_implies, implies_true, Bool.false_eq_true]
  try grind

theorem Datetime.computeValue_eq (s : String) :
    Datetime.computeValue s =
      (decode Datetime.grammar s).map
        (fun _ =>
          Datetime.value (Triptych.component Datetime.grammar s "YYYY") (Triptych.component Datetime.grammar s "MM")
            (Triptych.component Datetime.grammar s "DD") (Triptych.component Datetime.grammar s "Time.hh")
            (Triptych.component Datetime.grammar s "Time.mm") (Triptych.component Datetime.grammar s "ss")
            (Triptych.component Datetime.grammar s "SSS") (Triptych.component Datetime.grammar s "Offset.hh")
            (Triptych.component Datetime.grammar s "Offset.mm") (Triptych.component Datetime.grammar s "Offset")) :=
  by
  unfold Datetime.computeValue Triptych.computeValueF Triptych.component Triptych.envOf Datetime.value Datetime.valueFn
  cases h : decode Datetime.grammar s with
  | none => simp
  | some m => simp only [Option.map_some, natOf_getD, intOf_getD, lenOf_getD, signOf_getD, ValExpr.eval]

/- ═══════════════════════════════ parser ══════════════════════════════
The generated correct-by-construction parser `parse` (= `computeValue` gated on the
decidable `isValid`) together with its guarantees — `parse_sound`, `parse_complete`,
`parse_reject` — all AUTO-DISCHARGED here. A verified parser, no `sorry`. -/

theorem Datetime.computeValue_isSome (s : String) : Datetime.isValid s → (Datetime.computeValue s).isSome :=
  by
  intro h
  unfold Datetime.isValid Datetime.isWf Triptych.isWf at h
  unfold Datetime.computeValue Triptych.computeValueF
  rw [Option.isSome_map]
  exact h.1.1

def Datetime.parse (s : String) :=
  Triptych.gatedParse Datetime.isValid Datetime.computeValue s

theorem Datetime.parse_sound (s : String) (i : Int) :
    Datetime.parse s = some i → Datetime.isValid s ∧ Datetime.computeValue s = some i :=
  Triptych.gatedParse_sound _ _ s i

theorem Datetime.parse_complete (s : String) (i : Int) :
    Datetime.isValid s → Datetime.computeValue s = some i → Datetime.parse s = some i :=
  Triptych.gatedParse_complete _ _ s i

theorem Datetime.parse_reject (s : String) : Datetime.parse s = none ↔ ¬Datetime.isValid s :=
  Triptych.gatedParse_reject _ _ Datetime.computeValue_isSome s
