/- Generated by Triptych from `triptych Graph`. -/

import Triptych.Architecture.Denote
import Triptych.Architecture.Value
import Triptych.Architecture.Constraint
import Triptych.Architecture.Assemble
import Triptych.Theorems.Reconcile
import Triptych.Examples.Graph.grammar

open Triptych
open Triptych.Examples.Graph

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ═══════════════════════════════ spec ═══════════════════════════════
The more readable specification. Each production of the input grammar becomes an
inlined well-formedness predicate `IsWf.*` written as a plain existential over the
named captures, so you can read it side-by-side with the grammar and check that it
says the same thing. `WfConstraints` contains capture-derived format conditions;
`Constraints` contains only conditions that explicitly mention the final `value`.
`IsValid` combines both phases. This file is proof-free — it is what you cite. -/

def Graph.grammar : Grammar :=
  Grammar.mk "Adj"
    [Production.mk "Adj" [[SymItem.mk (Sym.ref "Cells") false]],
      Production.mk "Cells" [[SymItem.mk (Sym.term TokClass.bit LenSpec.atLeastOne) false]]]

def Graph.IsWf.Cells (s : String) : Prop :=
  IsBits s

def Graph.IsWf.Adj (s : String) : Prop :=
  Graph.IsWf.Cells s

def Graph.value (cells : String) :=
  toGraph cells

def Graph.WfConstraints (cells : String) : Prop :=
  isTriangular cells = true

def Graph.SatisfiesWfConstraints (s : String) : Prop :=
  Graph.WfConstraints (Triptych.component Graph.grammar s "Cells")

abbrev Graph.IsWf (s : String) : Prop :=
  Graph.IsWf.Adj s ∧ Graph.SatisfiesWfConstraints s

abbrev Graph.SatisfiesConstraints (s : String) : Prop :=
  True

abbrev Graph.IsValid (s : String) : Prop :=
  Graph.IsWf s ∧ Graph.SatisfiesConstraints s
