/- Generated by Triptych from `triptych Duration`. -/

import Duration.parser
import Duration.grammar
import Duration.RuleRegistrySoundness
-- Retained only for Cedar's independent serializer roundtrip theorem.
import Cedar.Thm.Ext.Duration

open Triptych
open CedarExamples.Duration

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ══════════════════════ soundness · generated parser ══════════════════════
Obligations about the GENERATED parser `parse`. The `encode_*` obligations (a
serialized value is accepted, and evaluates back to itself) are discharged against
Cedar's Duration theorems; from them the printer theorems
(`parse_toString_roundtrip`/`toString_injective`/`normalize_eq_iff_parse_eq`) follow.
These same `encode_*` obligations are reused by the external section below. -/

theorem Duration.toSpec_ofSpec (s : String) (v : Int) :
    Duration.isValid s → Duration.computeValue s = some v →
      durationMillis (millisToDuration v) = v := by
  intro hvalid hvalue
  have hsurface : Duration.IsValid s := (Duration.IsValid_equiv s).mpr hvalid
  obtain ⟨view, hview, hvalidView⟩ :=
    (Duration.IsValid_view s).mp hsurface
  have hdenotation : Duration.View.denotation view = v := by
    rw [Duration.computeValue_view, hview] at hvalue
    exact Option.some.inj hvalue
  have hbounds := hvalidView.2
  unfold Duration.View.Constraints Duration.Constraints at hbounds
  change
    (-9223372036854775808 : Int) ≤ Duration.View.denotation view ∧
      Duration.View.denotation view ≤ (9223372036854775807 : Int) at hbounds
  rw [hdenotation] at hbounds
  unfold durationMillis millisToDuration
    Cedar.Spec.Ext.Datetime.Duration.toMilliseconds
  exact Int64.toInt_ofInt_of_le (by omega) (by omega)

theorem Duration.parse_sound_toSpec (s : String) (d : Cedar.Spec.Ext.Datetime.Duration) :
    Duration.parse s = some d → Duration.isValid s ∧ Duration.computeValue s = some (durationMillis d) :=
  Triptych.gatedParseOfSpec_sound_toSpec
    Duration.isValid Duration.computeValue millisToDuration durationMillis
      Duration.toSpec_ofSpec s d

theorem Duration.encode_accepted (d : Cedar.Spec.Ext.Datetime.Duration) :
    Duration.isValid (durationToStr d) := by
  have hparse : Cedar.Spec.Ext.Datetime.Duration.parse (durationToStr d) = some d := by
    change Cedar.Spec.Ext.Datetime.Duration.parse
      (Cedar.Spec.Ext.Datetime.Duration.toString d) = some d
    exact Cedar.Thm.Duration.parse_toString_roundtrip d
  exact (Duration.IsValid_equiv _).mp
    ((Duration.RuleRegistrySoundness.parser_agrees _ _).mp hparse).1

theorem Duration.encode_value (d : Cedar.Spec.Ext.Datetime.Duration) :
    Duration.computeValue (durationToStr d) = some (durationMillis d) := by
  have hparse : Cedar.Spec.Ext.Datetime.Duration.parse (durationToStr d) = some d := by
    change Cedar.Spec.Ext.Datetime.Duration.parse
      (Cedar.Spec.Ext.Datetime.Duration.toString d) = some d
    exact Cedar.Thm.Duration.parse_toString_roundtrip d
  exact ((Duration.RuleRegistrySoundness.parser_agrees _ _).mp hparse).2

theorem Duration.ofSpec_toSpec (d : Cedar.Spec.Ext.Datetime.Duration) :
    millisToDuration (durationMillis d) = d := by
  rcases d with ⟨val⟩
  simp [millisToDuration, durationMillis,
    Cedar.Spec.Ext.Datetime.Duration.toMilliseconds, Int64.ofInt_toInt]

theorem Duration.parse_toString_roundtrip (d : Cedar.Spec.Ext.Datetime.Duration) :
    Duration.parse (durationToStr d) = some d :=
  Triptych.gatedParseOfSpec_toString_roundtrip
    Duration.encode_accepted Duration.encode_value Duration.ofSpec_toSpec d

theorem Duration.toString_injective (d d' : Cedar.Spec.Ext.Datetime.Duration) (h : durationToStr d = durationToStr d') :
    d = d' :=
  Triptych.toString_injective Duration.parse_toString_roundtrip d d' h

theorem Duration.normalize_eq_iff_parse_eq (s s' : String) :
    (Duration.parse s).map durationToStr = (Duration.parse s').map durationToStr ↔
      Duration.parse s = Duration.parse s' :=
  Triptych.normalize_eq_iff_parse_eq Duration.parse_toString_roundtrip s s'

/- ══════════════════════ soundness · external parser ══════════════════════
Obligations for validating YOUR OWN external parser against this specification:
`extparse_sound`, `extparse_complete`, and `extparse_reject`, stated over the readable
surface `IsValid`/`computeValue`. Cedar's Duration parser theorems discharge them below.
The external printer theorems (`extparse_toString_*`) then follow, reusing the generated
section's `encode_*`. -/

theorem Duration.extparse_reject (s : String) :
    Cedar.Spec.Ext.Datetime.Duration.parse s = none ↔ ¬Duration.IsValid s := by
  exact Duration.RuleRegistrySoundness.parser_rejects_iff s

theorem Duration.extparse_eq_none_iff_view (s : String) :
    Cedar.Spec.Ext.Datetime.Duration.parse s = none ↔
      ¬∃ v : Duration.View, Duration.decodeView s = some v ∧ Duration.View.Valid v := by
  rw [Duration.extparse_reject]
  constructor
  · intro hinvalid ⟨v, hview, hvalidView⟩
    exact hinvalid ((Duration.IsValid_view s).mpr ⟨v, hview, hvalidView⟩)
  · intro hnoview hvalid
    exact hnoview ((Duration.IsValid_view s).mp hvalid)

theorem Duration.extparse_sound (s : String) (d : Cedar.Spec.Ext.Datetime.Duration) :
    Cedar.Spec.Ext.Datetime.Duration.parse s = some d →
      Duration.IsValid s ∧ Duration.computeValue s = some (durationMillis d) :=
  Duration.RuleRegistrySoundness.parser_sound s d

theorem Duration.extparse_complete (s : String) (d : Cedar.Spec.Ext.Datetime.Duration) :
    Duration.IsValid s →
      Duration.computeValue s = some (durationMillis d) → Cedar.Spec.Ext.Datetime.Duration.parse s = some d :=
  Duration.RuleRegistrySoundness.parser_complete s d

theorem Duration.extparse_eq_some_iff_view (s : String)
    (d : Cedar.Spec.Ext.Datetime.Duration) :
    Cedar.Spec.Ext.Datetime.Duration.parse s = some d ↔
      ∃ v : Duration.View,
        Duration.decodeView s = some v ∧
        Duration.View.Valid v ∧
        Duration.View.denotation v = durationMillis d := by
  constructor
  · intro hparse
    obtain ⟨hvalid, hvalue⟩ := Duration.extparse_sound s d hparse
    obtain ⟨v, hview, hvalidView⟩ := (Duration.IsValid_view s).mp hvalid
    refine ⟨v, hview, hvalidView, ?_⟩
    rw [Duration.computeValue_view, hview] at hvalue
    exact Option.some.inj hvalue
  · rintro ⟨v, hview, hvalidView, hvalue⟩
    apply Duration.extparse_complete s d
    · exact (Duration.IsValid_view s).mpr ⟨v, hview, hvalidView⟩
    · rw [Duration.computeValue_view, hview]
      exact congrArg some hvalue

theorem Duration.extparse_toString_roundtrip (d : Cedar.Spec.Ext.Datetime.Duration) :
    Cedar.Spec.Ext.Datetime.Duration.parse (durationToStr d) = some d :=
  Triptych.parse_toString_roundtrip Duration.extparse_complete
    (fun d => (Duration.IsValid_equiv (durationToStr d)).mpr (Duration.encode_accepted d)) Duration.encode_value d

theorem Duration.extparse_toString_injective (d d' : Cedar.Spec.Ext.Datetime.Duration)
    (h : durationToStr d = durationToStr d') : d = d' :=
  Triptych.toString_injective Duration.extparse_toString_roundtrip d d' h

theorem Duration.extparse_normalize_eq_iff_parse_eq (s s' : String) :
    (Cedar.Spec.Ext.Datetime.Duration.parse s).map durationToStr =
        (Cedar.Spec.Ext.Datetime.Duration.parse s').map durationToStr ↔
      Cedar.Spec.Ext.Datetime.Duration.parse s = Cedar.Spec.Ext.Datetime.Duration.parse s' :=
  Triptych.normalize_eq_iff_parse_eq Duration.extparse_toString_roundtrip s s'
