/- Generated by Triptych from `triptych BitVector`. -/

import Triptych.Architecture.GeneratedLinter
import Triptych.Architecture.Denote
import Triptych.Architecture.Derivation
import Triptych.Architecture.Value
import Triptych.Architecture.Constraint
import Triptych.Architecture.Assemble
import Triptych.Theorems.Reconcile
import Triptych.Theorems.Value
import Triptych.Theorems.DecodeLemmas
import Triptych.Theorems.Derivation
import Outputs.SMT.BitVector.spec
import Inputs.SMT.BitVector.grammar

open Triptych
open StrataExamples.SMT.BitVector

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false

/- ══════════════════════════════ engine ══════════════════════════════
The executable counterpart of the spec. `decode` walks the grammar over an input
string and returns its captured components; `computeValue` then evaluates the value
function on those captures. Generated `DecidablePred` instances make the readable
`IsWf` and `IsValid` predicates directly executable.
`decodeView` packages the exact input and value/constraint captures as a typed `View`.

The public format API stays capitalized: use `#eval decide (IsValid s)` and
`#eval computeValue s`. The equivalence section below proves that these readable
predicates execute through the generic Triptych interpreter. -/

instance BitVector.Derivation.BinaryDigits.instDecidableValid : DecidablePred BitVector.Derivation.BinaryDigits.Valid :=
  fun d => by cases d <;> simp only [BitVector.Derivation.BinaryDigits.Valid] <;> infer_instance

def BitVector.Derivation.BinaryDigits.capturesWith (qual : String) :
    BitVector.Derivation.BinaryDigits → Triptych.CaptureMap
  | .alt0 part0 => ([] ++ [])

instance BitVector.Derivation.Binary.instDecidableValid : DecidablePred BitVector.Derivation.Binary.Valid := fun d => by
  cases d <;> simp only [BitVector.Derivation.Binary.Valid] <;> infer_instance

def BitVector.Derivation.Binary.capturesWith (qual : String) : BitVector.Derivation.Binary → Triptych.CaptureMap
  | .alt0 part1 =>
    ([] ++
      (Triptych.referenceCaptures qual "BinaryDigits" (BitVector.Derivation.BinaryDigits.render part1) ++
          BitVector.Derivation.BinaryDigits.capturesWith "BinaryDigits" part1 ++
        []))

instance BitVector.Derivation.HexDigits.instDecidableValid : DecidablePred BitVector.Derivation.HexDigits.Valid :=
  fun d => by cases d <;> simp only [BitVector.Derivation.HexDigits.Valid] <;> infer_instance

def BitVector.Derivation.HexDigits.capturesWith (qual : String) : BitVector.Derivation.HexDigits → Triptych.CaptureMap
  | .alt0 part0 => ([] ++ [])

instance BitVector.Derivation.Hexadecimal.instDecidableValid : DecidablePred BitVector.Derivation.Hexadecimal.Valid :=
  fun d => by cases d <;> simp only [BitVector.Derivation.Hexadecimal.Valid] <;> infer_instance

def BitVector.Derivation.Hexadecimal.capturesWith (qual : String) :
    BitVector.Derivation.Hexadecimal → Triptych.CaptureMap
  | .alt0 part1 =>
    ([] ++
      (Triptych.referenceCaptures qual "HexDigits" (BitVector.Derivation.HexDigits.render part1) ++
          BitVector.Derivation.HexDigits.capturesWith "HexDigits" part1 ++
        []))

instance BitVector.Derivation.Payload.instDecidableValid : DecidablePred BitVector.Derivation.Payload.Valid := fun d =>
  by cases d <;> simp only [BitVector.Derivation.Payload.Valid] <;> infer_instance

def BitVector.Derivation.Payload.capturesWith (qual : String) : BitVector.Derivation.Payload → Triptych.CaptureMap
  | .alt0 part0 =>
    (Triptych.referenceCaptures qual "Binary" (BitVector.Derivation.Binary.render part0) ++
        BitVector.Derivation.Binary.capturesWith "Binary" part0 ++
      [])
  | .alt1 part0 =>
    (Triptych.referenceCaptures qual "Hexadecimal" (BitVector.Derivation.Hexadecimal.render part0) ++
        BitVector.Derivation.Hexadecimal.capturesWith "Hexadecimal" part0 ++
      [])

instance BitVector.Derivation.BitVector.instDecidableValid : DecidablePred BitVector.Derivation.BitVector.Valid :=
  fun d => by cases d <;> simp only [BitVector.Derivation.BitVector.Valid] <;> infer_instance

def BitVector.Derivation.BitVector.capturesWith (qual : String) : BitVector.Derivation.BitVector → Triptych.CaptureMap
  | .alt0 part1 =>
    ([] ++
      (Triptych.referenceCaptures qual "Payload" (BitVector.Derivation.Payload.render part1) ++
          BitVector.Derivation.Payload.capturesWith "Payload" part1 ++
        []))

def BitVector.valueFn := fun m : Triptych.CaptureMap =>
  toValue ((Triptych.CaptureMap.toEnv m "BinaryDigits").getD "") ((Triptych.CaptureMap.toEnv m "HexDigits").getD "")

def BitVector.constraints : List ConstraintEntry :=
  []

def BitVector.computeValue (s : String) :=
  Triptych.computeValueMap BitVector.grammar BitVector.valueFn s

def BitVector.View.ofMap (input : String) (m : Triptych.CaptureMap) : BitVector.View :=
  BitVector.View.mk input (Triptych.CaptureMap.toEnv m "BinaryDigits") (Triptych.CaptureMap.toEnv m "HexDigits")

def BitVector.decodeView (s : String) : Option BitVector.View :=
  (decode BitVector.grammar s).map (BitVector.View.ofMap s)

def BitVector.Derivation.BitVector.toView (d : BitVector.Derivation.BitVector) : BitVector.View :=
  BitVector.View.ofMap (BitVector.Derivation.BitVector.render d) (BitVector.Derivation.BitVector.capturesWith "" d)

/- ════════════════════════════ equivalence ════════════════════════════
The auto-discharged guarantees relating the readable surface to the executable
engine: `IsWfGrammar_equiv` proves grammar-layout agreement and `IsWf_equiv`
proves full well-formedness agreement. `computeValue_eq` proves the values agree,
while `decodeView_input`, `IsValid_view`, and `computeValue_view` expose the typed
parse view. Derived `DecidablePred` instances make the surface predicates executable
via the engine. No `sorry`. -/

theorem BitVector.Derivation.BinaryDigits.matches (qual : String) (fuel : Nat) (d : BitVector.Derivation.BinaryDigits)
    (hvalid : BitVector.Derivation.BinaryDigits.Valid d) :
    Triptych.ProdMatch BitVector.grammar qual (fuel + 1)
      (Production.mk "BinaryDigits" [[SymItem.mk (Sym.term TokClass.bit (LenSpec.atLeastOne)) false]])
      (BitVector.Derivation.BinaryDigits.render d) (BitVector.Derivation.BinaryDigits.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [BitVector.Derivation.BinaryDigits.Valid] at hvalid
    have hpart0 := hvalid
    simp only [BitVector.Derivation.BinaryDigits.render, BitVector.Derivation.BinaryDigits.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.term TokClass.bit (LenSpec.atLeastOne)) false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              Triptych.symMatch_term BitVector.grammar qual (fuel + 1) TokClass.bit (LenSpec.atLeastOne) part0 hpart0
          · exact Triptych.seqMatch_nil BitVector.grammar qual (fuel + 1))

theorem BitVector.Derivation.Binary.matches (qual : String) (fuel : Nat) (d : BitVector.Derivation.Binary)
    (hvalid : BitVector.Derivation.Binary.Valid d) :
    Triptych.ProdMatch BitVector.grammar qual (fuel + 2)
      (Production.mk "Binary" [[SymItem.mk (Sym.lit "b") false, SymItem.mk (Sym.ref "BinaryDigits") false]])
      (BitVector.Derivation.Binary.render d) (BitVector.Derivation.Binary.capturesWith qual d) :=
  by
  cases d with
  | alt0 part1 =>
    simp only [BitVector.Derivation.Binary.Valid] at hvalid
    have hpart1 := hvalid
    simp only [BitVector.Derivation.Binary.render, BitVector.Derivation.Binary.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.lit "b") false, SymItem.mk (Sym.ref "BinaryDigits") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          · exact Triptych.symMatch_lit BitVector.grammar qual (fuel + 2) "b"
          ·
            exact
              (by
                apply Triptych.seqMatch_required
                ·
                  exact
                    (by
                      simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                        (Triptych.symMatch_ref BitVector.grammar qual (((fuel + 0)) + 1) "BinaryDigits"
                          (Production.mk "BinaryDigits"
                            [[SymItem.mk (Sym.term TokClass.bit (LenSpec.atLeastOne)) false]])
                          (by rfl) (BitVector.Derivation.BinaryDigits.render part1)
                          (BitVector.Derivation.BinaryDigits.capturesWith "BinaryDigits" part1)
                          (BitVector.Derivation.BinaryDigits.matches "BinaryDigits" (fuel + 0) part1 hpart1)))
                · exact Triptych.seqMatch_nil BitVector.grammar qual (fuel + 2)))

theorem BitVector.Derivation.HexDigits.matches (qual : String) (fuel : Nat) (d : BitVector.Derivation.HexDigits)
    (hvalid : BitVector.Derivation.HexDigits.Valid d) :
    Triptych.ProdMatch BitVector.grammar qual (fuel + 1)
      (Production.mk "HexDigits" [[SymItem.mk (Sym.term TokClass.hexDigit (LenSpec.atLeastOne)) false]])
      (BitVector.Derivation.HexDigits.render d) (BitVector.Derivation.HexDigits.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [BitVector.Derivation.HexDigits.Valid] at hvalid
    have hpart0 := hvalid
    simp only [BitVector.Derivation.HexDigits.render, BitVector.Derivation.HexDigits.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.term TokClass.hexDigit (LenSpec.atLeastOne)) false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              Triptych.symMatch_term BitVector.grammar qual (fuel + 1) TokClass.hexDigit (LenSpec.atLeastOne) part0
                hpart0
          · exact Triptych.seqMatch_nil BitVector.grammar qual (fuel + 1))

theorem BitVector.Derivation.Hexadecimal.matches (qual : String) (fuel : Nat) (d : BitVector.Derivation.Hexadecimal)
    (hvalid : BitVector.Derivation.Hexadecimal.Valid d) :
    Triptych.ProdMatch BitVector.grammar qual (fuel + 2)
      (Production.mk "Hexadecimal" [[SymItem.mk (Sym.lit "x") false, SymItem.mk (Sym.ref "HexDigits") false]])
      (BitVector.Derivation.Hexadecimal.render d) (BitVector.Derivation.Hexadecimal.capturesWith qual d) :=
  by
  cases d with
  | alt0 part1 =>
    simp only [BitVector.Derivation.Hexadecimal.Valid] at hvalid
    have hpart1 := hvalid
    simp only [BitVector.Derivation.Hexadecimal.render, BitVector.Derivation.Hexadecimal.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.lit "x") false, SymItem.mk (Sym.ref "HexDigits") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          · exact Triptych.symMatch_lit BitVector.grammar qual (fuel + 2) "x"
          ·
            exact
              (by
                apply Triptych.seqMatch_required
                ·
                  exact
                    (by
                      simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                        (Triptych.symMatch_ref BitVector.grammar qual (((fuel + 0)) + 1) "HexDigits"
                          (Production.mk "HexDigits"
                            [[SymItem.mk (Sym.term TokClass.hexDigit (LenSpec.atLeastOne)) false]])
                          (by rfl) (BitVector.Derivation.HexDigits.render part1)
                          (BitVector.Derivation.HexDigits.capturesWith "HexDigits" part1)
                          (BitVector.Derivation.HexDigits.matches "HexDigits" (fuel + 0) part1 hpart1)))
                · exact Triptych.seqMatch_nil BitVector.grammar qual (fuel + 2)))

theorem BitVector.Derivation.Payload.matches (qual : String) (fuel : Nat) (d : BitVector.Derivation.Payload)
    (hvalid : BitVector.Derivation.Payload.Valid d) :
    Triptych.ProdMatch BitVector.grammar qual (fuel + 3)
      (Production.mk "Payload" [[SymItem.mk (Sym.ref "Binary") false], [SymItem.mk (Sym.ref "Hexadecimal") false]])
      (BitVector.Derivation.Payload.render d) (BitVector.Derivation.Payload.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [BitVector.Derivation.Payload.Valid] at hvalid
    have hpart0 := hvalid
    simp only [BitVector.Derivation.Payload.render, BitVector.Derivation.Payload.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.ref "Binary") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              (by
                simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                  (Triptych.symMatch_ref BitVector.grammar qual (((fuel + 0)) + 2) "Binary"
                    (Production.mk "Binary"
                      [[SymItem.mk (Sym.lit "b") false, SymItem.mk (Sym.ref "BinaryDigits") false]])
                    (by rfl) (BitVector.Derivation.Binary.render part0)
                    (BitVector.Derivation.Binary.capturesWith "Binary" part0)
                    (BitVector.Derivation.Binary.matches "Binary" (fuel + 0) part0 hpart0)))
          · exact Triptych.seqMatch_nil BitVector.grammar qual (fuel + 3))
  | alt1 part0 =>
    simp only [BitVector.Derivation.Payload.Valid] at hvalid
    have hpart0 := hvalid
    simp only [BitVector.Derivation.Payload.render, BitVector.Derivation.Payload.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.ref "Hexadecimal") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              (by
                simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                  (Triptych.symMatch_ref BitVector.grammar qual (((fuel + 0)) + 2) "Hexadecimal"
                    (Production.mk "Hexadecimal"
                      [[SymItem.mk (Sym.lit "x") false, SymItem.mk (Sym.ref "HexDigits") false]])
                    (by rfl) (BitVector.Derivation.Hexadecimal.render part0)
                    (BitVector.Derivation.Hexadecimal.capturesWith "Hexadecimal" part0)
                    (BitVector.Derivation.Hexadecimal.matches "Hexadecimal" (fuel + 0) part0 hpart0)))
          · exact Triptych.seqMatch_nil BitVector.grammar qual (fuel + 3))

theorem BitVector.Derivation.BitVector.matches (qual : String) (fuel : Nat) (d : BitVector.Derivation.BitVector)
    (hvalid : BitVector.Derivation.BitVector.Valid d) :
    Triptych.ProdMatch BitVector.grammar qual (fuel + 4)
      (Production.mk "BitVector" [[SymItem.mk (Sym.lit "#") false, SymItem.mk (Sym.ref "Payload") false]])
      (BitVector.Derivation.BitVector.render d) (BitVector.Derivation.BitVector.capturesWith qual d) :=
  by
  cases d with
  | alt0 part1 =>
    simp only [BitVector.Derivation.BitVector.Valid] at hvalid
    have hpart1 := hvalid
    simp only [BitVector.Derivation.BitVector.render, BitVector.Derivation.BitVector.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.lit "#") false, SymItem.mk (Sym.ref "Payload") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          · exact Triptych.symMatch_lit BitVector.grammar qual (fuel + 4) "#"
          ·
            exact
              (by
                apply Triptych.seqMatch_required
                ·
                  exact
                    (by
                      simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                        (Triptych.symMatch_ref BitVector.grammar qual (((fuel + 0)) + 3) "Payload"
                          (Production.mk "Payload"
                            [[SymItem.mk (Sym.ref "Binary") false], [SymItem.mk (Sym.ref "Hexadecimal") false]])
                          (by rfl) (BitVector.Derivation.Payload.render part1)
                          (BitVector.Derivation.Payload.capturesWith "Payload" part1)
                          (BitVector.Derivation.Payload.matches "Payload" (fuel + 0) part1 hpart1)))
                · exact Triptych.seqMatch_nil BitVector.grammar qual (fuel + 4)))

theorem BitVector.Derivation.BitVector.mem_fullParses (d : BitVector.Derivation.BitVector)
    (hvalid : BitVector.Derivation.BitVector.Valid d) :
    BitVector.Derivation.BitVector.capturesWith "" d ∈
      Triptych.fullParses BitVector.grammar (BitVector.Derivation.BitVector.render d) :=
  by
  apply
    Triptych.prodMatch_mem_fullParses BitVector.grammar
      (Production.mk "BitVector" [[SymItem.mk (Sym.lit "#") false, SymItem.mk (Sym.ref "Payload") false]]) (by rfl)
  simpa [BitVector.grammar] using (BitVector.Derivation.BitVector.matches "" 2 d hvalid)

theorem BitVector.Derivation.BitVector.decode_render_of_captureFunctional
    (hfunctional : Triptych.GrammarCaptureFunctional BitVector.grammar) (d : BitVector.Derivation.BitVector)
    (hvalid : BitVector.Derivation.BitVector.Valid d) :
    Triptych.decode BitVector.grammar (BitVector.Derivation.BitVector.render d) =
      some (BitVector.Derivation.BitVector.capturesWith "" d) :=
  Triptych.decode_eq_of_mem_fullParses hfunctional (mem_fullParses d hvalid)

theorem BitVector.decodeView_input {s : String} {v : BitVector.View} (h : BitVector.decodeView s = some v) :
    BitVector.View.input v = s := by
  unfold BitVector.decodeView at h
  rw [Option.map_eq_some_iff] at h
  obtain ⟨m, _, hv⟩ := h
  subst v
  rfl

theorem BitVector.Derivation.BitVector.decodeView_render_of_captureFunctional
    (hfunctional : Triptych.GrammarCaptureFunctional BitVector.grammar) (d : BitVector.Derivation.BitVector)
    (hvalid : BitVector.Derivation.BitVector.Valid d) :
    BitVector.decodeView (BitVector.Derivation.BitVector.render d) = some (BitVector.Derivation.BitVector.toView d) :=
  by
  unfold BitVector.decodeView BitVector.Derivation.BitVector.toView
  rw [BitVector.Derivation.BitVector.decode_render_of_captureFunctional hfunctional d hvalid]
  rfl

theorem BitVector.Internal.matchesRef.BinaryDigits (fuel : Nat) (s : String) :
    matchesSym BitVector.grammar (fuel + 1) (Sym.ref "BinaryDigits") s ↔ BitVector.IsWf.BinaryDigits s :=
  by
  rw [matchesSym,
    show
      (BitVector.grammar).prod? "BinaryDigits" =
        some (Production.mk "BinaryDigits" [[SymItem.mk (Sym.term TokClass.bit LenSpec.atLeastOne) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold BitVector.IsWf.BinaryDigits
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsBits_matchesTerm,
    IsFixedBits_matchesTerm, IsBitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem BitVector.Internal.matchesRef.Binary (fuel : Nat) (s : String) :
    matchesSym BitVector.grammar (fuel + 2) (Sym.ref "Binary") s ↔ BitVector.IsWf.Binary s :=
  by
  rw [matchesSym,
    show
      (BitVector.grammar).prod? "Binary" =
        some (Production.mk "Binary" [[SymItem.mk (Sym.lit "b") false, SymItem.mk (Sym.ref "BinaryDigits") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold BitVector.IsWf.Binary
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym,
    BitVector.Internal.matchesRef.BinaryDigits]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem BitVector.Internal.matchesRef.HexDigits (fuel : Nat) (s : String) :
    matchesSym BitVector.grammar (fuel + 1) (Sym.ref "HexDigits") s ↔ BitVector.IsWf.HexDigits s :=
  by
  rw [matchesSym,
    show
      (BitVector.grammar).prod? "HexDigits" =
        some (Production.mk "HexDigits" [[SymItem.mk (Sym.term TokClass.hexDigit LenSpec.atLeastOne) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold BitVector.IsWf.HexDigits
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsHexDigits_matchesTerm,
    IsFixedHexDigits_matchesTerm, IsHexDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem BitVector.Internal.matchesRef.Hexadecimal (fuel : Nat) (s : String) :
    matchesSym BitVector.grammar (fuel + 2) (Sym.ref "Hexadecimal") s ↔ BitVector.IsWf.Hexadecimal s :=
  by
  rw [matchesSym,
    show
      (BitVector.grammar).prod? "Hexadecimal" =
        some (Production.mk "Hexadecimal" [[SymItem.mk (Sym.lit "x") false, SymItem.mk (Sym.ref "HexDigits") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold BitVector.IsWf.Hexadecimal
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym,
    BitVector.Internal.matchesRef.HexDigits]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem BitVector.Internal.matchesRef.Payload (fuel : Nat) (s : String) :
    matchesSym BitVector.grammar (fuel + 3) (Sym.ref "Payload") s ↔ BitVector.IsWf.Payload s :=
  by
  rw [matchesSym,
    show
      (BitVector.grammar).prod? "Payload" =
        some
          (Production.mk "Payload" [[SymItem.mk (Sym.ref "Binary") false], [SymItem.mk (Sym.ref "Hexadecimal") false]])
      from rfl]
  dsimp only
  unfold matchesProd BitVector.IsWf.Payload
  simp (config := { maxSteps := 1000000 }) only [List.mem_cons, List.mem_singleton, List.not_mem_nil,
    Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_or_imp, exists_eq_left, exists_eq_left, if_true,
    if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym,
    BitVector.Internal.matchesRef.Binary, BitVector.Internal.matchesRef.Hexadecimal]
  repeat'
    first
    | apply or_congr
    | ( simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left,
          ← and_assoc, exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
        try grind [String.append_assoc, String.append_empty])

theorem BitVector.Internal.matchesRef.BitVector (fuel : Nat) (s : String) :
    matchesSym BitVector.grammar (fuel + 4) (Sym.ref "BitVector") s ↔ BitVector.IsWf.BitVector s :=
  by
  rw [matchesSym,
    show
      (BitVector.grammar).prod? "BitVector" =
        some (Production.mk "BitVector" [[SymItem.mk (Sym.lit "#") false, SymItem.mk (Sym.ref "Payload") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold BitVector.IsWf.BitVector
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym,
    BitVector.Internal.matchesRef.Payload]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem BitVector.IsWfGrammar_equiv (s : String) : Triptych.IsWf BitVector.grammar s ↔ BitVector.IsWf.BitVector s :=
  by
  rw [isWf_eq_isWfProd_start, IsWfProd,
    show
      (BitVector.grammar).prod? (BitVector.grammar).start =
        some (Production.mk "BitVector" [[SymItem.mk (Sym.lit "#") false, SymItem.mk (Sym.ref "Payload") false]])
      from rfl]
  have hstart :
    ∀ n,
      matchesProd BitVector.grammar n
          (Production.mk "BitVector" [[SymItem.mk (Sym.lit "#") false, SymItem.mk (Sym.ref "Payload") false]]) s =
        matchesSym BitVector.grammar (n + 1) (Sym.ref "BitVector") s :=
    by
    intro n
    rw [matchesSym,
      show
        (BitVector.grammar).prod? "BitVector" =
          some (Production.mk "BitVector" [[SymItem.mk (Sym.lit "#") false, SymItem.mk (Sym.ref "Payload") false]])
        from rfl]
  show
    matchesProd BitVector.grammar (BitVector.grammar).prods.length
        (Production.mk "BitVector" [[SymItem.mk (Sym.lit "#") false, SymItem.mk (Sym.ref "Payload") false]]) s ↔
      _
  rw [hstart]
  exact BitVector.Internal.matchesRef.BitVector _ s

theorem BitVector.IsWf_equiv (s : String) :
    BitVector.IsWf s ↔ Triptych.isWf BitVector.grammar BitVector.constraints s :=
  by
  unfold BitVector.IsWf Triptych.isWf
  rw [← BitVector.IsWfGrammar_equiv, ← decodeSome_iff_IsWf BitVector.grammar (by decide)]
  unfold BitVector.constraints
  simp only [Triptych.component, Triptych.componentList, Triptych.envOf, Triptych.captureMapOf, List.forall_mem_cons,
    List.forall_mem_singleton, List.not_mem_nil, forall_const, ConstraintEntry.wfPart, Constraint.eval, ValExpr.eval,
    presentCount, natOf_getD, intOf_getD, lenOf_getD, countOf_getD, signOf_getD, Env.countVal, and_true, true_and,
    false_implies, implies_true, Bool.false_eq_true]
  try grind

theorem BitVector.IsValid_equiv (s : String) :
    BitVector.IsValid s ↔
      Triptych.isWf BitVector.grammar BitVector.constraints s ∧
        Triptych.satisfiesConstraints BitVector.grammar BitVector.constraints s :=
  by
  unfold BitVector.IsValid
  rw [(BitVector.IsWf_equiv s)]
  unfold Triptych.satisfiesConstraints Triptych.captureMapOf BitVector.constraints
  simp only [List.forall_mem_cons, List.forall_mem_singleton, List.not_mem_nil, ConstraintEntry.valPart, false_implies,
    true_and, and_true]
  constructor
  · intro h
    exact ⟨h, fun _ => True.intro⟩
  · exact And.left

instance BitVector.instDecidableGrammar : DecidablePred BitVector.IsWf.BitVector := fun s =>
  @decidable_of_iff _ _ (BitVector.IsWfGrammar_equiv s) (Triptych.decIsWf BitVector.grammar (by decide) s)

instance BitVector.instDecidableIsWf : DecidablePred BitVector.IsWf := fun s =>
  @decidable_of_iff _ _ (BitVector.IsWf_equiv s).symm inferInstance

instance BitVector.instDecidableIsValid : DecidablePred BitVector.IsValid := fun s => inferInstance

theorem BitVector.IsValid_view (s : String) :
    BitVector.IsValid s ↔ ∃ v : BitVector.View, BitVector.decodeView s = some v ∧ BitVector.View.Valid v :=
  by
  constructor
  · intro hvalid
    have hengine := (BitVector.IsValid_equiv s).mp hvalid
    have hsome : (decode BitVector.grammar s).isSome = true := by exact hengine.1.1
    obtain ⟨m, hm⟩ := Option.isSome_iff_exists.mp hsome
    refine ⟨BitVector.View.ofMap s m, ?_, ?_⟩
    · unfold BitVector.decodeView
      simp [hm]
    · exact True.intro
  · rintro ⟨v, hview, hvalid⟩
    unfold BitVector.decodeView at hview
    rw [Option.map_eq_some_iff] at hview
    obtain ⟨m, hm, hv⟩ := hview
    subst v
    have hdecoded : (decode BitVector.grammar s).isSome = true := by simp [hm]
    have hgrammar :=
      (BitVector.IsWfGrammar_equiv s).mp ((decodeSome_iff_IsWf BitVector.grammar (by decide) s).mp hdecoded)
    exact hgrammar

theorem BitVector.computeValue_eq (s : String) :
    BitVector.computeValue s =
      (decode BitVector.grammar s).map
        (fun _ =>
          BitVector.value (Triptych.component BitVector.grammar s "BinaryDigits")
            (Triptych.component BitVector.grammar s "HexDigits")) :=
  by
  unfold BitVector.computeValue Triptych.computeValueMap Triptych.component Triptych.envOf Triptych.captureMapOf
    BitVector.value BitVector.valueFn
  cases h : decode BitVector.grammar s with
  | none => simp
  | some m => simp [natOf_getD, intOf_getD, lenOf_getD, countOf_getD, signOf_getD, Env.countVal, ValExpr.eval]

theorem BitVector.computeValue_of_decode {s : String} {m : Triptych.CaptureMap}
    (h : decode BitVector.grammar s = some m) :
    BitVector.computeValue s =
      some
        (BitVector.value ((Triptych.CaptureMap.toEnv m "BinaryDigits").getD "")
          ((Triptych.CaptureMap.toEnv m "HexDigits").getD "")) :=
  by
  rw [BitVector.computeValue_eq, h]
  simp only [Option.map_some, Triptych.component_eq_of_decode h "BinaryDigits",
    Triptych.component_eq_of_decode h "HexDigits"]

theorem BitVector.computeValue_view (s : String) :
    BitVector.computeValue s = (BitVector.decodeView s).map BitVector.View.denotation :=
  by
  unfold BitVector.decodeView
  cases h : decode BitVector.grammar s with
  |
    none =>
    rw [show BitVector.computeValue s = none by
        rw [BitVector.computeValue_eq, h]
        rfl]
    rfl
  | some m =>
    rw [BitVector.computeValue_of_decode h]
    simp only [Option.map_some]
    rfl

/- ═══════════════════════════════ parser ══════════════════════════════
The generated correct-by-construction parser `parse` (= `computeValue` gated on the
decidable `IsValid`) together with its guarantees — `parse_sound`, `parse_complete`,
`parse_reject`, `parse_view`, and typed `parse_eq_some_iff_view` /
`parse_eq_none_iff_view` normal forms — all AUTO-DISCHARGED here.
When an external parser is declared, `checkedExtParse` additionally validates each
external result against this parser and ships an AUTO-DISCHARGED soundness theorem.
A verified parser, no `sorry`. -/

theorem BitVector.computeValue_isSome (s : String) : BitVector.IsValid s → (BitVector.computeValue s).isSome :=
  by
  intro h
  have hengine := (BitVector.IsValid_equiv s).mp h
  unfold Triptych.isWf at hengine
  unfold BitVector.computeValue Triptych.computeValueMap
  rw [Option.isSome_map]
  exact hengine.1.1

def BitVector.parse (s : String) :=
  Triptych.gatedParse BitVector.IsValid BitVector.computeValue s

theorem BitVector.parse_sound (s : String) (v : Value) :
    BitVector.parse s = some v → BitVector.IsValid s ∧ BitVector.computeValue s = some v :=
  Triptych.gatedParse_sound _ _ s v

theorem BitVector.parse_complete (s : String) (v : Value) :
    BitVector.IsValid s → BitVector.computeValue s = some v → BitVector.parse s = some v :=
  Triptych.gatedParse_complete _ _ s v

theorem BitVector.parse_reject (s : String) : BitVector.parse s = none ↔ ¬BitVector.IsValid s :=
  Triptych.gatedParse_reject _ _ BitVector.computeValue_isSome s

theorem BitVector.parse_view (s : String) :
    BitVector.parse s =
      if decide (BitVector.IsValid s) then (BitVector.decodeView s).map BitVector.View.denotation else none :=
  by
  unfold BitVector.parse Triptych.gatedParse
  rw [BitVector.computeValue_view]

theorem BitVector.parse_eq_some_iff_view (s : String) (v : Value) :
    BitVector.parse s = some v ↔
      ∃ decodedView : BitVector.View,
        BitVector.decodeView s = some decodedView ∧
          BitVector.View.Valid decodedView ∧ BitVector.View.denotation decodedView = v :=
  by
  constructor
  · intro hparse
    obtain ⟨hvalid, hvalue⟩ := BitVector.parse_sound s v hparse
    obtain ⟨decodedView, hview, hvalidView⟩ := (BitVector.IsValid_view s).mp hvalid
    refine ⟨decodedView, hview, hvalidView, ?_⟩
    rw [BitVector.computeValue_view, hview] at hvalue
    exact Option.some.inj hvalue
  · rintro ⟨decodedView, hview, hvalidView, hvalue⟩
    apply BitVector.parse_complete s v
    · exact (BitVector.IsValid_view s).mpr ⟨decodedView, hview, hvalidView⟩
    · rw [BitVector.computeValue_view, hview]
      exact congrArg some hvalue

theorem BitVector.parse_eq_none_iff_view (s : String) :
    BitVector.parse s = none ↔ ¬∃ v : BitVector.View, BitVector.decodeView s = some v ∧ BitVector.View.Valid v :=
  by
  rw [BitVector.parse_reject]
  constructor
  · intro hinvalid ⟨v, hview, hvalidView⟩
    exact hinvalid ((BitVector.IsValid_view s).mpr ⟨v, hview, hvalidView⟩)
  · intro hnoview hvalid
    exact hnoview ((BitVector.IsValid_view s).mp hvalid)
