/- Generated by Triptych from `triptych BitVector`. -/

import Triptych.Architecture.Denote
import Triptych.Architecture.Derivation
import Triptych.Architecture.Value
import Triptych.Architecture.Constraint
import Triptych.Architecture.Assemble
import Triptych.Theorems.Reconcile
import Triptych.Theorems.Value
import Inputs.SMT.BitVector.grammar

open Triptych
open StrataExamples.SMT.BitVector

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ═══════════════════════════════ spec ═══════════════════════════════
The more readable specification. Each production of the input grammar becomes an
inlined well-formedness predicate `IsWf.*` written as a plain existential over the
named captures, so you can read it side-by-side with the grammar and check that it
says the same thing. When present, `WfConstraints` contains capture-derived format
conditions and `Constraints` contains conditions that explicitly mention the final
`value`. Empty phases are omitted; `IsWf` and `IsValid` specialize accordingly.
This file is proof-free — it is what you cite. -/

def BitVector.grammar : Grammar :=
  Grammar.mk "BitVector"
    [Production.mk "BitVector" [[SymItem.mk (Sym.lit "#") false, SymItem.mk (Sym.ref "Payload") false]],
      Production.mk "Payload" [[SymItem.mk (Sym.ref "Binary") false], [SymItem.mk (Sym.ref "Hexadecimal") false]],
      Production.mk "Binary" [[SymItem.mk (Sym.lit "b") false, SymItem.mk (Sym.ref "BinaryDigits") false]],
      Production.mk "Hexadecimal" [[SymItem.mk (Sym.lit "x") false, SymItem.mk (Sym.ref "HexDigits") false]],
      Production.mk "BinaryDigits" [[SymItem.mk (Sym.term TokClass.bit LenSpec.atLeastOne) false]],
      Production.mk "HexDigits" [[SymItem.mk (Sym.term TokClass.hexDigit LenSpec.atLeastOne) false]]]

inductive BitVector.Derivation.BinaryDigits where
  | alt0 (part0 : String)
  deriving Repr, DecidableEq

def BitVector.Derivation.BinaryDigits.render : BitVector.Derivation.BinaryDigits → String
  | .alt0 part0 => (part0 ++ "")

def BitVector.Derivation.BinaryDigits.Valid : BitVector.Derivation.BinaryDigits → Prop
  | .alt0 part0 => matchesTerm TokClass.bit (LenSpec.atLeastOne) part0

inductive BitVector.Derivation.Binary where
  | alt0 (part1 : BitVector.Derivation.BinaryDigits)
  deriving Repr, DecidableEq

def BitVector.Derivation.Binary.render : BitVector.Derivation.Binary → String
  | .alt0 part1 => ("b" ++ (BitVector.Derivation.BinaryDigits.render part1 ++ ""))

def BitVector.Derivation.Binary.Valid : BitVector.Derivation.Binary → Prop
  | .alt0 part1 => BitVector.Derivation.BinaryDigits.Valid part1

inductive BitVector.Derivation.HexDigits where
  | alt0 (part0 : String)
  deriving Repr, DecidableEq

def BitVector.Derivation.HexDigits.render : BitVector.Derivation.HexDigits → String
  | .alt0 part0 => (part0 ++ "")

def BitVector.Derivation.HexDigits.Valid : BitVector.Derivation.HexDigits → Prop
  | .alt0 part0 => matchesTerm TokClass.hexDigit (LenSpec.atLeastOne) part0

inductive BitVector.Derivation.Hexadecimal where
  | alt0 (part1 : BitVector.Derivation.HexDigits)
  deriving Repr, DecidableEq

def BitVector.Derivation.Hexadecimal.render : BitVector.Derivation.Hexadecimal → String
  | .alt0 part1 => ("x" ++ (BitVector.Derivation.HexDigits.render part1 ++ ""))

def BitVector.Derivation.Hexadecimal.Valid : BitVector.Derivation.Hexadecimal → Prop
  | .alt0 part1 => BitVector.Derivation.HexDigits.Valid part1

inductive BitVector.Derivation.Payload where
  | alt0 (part0 : BitVector.Derivation.Binary)
  | alt1 (part0 : BitVector.Derivation.Hexadecimal)
  deriving Repr, DecidableEq

def BitVector.Derivation.Payload.render : BitVector.Derivation.Payload → String
  | .alt0 part0 => (BitVector.Derivation.Binary.render part0 ++ "")
  | .alt1 part0 => (BitVector.Derivation.Hexadecimal.render part0 ++ "")

def BitVector.Derivation.Payload.Valid : BitVector.Derivation.Payload → Prop
  | .alt0 part0 => BitVector.Derivation.Binary.Valid part0
  | .alt1 part0 => BitVector.Derivation.Hexadecimal.Valid part0

inductive BitVector.Derivation.BitVector where
  | alt0 (part1 : BitVector.Derivation.Payload)
  deriving Repr, DecidableEq

def BitVector.Derivation.BitVector.render : BitVector.Derivation.BitVector → String
  | .alt0 part1 => ("#" ++ (BitVector.Derivation.Payload.render part1 ++ ""))

def BitVector.Derivation.BitVector.Valid : BitVector.Derivation.BitVector → Prop
  | .alt0 part1 => BitVector.Derivation.Payload.Valid part1

def BitVector.IsWf.BinaryDigits (s : String) : Prop :=
  IsBits s

def BitVector.IsWf.Binary (s : String) : Prop :=
  ∃ binaryDigits, s = "b" ++ binaryDigits ∧ BitVector.IsWf.BinaryDigits binaryDigits

def BitVector.IsWf.HexDigits (s : String) : Prop :=
  IsHexDigits s

def BitVector.IsWf.Hexadecimal (s : String) : Prop :=
  ∃ hexDigits, s = "x" ++ hexDigits ∧ BitVector.IsWf.HexDigits hexDigits

def BitVector.IsWf.Payload (s : String) : Prop :=
  BitVector.IsWf.Binary s ∨ BitVector.IsWf.Hexadecimal s

def BitVector.IsWf.BitVector (s : String) : Prop :=
  ∃ payload, s = "#" ++ payload ∧ BitVector.IsWf.Payload payload

def BitVector.value (binaryDigits : String) (hexDigits : String) :=
  toValue binaryDigits hexDigits

abbrev BitVector.IsWf (s : String) : Prop :=
  BitVector.IsWf.BitVector s

abbrev BitVector.IsValid (s : String) : Prop :=
  BitVector.IsWf s

structure BitVector.View where
  input : String
  binaryDigits : Option String
  hexDigits : Option String

abbrev BitVector.View.Valid (_ : BitVector.View) : Prop :=
  True

def BitVector.View.denotation (v : BitVector.View) :=
  BitVector.value ((BitVector.View.binaryDigits v).getD "") ((BitVector.View.hexDigits v).getD "")
