import Decimal.RuleRegistryProof

/-!
# End-to-end Decimal soundness from executable rules

The proofs in this module use no Cedar Decimal soundness/completeness theorem and no handwritten
`Decimal.CedarBridge`. They compose the executable parser summary with the specification and
decoder facts generated by Triptych.
-/

open Triptych

namespace Decimal.RuleRegistrySoundness

open Decimal.RuleRegistryProof

private theorem int64Bounds (i : Int64) :
    (-9223372036854775808 : Int) ≤ i.toInt ∧
      i.toInt ≤ (9223372036854775807 : Int) := by
  have hrange : Int64.«MIN» ≤ i.toInt ∧ i.toInt ≤ Int64.«MAX» :=
    (Int64.ofInt?_some_iff (i := i.toInt)).mpr (by
      simpa using Int64.ofInt?_toInt i)
  simpa only [Int64.«MIN», Int64.«MAX»] using hrange

private theorem constraintsOfDecode {s sgn natural fraction : String}
    (hdecode :
      decode Decimal.grammar s =
        some [("Sign", sgn), ("Natural", natural), ("Fraction", fraction)])
    (hconstraints : Decimal.Constraints sgn natural fraction) :
    Decimal.SatisfiesConstraints s := by
  apply (Decimal.SatisfiesConstraints_of_decode hdecode).mpr
  simpa [CaptureMap.toEnv] using hconstraints

/-- Cedar's executable parser returns exactly the values accepted and denoted by Triptych. -/
theorem parser_agrees (s : String) (d : Cedar.Spec.Ext.Decimal) :
    Cedar.Spec.Ext.Decimal.parse s = some d ↔
      Decimal.IsValid s ∧ Decimal.computeValue s = some (Int64.toInt d) := by
  constructor
  · intro hparse
    have hparseEq := hparse
    triptych_sound at hparse
    obtain ⟨_, _, _, _, hs, hnatural, hfraction, _⟩ :=
      hparse
    have hisWf : Decimal.IsWf.Decimal s :=
      ⟨_, _, _, ⟨⟨hs, by assumption⟩, hnatural⟩, hfraction⟩
    obtain ⟨sgn, natural, fraction, hdecode, hsgn, hs', hnatural', hfraction'⟩ :=
      decode_parts_of_isWf hisWf
    have hparseValue :=
      parse_of_parts s sgn natural fraction hs' hsgn hnatural' hfraction'
    have hofInt : Int64.ofInt? (Decimal.value sgn natural fraction) = some d := by
      rw [hparseEq] at hparseValue
      exact hparseValue.symm
    have hvalue : Decimal.value sgn natural fraction = Int64.toInt d :=
      (Int64.ofInt?_some_toInt hofInt).symm
    have hpartConstraints : Decimal.Constraints sgn natural fraction := by
      unfold Decimal.Constraints
      rw [hvalue]
      exact int64Bounds d
    have hconstraints := constraintsOfDecode hdecode hpartConstraints
    refine ⟨⟨hisWf, hconstraints⟩, ?_⟩
    rw [Decimal.computeValue_of_decode hdecode]
    simpa [CaptureMap.toEnv] using congrArg some hvalue
  · rintro ⟨hvalid, hcompute⟩
    obtain ⟨sgn, natural, fraction, hdecode, hsgn, hs, hnatural, hfraction⟩ :=
      decode_parts_of_isWf hvalid.1
    have hvalue : Decimal.value sgn natural fraction = Int64.toInt d := by
      rw [Decimal.computeValue_of_decode hdecode] at hcompute
      simpa [CaptureMap.toEnv] using Option.some.inj hcompute
    rw [parse_of_parts s sgn natural fraction hs hsgn hnatural hfraction, hvalue]
    exact Int64.ofInt?_toInt d

/-- Successful parsing is sound for the readable generated specification. -/
theorem parser_sound (s : String) (d : Cedar.Spec.Ext.Decimal) :
    Cedar.Spec.Ext.Decimal.parse s = some d →
      Decimal.IsValid s ∧ Decimal.computeValue s = some (Int64.toInt d) :=
  (parser_agrees s d).mp

/-- Every accepted generated specification value is returned by Cedar's parser. -/
theorem parser_complete (s : String) (d : Cedar.Spec.Ext.Decimal) :
    Decimal.IsValid s → Decimal.computeValue s = some (Int64.toInt d) →
      Cedar.Spec.Ext.Decimal.parse s = some d := by
  intro hvalid hvalue
  exact (parser_agrees s d).mpr ⟨hvalid, hvalue⟩

/-- Proof-facing typed-view normal form of Cedar's executable parser. -/
theorem parser_eq_some_iff_view (s : String) (d : Cedar.Spec.Ext.Decimal) :
    Cedar.Spec.Ext.Decimal.parse s = some d ↔
      ∃ v : Decimal.View,
        Decimal.decodeView s = some v ∧
        Decimal.View.Valid v ∧
        Decimal.View.denotation v = Int64.toInt d := by
  rw [parser_agrees]
  constructor
  · rintro ⟨hvalid, hvalue⟩
    obtain ⟨v, hview, hvalidView⟩ := (Decimal.IsValid_view s).mp hvalid
    refine ⟨v, hview, hvalidView, ?_⟩
    rw [Decimal.computeValue_view, hview] at hvalue
    exact Option.some.inj hvalue
  · rintro ⟨v, hview, hvalidView, hvalue⟩
    refine ⟨(Decimal.IsValid_view s).mpr ⟨v, hview, hvalidView⟩, ?_⟩
    rw [Decimal.computeValue_view, hview]
    exact congrArg some hvalue

/-- Cedar rejects exactly the strings rejected by the readable generated specification. -/
theorem parser_rejects_iff (s : String) :
    Cedar.Spec.Ext.Decimal.parse s = none ↔ ¬Decimal.IsValid s := by
  constructor
  · intro hnone hvalid
    obtain ⟨sgn, natural, fraction, hdecode, hsgn, hs, hnatural, hfraction⟩ :=
      decode_parts_of_isWf hvalid.1
    have hcompute := Decimal.computeValue_of_decode hdecode
    have hconstraints :
        (-9223372036854775808 : Int) ≤ Decimal.value sgn natural fraction ∧
          Decimal.value sgn natural fraction ≤ (9223372036854775807 : Int) := by
      have hsurface := hvalid.2
      rw [Decimal.SatisfiesConstraints_of_decode hdecode] at hsurface
      simpa [Decimal.Constraints, CaptureMap.toEnv] using hsurface
    have hofInt :
        Int64.ofInt? (Decimal.value sgn natural fraction) =
          some (Int64.ofInt (Decimal.value sgn natural fraction)) := by
      apply Int64.ofInt?_some_iff.mp
      simpa only [Int64.«MIN», Int64.«MAX»] using hconstraints
    have hsome :
        Cedar.Spec.Ext.Decimal.parse s =
          some (Int64.ofInt (Decimal.value sgn natural fraction)) := by
      rw [parse_of_parts s sgn natural fraction hs hsgn hnatural hfraction]
      exact hofInt
    rw [hnone] at hsome
    simp at hsome
  · intro hinvalid
    cases hparse : Cedar.Spec.Ext.Decimal.parse s with
    | none => rfl
    | some d => exact (hinvalid ((parser_agrees s d).mp hparse).1).elim

/-- Proof-facing typed-view normal form of Cedar's rejection behavior. -/
theorem parser_eq_none_iff_view (s : String) :
    Cedar.Spec.Ext.Decimal.parse s = none ↔
      ¬∃ v : Decimal.View, Decimal.decodeView s = some v ∧ Decimal.View.Valid v := by
  rw [parser_rejects_iff]
  exact not_congr (Decimal.IsValid_view s)

end Decimal.RuleRegistrySoundness
