/- Generated by Triptych from `triptych Decimal`. -/

import Triptych.Architecture.Denote
import Triptych.Architecture.Value
import Triptych.Architecture.Constraint
import Triptych.Architecture.Assemble
import Triptych.Theorems.Reconcile

open Triptych

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ═══════════════════════════════ spec ═══════════════════════════════
The more readable specification. Each production of the input grammar becomes an
inlined well-formedness predicate `IsWf.*` written as a plain existential over the
named captures, so you can read it side-by-side with the grammar and check that it
says the same thing. `WfConstraints` contains capture-derived format conditions;
`Constraints` contains only conditions that explicitly mention the final `value`.
`IsValid` combines both phases. This file is proof-free — it is what you cite. -/

def Decimal.grammar : Grammar :=
  Grammar.mk "Decimal"
    [Production.mk "Decimal"
        [[SymItem.mk (Sym.ref "Sign") false, SymItem.mk (Sym.ref "Natural") false, SymItem.mk (Sym.lit ".") false,
            SymItem.mk (Sym.ref "Fraction") false]],
      Production.mk "Sign" [[SymItem.mk (Sym.lit "-") true]],
      Production.mk "Natural" [[SymItem.mk (Sym.term TokClass.digit LenSpec.atLeastOne) false]],
      Production.mk "Fraction" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.between 1 4)) false]]]

def Decimal.IsWf.Sign (s : String) : Prop :=
  s = "-" ∨ s = ""

def Decimal.IsWf.Natural (s : String) : Prop :=
  IsDigits s

def Decimal.IsWf.Fraction (s : String) : Prop :=
  IsDigitsBetween 1 4 s

def Decimal.IsWf.Decimal (s : String) : Prop :=
  ∃ «sign» natural fraction,
    ((s = «sign» ++ natural ++ "." ++ fraction ∧ Decimal.IsWf.Sign «sign») ∧ Decimal.IsWf.Natural natural) ∧
      Decimal.IsWf.Fraction fraction

def Decimal.value («sign» : String) (natural : String) (fraction : String) : Int :=
  signOf «sign» *
    (natOf natural * (10 : Int) ^ ((4 : Int)).toNat +
      natOf fraction * (10 : Int) ^ (((4 : Int) - lenOf fraction)).toNat)

def Decimal.Constraints («sign» : String) (natural : String) (fraction : String) : Prop :=
  (-9223372036854775808 : Int) ≤ Decimal.value «sign» natural fraction ∧
    Decimal.value «sign» natural fraction ≤ (9223372036854775807 : Int)

abbrev Decimal.SatisfiesWfConstraints (s : String) : Prop :=
  True

abbrev Decimal.IsWf (s : String) : Prop :=
  Decimal.IsWf.Decimal s ∧ Decimal.SatisfiesWfConstraints s

def Decimal.SatisfiesConstraints (s : String) : Prop :=
  Decimal.Constraints (Triptych.component Decimal.grammar s "Sign") (Triptych.component Decimal.grammar s "Natural")
    (Triptych.component Decimal.grammar s "Fraction")

abbrev Decimal.IsValid (s : String) : Prop :=
  Decimal.IsWf s ∧ Decimal.SatisfiesConstraints s

structure Decimal.View where
  input : String
  «sign» : String
  natural : String
  fraction : String

abbrev Decimal.View.WfConstraints (_ : Decimal.View) : Prop :=
  True

def Decimal.View.Constraints (v : Decimal.View) : Prop :=
  Decimal.Constraints (Decimal.View.sign v) (Decimal.View.natural v) (Decimal.View.fraction v)

abbrev Decimal.View.Valid (v : Decimal.View) : Prop :=
  Decimal.View.WfConstraints v ∧ Decimal.View.Constraints v

def Decimal.View.denotation (v : Decimal.View) :=
  Decimal.value (Decimal.View.sign v) (Decimal.View.natural v) (Decimal.View.fraction v)
