/- Generated by FormatSpec from `format_spec IPv4`. Do not edit by hand. -/

import FormatSpec.Denote
import FormatSpec.Value
import FormatSpec.Constraint
import FormatSpec.Assemble
import FormatSpec.Reconcile

open FormatSpec

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ═══════════════════════════════ spec ═══════════════════════════════
The more readable specification. Each production of the input grammar becomes an
inlined well-formedness predicate `IsWf.*` written as a plain existential over the
named captures, so you can read it side-by-side with the grammar and check that it
says the same thing. `value` is the value function, `Constraints` the extra
conditions, and `IsValid` the overall acceptance predicate (well-formed ∧
constraints). This file is proof-free — it is what you cite. -/

def IPv4.grammar : Grammar :=
  Grammar.mk "V4Addr"
    [Production.mk "V4Addr"
        [[SymItem.mk (Sym.ref "Oct1") false, SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "Oct2") false,
            SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "Oct3") false, SymItem.mk (Sym.lit ".") false,
            SymItem.mk (Sym.ref "Oct4") false]],
      Production.mk "Oct1" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.between 1 3)) false]],
      Production.mk "Oct2" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.between 1 3)) false]],
      Production.mk "Oct3" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.between 1 3)) false]],
      Production.mk "Oct4" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.between 1 3)) false]]]

def IPv4.IsWf.Oct1 (s : String) : Prop :=
  IsDigitsBetween 1 3 s

def IPv4.IsWf.Oct2 (s : String) : Prop :=
  IsDigitsBetween 1 3 s

def IPv4.IsWf.Oct3 (s : String) : Prop :=
  IsDigitsBetween 1 3 s

def IPv4.IsWf.Oct4 (s : String) : Prop :=
  IsDigitsBetween 1 3 s

def IPv4.IsWf.V4Addr (s : String) : Prop :=
  ∃ oct1 oct2 oct3 oct4,
    (((s = oct1 ++ "." ++ oct2 ++ "." ++ oct3 ++ "." ++ oct4 ∧ IPv4.IsWf.Oct1 oct1) ∧ IPv4.IsWf.Oct2 oct2) ∧
        IPv4.IsWf.Oct3 oct3) ∧
      IPv4.IsWf.Oct4 oct4

def IPv4.Constraints (oct1 : String) (oct2 : String) (oct3 : String) (oct4 : String) : Prop :=
  ((((((((oct1).startsWith "0" → oct1 = "0") ∧ (0 : Int) ≤ natOf oct1 ∧ natOf oct1 ≤ (255 : Int)) ∧
              ((oct2).startsWith "0" → oct2 = "0")) ∧
            (0 : Int) ≤ natOf oct2 ∧ natOf oct2 ≤ (255 : Int)) ∧
          ((oct3).startsWith "0" → oct3 = "0")) ∧
        (0 : Int) ≤ natOf oct3 ∧ natOf oct3 ≤ (255 : Int)) ∧
      ((oct4).startsWith "0" → oct4 = "0")) ∧
    (0 : Int) ≤ natOf oct4 ∧ natOf oct4 ≤ (255 : Int)

def IPv4.SatisfiesConstraints (s : String) : Prop :=
  IPv4.Constraints (FormatSpec.component IPv4.grammar s "Oct1") (FormatSpec.component IPv4.grammar s "Oct2")
    (FormatSpec.component IPv4.grammar s "Oct3") (FormatSpec.component IPv4.grammar s "Oct4")

abbrev IPv4.IsValid (s : String) : Prop :=
  IPv4.IsWf.V4Addr s ∧ IPv4.SatisfiesConstraints s
