/- Generated by Triptych from `triptych Datetime`. -/

import Triptych.Architecture.Denote
import Triptych.Architecture.Value
import Triptych.Architecture.Constraint
import Triptych.Architecture.Assemble
import Triptych.Theorems.Reconcile
import Triptych.Theorems.DecodeLemmas
import Datetime.spec
import Datetime.grammar

open Triptych
open CedarExamples.Datetime

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ══════════════════════════════ engine ══════════════════════════════
The executable counterpart of the spec. `decode` walks the grammar over an input
string and returns its captured components; `computeValue` then evaluates the value
function on those captures, and `isWf`/`isValid` decide well-formedness/acceptance.
`decodeView` packages the exact input and value/constraint captures as a typed `View`.

Naming convention: CAPITALIZED `IsWf.*`/`IsValid` are the surface `Prop`s you READ
and reason about; lowercase `isWf`/`isValid` are the engine's executable deciders you
RUN (`#eval isValid s`, `#eval computeValue s`). The `equivalence` section below
proves the two describe the same language and value. -/

def Datetime.valueFn := fun m : Triptych.CaptureMap =>
  epochMillis ((Triptych.CaptureMap.toEnv m "YYYY").getD "") ((Triptych.CaptureMap.toEnv m "MM").getD "")
    ((Triptych.CaptureMap.toEnv m "DD").getD "") ((Triptych.CaptureMap.toEnv m "Time.hh").getD "")
    ((Triptych.CaptureMap.toEnv m "Time.mm").getD "") ((Triptych.CaptureMap.toEnv m "ss").getD "")
    ((Triptych.CaptureMap.toEnv m "SSS").getD "") ((Triptych.CaptureMap.toEnv m "Offset.hh").getD "")
    ((Triptych.CaptureMap.toEnv m "Offset.mm").getD "") ((Triptych.CaptureMap.toEnv m "Offset").getD "")

def Datetime.constraints : List ConstraintEntry :=
  [ConstraintEntry.dsl ConstraintPhase.wellFormed
      (Constraint.and (Constraint.le (ValExpr.lit 1) (ValExpr.nat "MM"))
        (Constraint.le (ValExpr.nat "MM") (ValExpr.lit 12))),
    ConstraintEntry.dsl ConstraintPhase.wellFormed
      (Constraint.and (Constraint.le (ValExpr.lit 0) (ValExpr.nat "Time.hh"))
        (Constraint.le (ValExpr.nat "Time.hh") (ValExpr.lit 23))),
    ConstraintEntry.dsl ConstraintPhase.wellFormed
      (Constraint.and (Constraint.le (ValExpr.lit 0) (ValExpr.nat "Time.mm"))
        (Constraint.le (ValExpr.nat "Time.mm") (ValExpr.lit 59))),
    ConstraintEntry.dsl ConstraintPhase.wellFormed
      (Constraint.and (Constraint.le (ValExpr.lit 0) (ValExpr.nat "ss"))
        (Constraint.le (ValExpr.nat "ss") (ValExpr.lit 59))),
    ConstraintEntry.dsl ConstraintPhase.wellFormed
      (Constraint.and (Constraint.le (ValExpr.lit 0) (ValExpr.nat "Offset.hh"))
        (Constraint.le (ValExpr.nat "Offset.hh") (ValExpr.lit 23))),
    ConstraintEntry.dsl ConstraintPhase.wellFormed
      (Constraint.and (Constraint.le (ValExpr.lit 0) (ValExpr.nat "Offset.mm"))
        (Constraint.le (ValExpr.nat "Offset.mm") (ValExpr.lit 59))),
    ConstraintEntry.opaque ConstraintPhase.wellFormed fun env : Env =>
      dayBound (((env : Env) "YYYY").getD "") (((env : Env) "MM").getD "") (((env : Env) "DD").getD "")]

abbrev Datetime.isWf (s : String) : Prop :=
  Triptych.isWf Datetime.grammar Datetime.constraints s

abbrev Datetime.satisfiesConstraints (s : String) : Prop :=
  Triptych.satisfiesConstraints Datetime.grammar Datetime.constraints s

abbrev Datetime.isValid (s : String) : Prop :=
  Datetime.isWf s ∧ Datetime.satisfiesConstraints s

def Datetime.computeValue (s : String) :=
  Triptych.computeValueMap Datetime.grammar Datetime.valueFn s

def Datetime.View.ofMap (input : String) (m : Triptych.CaptureMap) : Datetime.View :=
  Datetime.View.mk input ((Triptych.CaptureMap.toEnv m "YYYY").getD "") ((Triptych.CaptureMap.toEnv m "MM").getD "")
    ((Triptych.CaptureMap.toEnv m "DD").getD "") (Triptych.CaptureMap.toEnv m "Time.hh")
    (Triptych.CaptureMap.toEnv m "Time.mm") (Triptych.CaptureMap.toEnv m "ss") (Triptych.CaptureMap.toEnv m "SSS")
    (Triptych.CaptureMap.toEnv m "Offset.hh") (Triptych.CaptureMap.toEnv m "Offset.mm")
    (Triptych.CaptureMap.toEnv m "Offset")

def Datetime.decodeView (s : String) : Option Datetime.View :=
  (decode Datetime.grammar s).map (Datetime.View.ofMap s)

/- ════════════════════════════ equivalence ════════════════════════════
The auto-discharged guarantees relating the readable surface to the executable
engine: `IsWfGrammar_equiv` proves grammar-layout agreement and `IsWf_equiv`
proves full well-formedness agreement. `computeValue_eq` proves the values agree,
while `decodeView_input`, `IsValid_view`, and `computeValue_view` expose the typed
parse view. Derived `DecidablePred` instances make the surface predicates executable
via the engine. No `sorry`. -/

theorem Datetime.decodeView_input {s : String} {v : Datetime.View} (h : Datetime.decodeView s = some v) :
    Datetime.View.input v = s := by
  unfold Datetime.decodeView at h
  rw [Option.map_eq_some_iff] at h
  obtain ⟨m, _, hv⟩ := h
  subst v
  rfl

theorem Datetime.SatisfiesWfConstraints_of_decode {s : String} {m : Triptych.CaptureMap}
    (h : decode Datetime.grammar s = some m) :
    Datetime.SatisfiesWfConstraints s ↔
      Datetime.WfConstraints ((Triptych.CaptureMap.toEnv m "MM").getD "")
        ((Triptych.CaptureMap.toEnv m "Time.hh").getD "") ((Triptych.CaptureMap.toEnv m "Time.mm").getD "")
        ((Triptych.CaptureMap.toEnv m "ss").getD "") ((Triptych.CaptureMap.toEnv m "Offset.hh").getD "")
        ((Triptych.CaptureMap.toEnv m "Offset.mm").getD "") ((Triptych.CaptureMap.toEnv m "YYYY").getD "")
        ((Triptych.CaptureMap.toEnv m "DD").getD "") :=
  by
  unfold Datetime.SatisfiesWfConstraints
  simp only [Triptych.component_eq_of_decode h "MM", Triptych.component_eq_of_decode h "Time.hh",
    Triptych.component_eq_of_decode h "Time.mm", Triptych.component_eq_of_decode h "ss",
    Triptych.component_eq_of_decode h "Offset.hh", Triptych.component_eq_of_decode h "Offset.mm",
    Triptych.component_eq_of_decode h "YYYY", Triptych.component_eq_of_decode h "DD"]

theorem Datetime.Internal.matchesRef.YYYY (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "YYYY") s ↔ Datetime.IsWf.YYYY s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "YYYY" =
        some (Production.mk "YYYY" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 4)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.YYYY
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.MM (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "MM") s ↔ Datetime.IsWf.MM s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "MM" =
        some (Production.mk "MM" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.MM
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.DD (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "DD") s ↔ Datetime.IsWf.DD s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "DD" =
        some (Production.mk "DD" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.DD
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.Date (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 2) (Sym.ref "Date") s ↔ Datetime.IsWf.Date s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "Date" =
        some
          (Production.mk "Date"
            [[SymItem.mk (Sym.ref "YYYY") false, SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "MM") false,
                SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "DD") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.Date
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym,
    Datetime.Internal.matchesRef.YYYY, Datetime.Internal.matchesRef.MM, Datetime.Internal.matchesRef.DD]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.hh (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "hh") s ↔ Datetime.IsWf.hh s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "hh" =
        some (Production.mk "hh" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.hh
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.mm (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "mm") s ↔ Datetime.IsWf.mm s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "mm" =
        some (Production.mk "mm" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.mm
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.ss (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "ss") s ↔ Datetime.IsWf.ss s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "ss" =
        some (Production.mk "ss" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.ss
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.Time (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 2) (Sym.ref "Time") s ↔ Datetime.IsWf.Time s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "Time" =
        some
          (Production.mk "Time"
            [[SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "mm") false,
                SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "ss") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.Time
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym,
    Datetime.Internal.matchesRef.hh, Datetime.Internal.matchesRef.mm, Datetime.Internal.matchesRef.ss]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.SSS (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "SSS") s ↔ Datetime.IsWf.SSS s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "SSS" =
        some (Production.mk "SSS" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 3)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.SSS
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.Offset (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 2) (Sym.ref "Offset") s ↔ Datetime.IsWf.Offset s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "Offset" =
        some
          (Production.mk "Offset"
            [[SymItem.mk (Sym.lit "+") false, SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.ref "mm") false],
              [SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.ref "mm") false]])
      from rfl]
  dsimp only
  unfold matchesProd Datetime.IsWf.Offset
  simp (config := { maxSteps := 1000000 }) only [List.mem_cons, List.mem_singleton, List.not_mem_nil,
    Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_or_imp, exists_eq_left, exists_eq_left, if_true,
    if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, Datetime.Internal.matchesRef.hh,
    Datetime.Internal.matchesRef.mm]
  repeat'
    first
    | apply or_congr
    | ( simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left,
          ← and_assoc, exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
        try grind [String.append_assoc, String.append_empty])

theorem Datetime.Internal.matchesRef.Datetime (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 3) (Sym.ref "Datetime") s ↔ Datetime.IsWf.Datetime s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "Datetime" =
        some
          (Production.mk "Datetime"
            [[SymItem.mk (Sym.ref "Date") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.ref "Offset") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false]])
      from rfl]
  dsimp only
  unfold matchesProd Datetime.IsWf.Datetime
  simp (config := { maxSteps := 1000000 }) only [List.mem_cons, List.mem_singleton, List.not_mem_nil,
    Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_or_imp, exists_eq_left, exists_eq_left, if_true,
    if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, Datetime.Internal.matchesRef.Date,
    Datetime.Internal.matchesRef.Time, Datetime.Internal.matchesRef.SSS, Datetime.Internal.matchesRef.Offset]
  repeat'
    first
    | apply or_congr
    | ( simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left,
          ← and_assoc, exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
        try grind [String.append_assoc, String.append_empty])

theorem Datetime.IsWfGrammar_equiv (s : String) : Triptych.IsWf Datetime.grammar s ↔ Datetime.IsWf.Datetime s :=
  by
  rw [isWf_eq_isWfProd_start, IsWfProd,
    show
      (Datetime.grammar).prod? (Datetime.grammar).start =
        some
          (Production.mk "Datetime"
            [[SymItem.mk (Sym.ref "Date") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.ref "Offset") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false]])
      from rfl]
  have hstart :
    ∀ n,
      matchesProd Datetime.grammar n
          (Production.mk "Datetime"
            [[SymItem.mk (Sym.ref "Date") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.ref "Offset") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false]])
          s =
        matchesSym Datetime.grammar (n + 1) (Sym.ref "Datetime") s :=
    by
    intro n
    rw [matchesSym,
      show
        (Datetime.grammar).prod? "Datetime" =
          some
            (Production.mk "Datetime"
              [[SymItem.mk (Sym.ref "Date") false],
                [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                  SymItem.mk (Sym.lit "Z") false],
                [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                  SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
                [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                  SymItem.mk (Sym.ref "Offset") false],
                [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                  SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false,
                  SymItem.mk (Sym.ref "Offset") false]])
        from rfl]
  show
    matchesProd Datetime.grammar (Datetime.grammar).prods.length
        (Production.mk "Datetime"
          [[SymItem.mk (Sym.ref "Date") false],
            [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
              SymItem.mk (Sym.lit "Z") false],
            [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
              SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
            [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
              SymItem.mk (Sym.ref "Offset") false],
            [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
              SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false]])
        s ↔
      _
  rw [hstart]
  exact Datetime.Internal.matchesRef.Datetime _ s

theorem Datetime.IsWf_equiv (s : String) : Datetime.IsWf s ↔ Datetime.isWf s :=
  by
  unfold Datetime.IsWf Datetime.isWf Triptych.isWf
  rw [← Datetime.IsWfGrammar_equiv, ← decodeSome_iff_IsWf Datetime.grammar (by decide)]
  unfold Datetime.SatisfiesWfConstraints Datetime.WfConstraints Datetime.constraints
  simp only [Triptych.component, List.forall_mem_cons, List.forall_mem_singleton, List.not_mem_nil, forall_const,
    ConstraintEntry.wfPart, Constraint.eval, ValExpr.eval, presentCount, natOf_getD, intOf_getD, lenOf_getD,
    countOf_getD, signOf_getD, Env.countVal, and_true, true_and, false_implies, implies_true, Bool.false_eq_true]
  try grind

theorem Datetime.IsValid_equiv (s : String) : Datetime.IsValid s ↔ Datetime.isValid s :=
  by
  unfold Datetime.IsValid Datetime.isValid
  rw [(Datetime.IsWf_equiv s)]
  unfold Datetime.satisfiesConstraints Triptych.satisfiesConstraints Datetime.constraints
  simp only [List.forall_mem_cons, List.forall_mem_singleton, List.not_mem_nil, ConstraintEntry.valPart, false_implies,
    true_and, and_true]
  constructor
  · intro h
    exact ⟨h, fun _ => True.intro⟩
  · exact And.left

instance Datetime.instDecidableGrammar : DecidablePred Datetime.IsWf.Datetime := fun s =>
  @decidable_of_iff _ _ (Datetime.IsWfGrammar_equiv s) (Triptych.decIsWf Datetime.grammar (by decide) s)

instance Datetime.instDecidableIsWf : DecidablePred Datetime.IsWf := fun s =>
  @decidable_of_iff _ _ (Datetime.IsWf_equiv s).symm inferInstance

instance Datetime.instDecidableIsValid : DecidablePred Datetime.IsValid := fun s => inferInstance

theorem Datetime.View.wfConstraints_of_decode {s : String} {m : Triptych.CaptureMap}
    (h : decode Datetime.grammar s = some m) :
    Datetime.SatisfiesWfConstraints s ↔ Datetime.View.WfConstraints (Datetime.View.ofMap s m) :=
  by
  rw [Datetime.SatisfiesWfConstraints_of_decode h]
  rfl

theorem Datetime.IsValid_view (s : String) :
    Datetime.IsValid s ↔ ∃ v : Datetime.View, Datetime.decodeView s = some v ∧ Datetime.View.Valid v :=
  by
  constructor
  · intro hvalid
    have hengine : Datetime.isValid s := (Datetime.IsValid_equiv s).mp hvalid
    have hsome : (decode Datetime.grammar s).isSome = true := by exact hengine.1.1
    obtain ⟨m, hm⟩ := Option.isSome_iff_exists.mp hsome
    refine ⟨Datetime.View.ofMap s m, ?_, ?_⟩
    · unfold Datetime.decodeView
      simp [hm]
    · exact (Datetime.View.wfConstraints_of_decode hm).mp hvalid.2
  · rintro ⟨v, hview, hvalid⟩
    unfold Datetime.decodeView at hview
    rw [Option.map_eq_some_iff] at hview
    obtain ⟨m, hm, hv⟩ := hview
    subst v
    have hdecoded : (decode Datetime.grammar s).isSome = true := by simp [hm]
    have hgrammar :=
      (Datetime.IsWfGrammar_equiv s).mp ((decodeSome_iff_IsWf Datetime.grammar (by decide) s).mp hdecoded)
    exact ⟨hgrammar, (Datetime.View.wfConstraints_of_decode hm).mpr hvalid⟩

theorem Datetime.computeValue_eq (s : String) :
    Datetime.computeValue s =
      (decode Datetime.grammar s).map
        (fun _ =>
          Datetime.value (Triptych.component Datetime.grammar s "YYYY") (Triptych.component Datetime.grammar s "MM")
            (Triptych.component Datetime.grammar s "DD") (Triptych.component Datetime.grammar s "Time.hh")
            (Triptych.component Datetime.grammar s "Time.mm") (Triptych.component Datetime.grammar s "ss")
            (Triptych.component Datetime.grammar s "SSS") (Triptych.component Datetime.grammar s "Offset.hh")
            (Triptych.component Datetime.grammar s "Offset.mm") (Triptych.component Datetime.grammar s "Offset")) :=
  by
  unfold Datetime.computeValue Triptych.computeValueMap Triptych.component Triptych.envOf Datetime.value
    Datetime.valueFn
  cases h : decode Datetime.grammar s with
  | none => simp
  | some m =>
    simp only [Option.map_some, natOf_getD, intOf_getD, lenOf_getD, countOf_getD, signOf_getD, Env.countVal,
      ValExpr.eval]

theorem Datetime.computeValue_of_decode {s : String} {m : Triptych.CaptureMap}
    (h : decode Datetime.grammar s = some m) :
    Datetime.computeValue s =
      some
        (Datetime.value ((Triptych.CaptureMap.toEnv m "YYYY").getD "") ((Triptych.CaptureMap.toEnv m "MM").getD "")
          ((Triptych.CaptureMap.toEnv m "DD").getD "") ((Triptych.CaptureMap.toEnv m "Time.hh").getD "")
          ((Triptych.CaptureMap.toEnv m "Time.mm").getD "") ((Triptych.CaptureMap.toEnv m "ss").getD "")
          ((Triptych.CaptureMap.toEnv m "SSS").getD "") ((Triptych.CaptureMap.toEnv m "Offset.hh").getD "")
          ((Triptych.CaptureMap.toEnv m "Offset.mm").getD "") ((Triptych.CaptureMap.toEnv m "Offset").getD "")) :=
  by
  rw [Datetime.computeValue_eq, h]
  simp only [Option.map_some, Triptych.component_eq_of_decode h "YYYY", Triptych.component_eq_of_decode h "MM",
    Triptych.component_eq_of_decode h "DD", Triptych.component_eq_of_decode h "Time.hh",
    Triptych.component_eq_of_decode h "Time.mm", Triptych.component_eq_of_decode h "ss",
    Triptych.component_eq_of_decode h "SSS", Triptych.component_eq_of_decode h "Offset.hh",
    Triptych.component_eq_of_decode h "Offset.mm", Triptych.component_eq_of_decode h "Offset"]

theorem Datetime.computeValue_view (s : String) :
    Datetime.computeValue s = (Datetime.decodeView s).map Datetime.View.denotation :=
  by
  unfold Datetime.decodeView
  cases h : decode Datetime.grammar s with
  |
    none =>
    rw [show Datetime.computeValue s = none by
        rw [Datetime.computeValue_eq, h]
        rfl]
    rfl
  | some m =>
    rw [Datetime.computeValue_of_decode h]
    simp only [Option.map_some]
    rfl

/- ═══════════════════════════════ parser ══════════════════════════════
The generated correct-by-construction parser `parse` (= `computeValue` gated on the
decidable `isValid`) together with its guarantees — `parse_sound`, `parse_complete`,
`parse_reject`, `parse_view`, and typed `parse_eq_some_iff_view` /
`parse_eq_none_iff_view` normal forms — all AUTO-DISCHARGED here.
When an external parser is declared, `checkedExtParse` additionally validates each
external result against this parser and ships an AUTO-DISCHARGED soundness theorem.
A verified parser, no `sorry`. -/

theorem Datetime.computeValue_isSome (s : String) : Datetime.isValid s → (Datetime.computeValue s).isSome :=
  by
  intro h
  unfold Datetime.isValid Datetime.isWf Triptych.isWf at h
  unfold Datetime.computeValue Triptych.computeValueMap
  rw [Option.isSome_map]
  exact h.1.1

def Datetime.parse (s : String) :=
  Triptych.gatedParse Datetime.isValid Datetime.computeValue s

theorem Datetime.parse_sound (s : String) (i : Int) :
    Datetime.parse s = some i → Datetime.isValid s ∧ Datetime.computeValue s = some i :=
  Triptych.gatedParse_sound _ _ s i

theorem Datetime.parse_complete (s : String) (i : Int) :
    Datetime.isValid s → Datetime.computeValue s = some i → Datetime.parse s = some i :=
  Triptych.gatedParse_complete _ _ s i

theorem Datetime.parse_reject (s : String) : Datetime.parse s = none ↔ ¬Datetime.isValid s :=
  Triptych.gatedParse_reject _ _ Datetime.computeValue_isSome s

theorem Datetime.parse_view (s : String) :
    Datetime.parse s =
      if decide (Datetime.isValid s) then (Datetime.decodeView s).map Datetime.View.denotation else none :=
  by
  unfold Datetime.parse Triptych.gatedParse
  rw [Datetime.computeValue_view]

theorem Datetime.parse_eq_some_iff_view (s : String) (i : Int) :
    Datetime.parse s = some i ↔
      ∃ v : Datetime.View, Datetime.decodeView s = some v ∧ Datetime.View.Valid v ∧ Datetime.View.denotation v = i :=
  by
  constructor
  · intro hparse
    obtain ⟨hvalidEngine, hvalue⟩ := Datetime.parse_sound s i hparse
    have hvalidSurface := (Datetime.IsValid_equiv s).mpr hvalidEngine
    obtain ⟨v, hview, hvalidView⟩ := (Datetime.IsValid_view s).mp hvalidSurface
    refine ⟨v, hview, hvalidView, ?_⟩
    rw [Datetime.computeValue_view, hview] at hvalue
    exact Option.some.inj hvalue
  · rintro ⟨v, hview, hvalidView, hvalue⟩
    apply Datetime.parse_complete s i
    · exact (Datetime.IsValid_equiv s).mp ((Datetime.IsValid_view s).mpr ⟨v, hview, hvalidView⟩)
    · rw [Datetime.computeValue_view, hview]
      exact congrArg some hvalue

theorem Datetime.parse_eq_none_iff_view (s : String) :
    Datetime.parse s = none ↔ ¬∃ v : Datetime.View, Datetime.decodeView s = some v ∧ Datetime.View.Valid v :=
  by
  rw [Datetime.parse_reject]
  constructor
  · intro hinvalid ⟨v, hview, hvalidView⟩
    exact hinvalid ((Datetime.IsValid_equiv s).mp ((Datetime.IsValid_view s).mpr ⟨v, hview, hvalidView⟩))
  · intro hnoview hvalidEngine
    have hvalidSurface := (Datetime.IsValid_equiv s).mpr hvalidEngine
    exact hnoview ((Datetime.IsValid_view s).mp hvalidSurface)

def Datetime.checkedExtParse (s : String) : Option Cedar.Spec.Ext.Datetime :=
  Triptych.checkedExternalParse Datetime.IsValid Datetime.computeValue Cedar.Spec.Ext.Datetime.parse datetimeMillis s

theorem Datetime.checkedExtParse_eq_some_iff (s : String) (d : Cedar.Spec.Ext.Datetime) :
    Datetime.checkedExtParse s = some d ↔
      Cedar.Spec.Ext.Datetime.parse s = some d ∧
        Datetime.IsValid s ∧ Datetime.computeValue s = some (datetimeMillis d) :=
  Triptych.checkedExternalParse_eq_some_iff Datetime.IsValid Datetime.computeValue Cedar.Spec.Ext.Datetime.parse
    datetimeMillis s d

theorem Datetime.checkedExtParse_sound (s : String) (d : Cedar.Spec.Ext.Datetime) :
    Datetime.checkedExtParse s = some d → Datetime.IsValid s ∧ Datetime.computeValue s = some (datetimeMillis d) :=
  Triptych.checkedExternalParse_sound Datetime.IsValid Datetime.computeValue Cedar.Spec.Ext.Datetime.parse
    datetimeMillis s d

theorem Datetime.checkedExtParse_sound_view (s : String) (d : Cedar.Spec.Ext.Datetime) :
    Datetime.checkedExtParse s = some d →
      ∃ v : Datetime.View,
        Datetime.decodeView s = some v ∧ Datetime.View.Valid v ∧ Datetime.View.denotation v = datetimeMillis d :=
  by
  intro hparse
  obtain ⟨hvalid, hvalue⟩ := Datetime.checkedExtParse_sound s d hparse
  obtain ⟨v, hview, hvalidView⟩ := (Datetime.IsValid_view s).mp hvalid
  refine ⟨v, hview, hvalidView, ?_⟩
  rw [Datetime.computeValue_view, hview] at hvalue
  exact Option.some.inj hvalue
