-- Generated by FormatSpec from `format_spec Graph`. Do not edit by hand.

import FormatSpec.Denote
import FormatSpec.Value
import FormatSpec.Constraint
import FormatSpec.Assemble
import FormatSpec.Reconcile
import FormatSpec.Examples.Graph.spec
import FormatSpec.Examples.Graph.grammar

open FormatSpec
open FormatSpec.Examples.Graph

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

-- ══════════════════════════════ engine ══════════════════════════════
-- The analyzable/executable machinery behind the spec: the deep-embedded
-- value/constraint ASTs and the decode-backed interpreter bundle (`isWf`,
-- `isValid`, `computeValue`).

def Graph.valueFn := fun env : Env => toGraph (((env : Env) "Cells").getD "")

def Graph.constraints : List ConstraintEntry :=
  [ConstraintEntry.opaque fun env : Env => isTriangular (((env : Env) "Cells").getD "")]

abbrev Graph.isWf (s : String) : Prop :=
  FormatSpec.isWf Graph.grammar Graph.constraints s

abbrev Graph.satisfiesConstraints (s : String) : Prop :=
  FormatSpec.satisfiesConstraints Graph.grammar Graph.constraints s

abbrev Graph.isValid (s : String) : Prop :=
  Graph.isWf s ∧ Graph.satisfiesConstraints s

def Graph.computeValue (s : String) :=
  FormatSpec.computeValueF Graph.grammar Graph.valueFn s

-- ════════════════════════════ soundness ════════════════════════════
-- The auto-discharged guarantees tying surface to engine: `IsWf_equiv` (+ its
-- `Internal.matchesRef.*` lemmas), `computeValue_eq`, and the derived
-- `DecidablePred` instances (an executable validator, via the interpreter).

theorem Graph.Internal.matchesRef.Cells (fuel : Nat) (s : String) :
    matchesSym Graph.grammar (fuel + 1) (Sym.ref "Cells") s ↔ Graph.IsWf.Cells s :=
  by
  rw [matchesSym,
    show
      (Graph.grammar).prod? "Cells" =
        some (Production.mk "Cells" [[SymItem.mk (Sym.term TokClass.bit LenSpec.atLeastOne) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Graph.IsWf.Cells
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym, IsBits_matchesTerm,
    IsFixedBits_matchesTerm, IsBitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Graph.Internal.matchesRef.Adj (fuel : Nat) (s : String) :
    matchesSym Graph.grammar (fuel + 2) (Sym.ref "Adj") s ↔ Graph.IsWf.Adj s :=
  by
  rw [matchesSym,
    show (Graph.grammar).prod? "Adj" = some (Production.mk "Adj" [[SymItem.mk (Sym.ref "Cells") false]]) from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Graph.IsWf.Adj
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym,
    Graph.Internal.matchesRef.Cells]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Graph.IsWf_equiv (s : String) : IsWf Graph.grammar s ↔ Graph.IsWf.Adj s :=
  by
  rw [isWf_eq_isWfProd_start, IsWfProd,
    show (Graph.grammar).prod? (Graph.grammar).start = some (Production.mk "Adj" [[SymItem.mk (Sym.ref "Cells") false]])
      from rfl]
  have hstart :
    ∀ n,
      matchesProd Graph.grammar n (Production.mk "Adj" [[SymItem.mk (Sym.ref "Cells") false]]) s =
        matchesSym Graph.grammar (n + 1) (Sym.ref "Adj") s :=
    by
    intro n
    rw [matchesSym,
      show (Graph.grammar).prod? "Adj" = some (Production.mk "Adj" [[SymItem.mk (Sym.ref "Cells") false]]) from rfl]
  show
    matchesProd Graph.grammar (Graph.grammar).prods.length (Production.mk "Adj" [[SymItem.mk (Sym.ref "Cells") false]])
        s ↔
      _
  rw [hstart]
  exact Graph.Internal.matchesRef.Adj _ s

instance Graph.instDecidableIsWf : DecidablePred Graph.IsWf.Adj := fun s =>
  @decidable_of_iff _ _ (Graph.IsWf_equiv s) (FormatSpec.decIsWf Graph.grammar (by decide) s)

instance Graph.instDecidableSatisfiesConstraints : DecidablePred Graph.SatisfiesConstraints := fun s => by
  simp only [Graph.SatisfiesConstraints, Graph.Constraints]; exact inferInstance

instance Graph.instDecidableIsValid : DecidablePred Graph.IsValid := fun s => inferInstanceAs (Decidable (_ ∧ _))

theorem Graph.IsValid_equiv (s : String) : Graph.IsValid s ↔ Graph.isValid s :=
  by
  unfold Graph.IsValid Graph.isValid Graph.isWf Graph.satisfiesConstraints
  unfold FormatSpec.isWf FormatSpec.satisfiesConstraints
  rw [← Graph.IsWf_equiv, ← decodeSome_iff_IsWf Graph.grammar (by decide)]
  unfold Graph.SatisfiesConstraints Graph.Constraints Graph.constraints
  simp only [FormatSpec.component, List.forall_mem_cons, List.forall_mem_singleton, List.not_mem_nil, forall_const,
    if_true, if_false, ConstraintEntry.wfPart, ConstraintEntry.valPart, Constraint.wfPart, Constraint.valPart,
    Constraint.isValueDependent, Constraint.eval, ValExpr.eval, presentCount, natOf_getD, intOf_getD, lenOf_getD,
    signOf_getD, and_true, true_and, false_implies, implies_true, Bool.false_eq_true]
  try grind

theorem Graph.computeValue_eq (s : String) :
    Graph.computeValue s =
      (decode Graph.grammar s).map (fun _ => Graph.value (FormatSpec.component Graph.grammar s "Cells")) :=
  by
  unfold Graph.computeValue FormatSpec.computeValueF FormatSpec.component FormatSpec.envOf Graph.value Graph.valueFn
  cases h : decode Graph.grammar s with
  | none => simp
  | some m => simp only [Option.map_some, natOf_getD, intOf_getD, lenOf_getD, signOf_getD, ValExpr.eval]

-- ═══════════════════════════════ parser ══════════════════════════════
-- The generated correct-by-construction parser `parse` (= `computeValue` gated on
-- the decidable `isValid`) and its AUTO-DISCHARGED contracts `parse_sound` /
-- `parse_complete` / `parse_reject`. A verified parser, no `sorry`.

theorem Graph.computeValue_isSome (s : String) : Graph.isValid s → (Graph.computeValue s).isSome :=
  by
  intro h
  unfold Graph.isValid Graph.isWf FormatSpec.isWf at h
  unfold Graph.computeValue FormatSpec.computeValueF
  rw [Option.isSome_map]
  exact h.1.1

def Graph.parse (s : String) :=
  FormatSpec.gatedParse Graph.isValid Graph.computeValue s

theorem Graph.parse_sound : SoundStmt Graph.isValid Graph.computeValue Graph.parse id :=
  FormatSpec.gatedParse_sound _ _

theorem Graph.parse_complete : CompleteStmt Graph.isValid Graph.computeValue Graph.parse id :=
  FormatSpec.gatedParse_complete _ _

theorem Graph.parse_reject : RejectStmt Graph.isValid Graph.parse :=
  FormatSpec.gatedParse_reject _ _ Graph.computeValue_isSome
