-- Generated by FormatSpec from `format_spec Graph`. Do not edit by hand.

import FormatSpec.Denote
import FormatSpec.Value
import FormatSpec.Constraint
import FormatSpec.Assemble
import FormatSpec.Reconcile
import FormatSpec.Examples.Graph.grammar

open FormatSpec
open FormatSpec.Examples.Graph

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

-- ═══════════════════════════════ spec ═══════════════════════════════
-- The reader-facing specification: the grammar, the readable per-production
-- well-formedness predicates `IsWf.*`, the `value` function, the `Constraints`,
-- and the acceptance predicates `SatisfiesConstraints` / `IsValid` (a string is
-- VALID iff it satisfies the grammar and constraints — Cedar's wording).

def Graph.grammar : Grammar :=
  Grammar.mk "Adj"
    [Production.mk "Adj" [[SymItem.mk (Sym.ref "Cells") false]],
      Production.mk "Cells" [[SymItem.mk (Sym.term TokClass.bit LenSpec.atLeastOne) false]]]

def Graph.IsWf.Cells (s : String) : Prop :=
  IsBits s

def Graph.IsWf.Adj (s : String) : Prop :=
  Graph.IsWf.Cells s

def Graph.value (cells : String) :=
  toGraph cells

def Graph.Constraints (cells : String) : Prop :=
  isTriangular cells = true

def Graph.SatisfiesConstraints (s : String) : Prop :=
  Graph.Constraints (FormatSpec.component Graph.grammar s "Cells")

abbrev Graph.IsValid (s : String) : Prop :=
  Graph.IsWf.Adj s ∧ Graph.SatisfiesConstraints s
