/- Generated by FormatSpec from `format_spec Graph`. -/

import FormatSpec.Denote
import FormatSpec.Value
import FormatSpec.Constraint
import FormatSpec.Assemble
import FormatSpec.Reconcile
import FormatSpec.Examples.Graph.grammar

open FormatSpec
open FormatSpec.Examples.Graph

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ═══════════════════════════════ spec ═══════════════════════════════
The more readable specification. Each production of the input grammar becomes an
inlined well-formedness predicate `IsWf.*` written as a plain existential over the
named captures, so you can read it side-by-side with the grammar and check that it
says the same thing. `value` is the value function, `Constraints` the extra
conditions, and `IsValid` the overall acceptance predicate (well-formed ∧
constraints). This file is proof-free — it is what you cite. -/

def Graph.grammar : Grammar :=
  Grammar.mk "Adj"
    [Production.mk "Adj" [[SymItem.mk (Sym.ref "Cells") false]],
      Production.mk "Cells" [[SymItem.mk (Sym.term TokClass.bit LenSpec.atLeastOne) false]]]

def Graph.IsWf.Cells (s : String) : Prop :=
  IsBits s

def Graph.IsWf.Adj (s : String) : Prop :=
  Graph.IsWf.Cells s

def Graph.value (cells : String) :=
  toGraph cells

def Graph.Constraints (cells : String) : Prop :=
  isTriangular cells = true

def Graph.SatisfiesConstraints (s : String) : Prop :=
  Graph.Constraints (FormatSpec.component Graph.grammar s "Cells")

abbrev Graph.IsValid (s : String) : Prop :=
  Graph.IsWf.Adj s ∧ Graph.SatisfiesConstraints s
