/- Generated by FormatSpec from `format_spec IPv6`. Do not edit by hand. -/

import FormatSpec.Denote
import FormatSpec.Value
import FormatSpec.Constraint
import FormatSpec.Assemble
import FormatSpec.Reconcile
import FormatSpec.Examples.IPv6.spec

open FormatSpec

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ══════════════════════════════ engine ══════════════════════════════
The executable engine, constructed by interpreting the input grammar's concrete
syntax tree: the deep-embedded value/constraint ASTs plus the interpreter bundle
(`isWf`, `isValid`, `computeValue`) built on top of the total capture-extracting
`decode`. Unlike the `Prop`-level surface, these actually run — `decode`/evaluate
a string and compute its captures, validity, and value. -/

def IPv6.constraints : List ConstraintEntry :=
  []

abbrev IPv6.isWf (s : String) : Prop :=
  FormatSpec.isWf IPv6.grammar IPv6.constraints s

abbrev IPv6.satisfiesConstraints (s : String) : Prop :=
  FormatSpec.satisfiesConstraints IPv6.grammar IPv6.constraints s

abbrev IPv6.isValid (s : String) : Prop :=
  IPv6.isWf s ∧ IPv6.satisfiesConstraints s

/- ════════════════════════════ equivalence ════════════════════════════
The auto-discharged guarantees relating the readable surface to the executable
engine: `IsWf_equiv` (+ its `Internal.matchesRef.*` lemmas) proves recognition
agrees, `computeValue_eq` proves the values agree, and the derived `DecidablePred`
instances make the surface predicates executable via the engine. No `sorry`. -/

theorem IPv6.Internal.matchesRef.H16 (fuel : Nat) (s : String) :
    matchesSym IPv6.grammar (fuel + 1) (Sym.ref "H16") s ↔ IPv6.IsWf.H16 s :=
  by
  rw [matchesSym,
    show
      (IPv6.grammar).prod? "H16" =
        some (Production.mk "H16" [[SymItem.mk (Sym.term TokClass.hexDigit (LenSpec.between 1 4)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold IPv6.IsWf.H16
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym,
    IsHexDigits_matchesTerm, IsFixedHexDigits_matchesTerm, IsHexDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem IPv6.Internal.matchesRef.V6Addr (fuel : Nat) (s : String) :
    matchesSym IPv6.grammar (fuel + 2) (Sym.ref "V6Addr") s ↔ IPv6.IsWf.V6Addr s :=
  by
  rw [matchesSym,
    show
      (IPv6.grammar).prod? "V6Addr" =
        some (Production.mk "V6Addr" [[SymItem.mk (Sym.rep ":" (Sym.ref "H16") 8 (some 8)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold IPv6.IsWf.V6Addr
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym,
    IPv6.Internal.matchesRef.H16]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem IPv6.IsWf_equiv (s : String) : IsWf IPv6.grammar s ↔ IPv6.IsWf.V6Addr s :=
  by
  rw [isWf_eq_isWfProd_start, IsWfProd,
    show
      (IPv6.grammar).prod? (IPv6.grammar).start =
        some (Production.mk "V6Addr" [[SymItem.mk (Sym.rep ":" (Sym.ref "H16") 8 (some 8)) false]])
      from rfl]
  have hstart :
    ∀ n,
      matchesProd IPv6.grammar n (Production.mk "V6Addr" [[SymItem.mk (Sym.rep ":" (Sym.ref "H16") 8 (some 8)) false]])
          s =
        matchesSym IPv6.grammar (n + 1) (Sym.ref "V6Addr") s :=
    by
    intro n
    rw [matchesSym,
      show
        (IPv6.grammar).prod? "V6Addr" =
          some (Production.mk "V6Addr" [[SymItem.mk (Sym.rep ":" (Sym.ref "H16") 8 (some 8)) false]])
        from rfl]
  show
    matchesProd IPv6.grammar (IPv6.grammar).prods.length
        (Production.mk "V6Addr" [[SymItem.mk (Sym.rep ":" (Sym.ref "H16") 8 (some 8)) false]]) s ↔
      _
  rw [hstart]
  exact IPv6.Internal.matchesRef.V6Addr _ s

instance IPv6.instDecidableIsWf : DecidablePred IPv6.IsWf.V6Addr := fun s =>
  @decidable_of_iff _ _ (IPv6.IsWf_equiv s) (FormatSpec.decIsWf IPv6.grammar (by decide) s)

instance IPv6.instDecidableIsValid : DecidablePred IPv6.IsValid := fun s => inferInstanceAs (Decidable (_ ∧ _))

theorem IPv6.IsValid_equiv (s : String) : IPv6.IsValid s ↔ IPv6.isValid s :=
  by
  unfold IPv6.IsValid IPv6.isValid IPv6.isWf IPv6.satisfiesConstraints
  unfold FormatSpec.isWf FormatSpec.satisfiesConstraints
  rw [← IPv6.IsWf_equiv, ← decodeSome_iff_IsWf IPv6.grammar (by decide)]
  unfold IPv6.SatisfiesConstraints IPv6.constraints
  simp only [FormatSpec.component, List.forall_mem_cons, List.forall_mem_singleton, List.not_mem_nil, forall_const,
    if_true, if_false, ConstraintEntry.wfPart, ConstraintEntry.valPart, Constraint.wfPart, Constraint.valPart,
    Constraint.isValueDependent, Constraint.eval, ValExpr.eval, presentCount, natOf_getD, intOf_getD, lenOf_getD,
    signOf_getD, and_true, true_and, false_implies, implies_true, Bool.false_eq_true]
  try grind
