-- Generated by FormatSpec from `format_spec IPv6`. Do not edit by hand.

import FormatSpec.Denote
import FormatSpec.Value
import FormatSpec.Constraint
import FormatSpec.Assemble
import FormatSpec.Reconcile

open FormatSpec

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

-- ═══════════════════════════════ spec ═══════════════════════════════
-- The reader-facing specification: the grammar, the readable per-production
-- well-formedness predicates `IsWf.*`, the `value` function, the `Constraints`,
-- and the acceptance predicates `SatisfiesConstraints` / `IsValid` (a string is
-- VALID iff it satisfies the grammar and constraints — Cedar's wording).

def IPv6.grammar : Grammar :=
  Grammar.mk "V6Addr"
    [Production.mk "V6Addr" [[SymItem.mk (Sym.rep ":" (Sym.ref "H16") 8 (some 8)) false]],
      Production.mk "H16" [[SymItem.mk (Sym.term TokClass.hexDigit (LenSpec.between 1 4)) false]]]

def IPv6.IsWf.H16 (s : String) : Prop :=
  IsHexDigitsBetween 1 4 s

def IPv6.IsWf.V6Addr (s : String) : Prop :=
  ∃ parts : List String,
    8 ≤ parts.length ∧ parts.length ≤ 8 ∧ (∀ p ∈ parts, IPv6.IsWf.H16 p) ∧ s = String.intercalate ":" parts

abbrev IPv6.SatisfiesConstraints (s : String) : Prop :=
  True

abbrev IPv6.IsValid (s : String) : Prop :=
  IPv6.IsWf.V6Addr s ∧ IPv6.SatisfiesConstraints s
