/- Generated by Triptych from `triptych IPv4`. -/

import IPv4.parser
import IPv4.grammar

open Triptych
open CedarExamples.IPv4

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ══════════════════════ soundness · generated parser ══════════════════════
Obligations about the GENERATED parser `parse`. The `encode_*` obligations (a
serialized value is accepted, and evaluates back to itself) are left as `sorry` — a
serializer is a choice, so its correctness is yours to prove; from them the printer
theorems (`parse_toString_roundtrip`/`toString_injective`/`normalize_eq_iff_parse_eq`)
are DISCHARGED here. These same `encode_*` obligations are reused by the external
section below. -/

theorem IPv4.encode_accepted (i : IPNet) : IPv4.isValid (ipNetToStr i) := by sorry

theorem IPv4.encode_value (i : IPNet) : IPv4.computeValue (ipNetToStr i) = some i := by sorry

theorem IPv4.parse_toString_roundtrip (i : IPNet) : IPv4.parse (ipNetToStr i) = some i :=
  Triptych.gatedParse_toString_roundtrip IPv4.isValid IPv4.computeValue IPv4.encode_accepted IPv4.encode_value i

theorem IPv4.toString_injective (i i' : IPNet) (h : ipNetToStr i = ipNetToStr i') : i = i' :=
  Triptych.toString_injective IPv4.parse_toString_roundtrip i i' h

theorem IPv4.normalize_eq_iff_parse_eq (s s' : String) :
    (IPv4.parse s).map ipNetToStr = (IPv4.parse s').map ipNetToStr ↔ IPv4.parse s = IPv4.parse s' :=
  Triptych.normalize_eq_iff_parse_eq IPv4.parse_toString_roundtrip s s'

/- ══════════════════════ soundness · external parser ══════════════════════
Obligations for validating YOUR OWN external parser against this specification:
`extparse_sound`, `extparse_complete`, and `extparse_reject`, stated over the readable
surface `IsValid`/`computeValue`. These are left as `sorry` — they are claims about
your parser, so you have to prove them yourself. Given them, the external printer
theorems (`extparse_toString_*`) are DISCHARGED, reusing the generated section's
`encode_*`. -/

theorem IPv4.extparse_reject (s : String) : ipv4Only s = none ↔ ¬IPv4.IsValid s := by sorry

theorem IPv4.extparse_sound (s : String) (i : IPNet) :
    ipv4Only s = some i → IPv4.IsValid s ∧ IPv4.computeValue s = some (id i) := by sorry

theorem IPv4.extparse_complete (s : String) (i : IPNet) :
    IPv4.IsValid s → IPv4.computeValue s = some (id i) → ipv4Only s = some i := by sorry

theorem IPv4.extparse_toString_roundtrip (i : IPNet) : ipv4Only (ipNetToStr i) = some i :=
  Triptych.parse_toString_roundtrip IPv4.extparse_complete
    (fun d => (IPv4.IsValid_equiv (ipNetToStr d)).mpr (IPv4.encode_accepted d)) IPv4.encode_value i

theorem IPv4.extparse_toString_injective (i i' : IPNet) (h : ipNetToStr i = ipNetToStr i') : i = i' :=
  Triptych.toString_injective IPv4.extparse_toString_roundtrip i i' h

theorem IPv4.extparse_normalize_eq_iff_parse_eq (s s' : String) :
    (ipv4Only s).map ipNetToStr = (ipv4Only s').map ipNetToStr ↔ ipv4Only s = ipv4Only s' :=
  Triptych.normalize_eq_iff_parse_eq IPv4.extparse_toString_roundtrip s s'
