/- Generated by Triptych from `format_spec Duration`. -/

import Triptych.Architecture.Denote
import Triptych.Architecture.Value
import Triptych.Architecture.Constraint
import Triptych.Architecture.Assemble
import Triptych.Theorems.Reconcile

open Triptych

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ═══════════════════════════════ spec ═══════════════════════════════
The more readable specification. Each production of the input grammar becomes an
inlined well-formedness predicate `IsWf.*` written as a plain existential over the
named captures, so you can read it side-by-side with the grammar and check that it
says the same thing. `value` is the value function, `Constraints` the extra
conditions, and `IsValid` the overall acceptance predicate (well-formed ∧
constraints). This file is proof-free — it is what you cite. -/

def Duration.grammar : Grammar :=
  Grammar.mk "Duration"
    [Production.mk "Duration" [[SymItem.mk (Sym.ref "Sign") false, SymItem.mk (Sym.ref "Components") false]],
      Production.mk "Sign" [[SymItem.mk (Sym.lit "-") true]],
      Production.mk "Components"
        [[SymItem.mk (Sym.ref "Days") true, SymItem.mk (Sym.ref "Hours") true, SymItem.mk (Sym.ref "Minutes") true,
            SymItem.mk (Sym.ref "Seconds") true, SymItem.mk (Sym.ref "Millis") true]],
      Production.mk "Days" [[SymItem.mk (Sym.ref "DDays") false, SymItem.mk (Sym.lit "d") false]],
      Production.mk "Hours" [[SymItem.mk (Sym.ref "DHours") false, SymItem.mk (Sym.lit "h") false]],
      Production.mk "Minutes" [[SymItem.mk (Sym.ref "DMinutes") false, SymItem.mk (Sym.lit "m") false]],
      Production.mk "Seconds" [[SymItem.mk (Sym.ref "DSeconds") false, SymItem.mk (Sym.lit "s") false]],
      Production.mk "Millis" [[SymItem.mk (Sym.ref "DMillis") false, SymItem.mk (Sym.lit "ms") false]],
      Production.mk "DDays" [[SymItem.mk (Sym.term TokClass.digit LenSpec.atLeastOne) false]],
      Production.mk "DHours" [[SymItem.mk (Sym.term TokClass.digit LenSpec.atLeastOne) false]],
      Production.mk "DMinutes" [[SymItem.mk (Sym.term TokClass.digit LenSpec.atLeastOne) false]],
      Production.mk "DSeconds" [[SymItem.mk (Sym.term TokClass.digit LenSpec.atLeastOne) false]],
      Production.mk "DMillis" [[SymItem.mk (Sym.term TokClass.digit LenSpec.atLeastOne) false]]]

def Duration.IsWf.Sign (s : String) : Prop :=
  s = "-" ∨ s = ""

def Duration.IsWf.DDays (s : String) : Prop :=
  IsDigits s

def Duration.IsWf.Days (s : String) : Prop :=
  ∃ dDays, s = dDays ++ "d" ∧ Duration.IsWf.DDays dDays

def Duration.IsWf.DHours (s : String) : Prop :=
  IsDigits s

def Duration.IsWf.Hours (s : String) : Prop :=
  ∃ dHours, s = dHours ++ "h" ∧ Duration.IsWf.DHours dHours

def Duration.IsWf.DMinutes (s : String) : Prop :=
  IsDigits s

def Duration.IsWf.Minutes (s : String) : Prop :=
  ∃ dMinutes, s = dMinutes ++ "m" ∧ Duration.IsWf.DMinutes dMinutes

def Duration.IsWf.DSeconds (s : String) : Prop :=
  IsDigits s

def Duration.IsWf.Seconds (s : String) : Prop :=
  ∃ dSeconds, s = dSeconds ++ "s" ∧ Duration.IsWf.DSeconds dSeconds

def Duration.IsWf.DMillis (s : String) : Prop :=
  IsDigits s

def Duration.IsWf.Millis (s : String) : Prop :=
  ∃ dMillis, s = dMillis ++ "ms" ∧ Duration.IsWf.DMillis dMillis

def Duration.IsWf.Components (s : String) : Prop :=
  ∃ days hours minutes seconds millis,
    ((((s = days ++ hours ++ minutes ++ seconds ++ millis ∧ (days = "" ∨ Duration.IsWf.Days days)) ∧
            (hours = "" ∨ Duration.IsWf.Hours hours)) ∧
          (minutes = "" ∨ Duration.IsWf.Minutes minutes)) ∧
        (seconds = "" ∨ Duration.IsWf.Seconds seconds)) ∧
      (millis = "" ∨ Duration.IsWf.Millis millis)

def Duration.IsWf.Duration (s : String) : Prop :=
  ∃ «sign» components, (s = «sign» ++ components ∧ Duration.IsWf.Sign «sign») ∧ Duration.IsWf.Components components

def Duration.value («sign» : String) (dDays : String) (dHours : String) (dMinutes : String) (dSeconds : String)
    (dMillis : String) : Int :=
  signOf «sign» *
    (natOf dDays * (86400000 : Int) + natOf dHours * (3600000 : Int) + natOf dMinutes * (60000 : Int) +
        natOf dSeconds * (1000 : Int) +
      natOf dMillis)

def Duration.Constraints (components : String) («sign» : String) (dDays : String) (dHours : String) (dMinutes : String)
    (dSeconds : String) (dMillis : String) : Prop :=
  components ≠ "" ∧
    (-9223372036854775808 : Int) ≤ Duration.value «sign» dDays dHours dMinutes dSeconds dMillis ∧
      Duration.value «sign» dDays dHours dMinutes dSeconds dMillis ≤ (9223372036854775807 : Int)

def Duration.SatisfiesConstraints (s : String) : Prop :=
  Duration.Constraints (Triptych.component Duration.grammar s "Components")
    (Triptych.component Duration.grammar s "Sign") (Triptych.component Duration.grammar s "DDays")
    (Triptych.component Duration.grammar s "DHours") (Triptych.component Duration.grammar s "DMinutes")
    (Triptych.component Duration.grammar s "DSeconds") (Triptych.component Duration.grammar s "DMillis")

abbrev Duration.IsValid (s : String) : Prop :=
  Duration.IsWf.Duration s ∧ Duration.SatisfiesConstraints s
