/- Generated by Triptych from `triptych IPv6`. -/

import Triptych.Architecture.Denote
import Triptych.Architecture.Value
import Triptych.Architecture.Constraint
import Triptych.Architecture.Assemble
import Triptych.Theorems.Reconcile
import Triptych.Examples.IPv6.spec
import Triptych.Examples.IPv6.grammar

open Triptych
open Triptych.Examples.IPv6

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ══════════════════════════════ engine ══════════════════════════════
The executable counterpart of the spec. `decode` walks the grammar over an input
string and returns its captured components; `computeValue` then evaluates the value
function on those captures, and `isWf`/`isValid` decide well-formedness/acceptance.

Naming convention: CAPITALIZED `IsWf.*`/`IsValid` are the surface `Prop`s you READ
and reason about; lowercase `isWf`/`isValid` are the engine's executable deciders you
RUN (`#eval isValid s`, `#eval computeValue s`). The `equivalence` section below
proves the two describe the same language and value. -/

def IPv6.valueFn := fun m : Triptych.CaptureMap => toV6Addr (Triptych.CaptureMap.toEnvList m "H16")

def IPv6.constraints : List ConstraintEntry :=
  []

abbrev IPv6.isWf (s : String) : Prop :=
  Triptych.isWf IPv6.grammar IPv6.constraints s

abbrev IPv6.satisfiesConstraints (s : String) : Prop :=
  Triptych.satisfiesConstraints IPv6.grammar IPv6.constraints s

abbrev IPv6.isValid (s : String) : Prop :=
  IPv6.isWf s ∧ IPv6.satisfiesConstraints s

def IPv6.computeValue (s : String) :=
  Triptych.computeValueMap IPv6.grammar IPv6.valueFn s

/- ════════════════════════════ equivalence ════════════════════════════
The auto-discharged guarantees relating the readable surface to the executable
engine: `IsWfGrammar_equiv` proves grammar-layout agreement and `IsWf_equiv`
proves full well-formedness agreement. `computeValue_eq` proves the values agree,
and the derived `DecidablePred` instances make the surface predicates executable
via the engine. No `sorry`. -/

theorem IPv6.Internal.matchesRef.H16 (fuel : Nat) (s : String) :
    matchesSym IPv6.grammar (fuel + 1) (Sym.ref "H16") s ↔ IPv6.IsWf.H16 s :=
  by
  rw [matchesSym,
    show
      (IPv6.grammar).prod? "H16" =
        some (Production.mk "H16" [[SymItem.mk (Sym.term TokClass.hexDigit (LenSpec.between 1 4)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold IPv6.IsWf.H16
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsHexDigits_matchesTerm,
    IsFixedHexDigits_matchesTerm, IsHexDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem IPv6.Internal.matchesRef.V6Addr (fuel : Nat) (s : String) :
    matchesSym IPv6.grammar (fuel + 2) (Sym.ref "V6Addr") s ↔ IPv6.IsWf.V6Addr s :=
  by
  rw [matchesSym,
    show
      (IPv6.grammar).prod? "V6Addr" =
        some (Production.mk "V6Addr" [[SymItem.mk (Sym.rep ":" (Sym.ref "H16") 8 (some 8)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold IPv6.IsWf.V6Addr
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym,
    IPv6.Internal.matchesRef.H16]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem IPv6.IsWfGrammar_equiv (s : String) : Triptych.IsWf IPv6.grammar s ↔ IPv6.IsWf.V6Addr s :=
  by
  rw [isWf_eq_isWfProd_start, IsWfProd,
    show
      (IPv6.grammar).prod? (IPv6.grammar).start =
        some (Production.mk "V6Addr" [[SymItem.mk (Sym.rep ":" (Sym.ref "H16") 8 (some 8)) false]])
      from rfl]
  have hstart :
    ∀ n,
      matchesProd IPv6.grammar n (Production.mk "V6Addr" [[SymItem.mk (Sym.rep ":" (Sym.ref "H16") 8 (some 8)) false]])
          s =
        matchesSym IPv6.grammar (n + 1) (Sym.ref "V6Addr") s :=
    by
    intro n
    rw [matchesSym,
      show
        (IPv6.grammar).prod? "V6Addr" =
          some (Production.mk "V6Addr" [[SymItem.mk (Sym.rep ":" (Sym.ref "H16") 8 (some 8)) false]])
        from rfl]
  show
    matchesProd IPv6.grammar (IPv6.grammar).prods.length
        (Production.mk "V6Addr" [[SymItem.mk (Sym.rep ":" (Sym.ref "H16") 8 (some 8)) false]]) s ↔
      _
  rw [hstart]
  exact IPv6.Internal.matchesRef.V6Addr _ s

theorem IPv6.IsWf_equiv (s : String) : IPv6.IsWf s ↔ IPv6.isWf s :=
  by
  unfold IPv6.IsWf IPv6.isWf Triptych.isWf
  rw [← IPv6.IsWfGrammar_equiv, ← decodeSome_iff_IsWf IPv6.grammar (by decide)]
  unfold IPv6.SatisfiesWfConstraints IPv6.constraints
  simp only [Triptych.component, List.forall_mem_cons, List.forall_mem_singleton, List.not_mem_nil, forall_const,
    ConstraintEntry.wfPart, Constraint.eval, ValExpr.eval, presentCount, natOf_getD, intOf_getD, lenOf_getD,
    signOf_getD, and_true, true_and, false_implies, implies_true, Bool.false_eq_true]
  try grind

theorem IPv6.SatisfiesConstraints_equiv (s : String) : IPv6.SatisfiesConstraints s ↔ IPv6.satisfiesConstraints s :=
  by
  unfold IPv6.satisfiesConstraints Triptych.satisfiesConstraints
  unfold IPv6.SatisfiesConstraints IPv6.constraints
  simp only [Triptych.component, List.forall_mem_cons, List.forall_mem_singleton, List.not_mem_nil, forall_const,
    ConstraintEntry.valPart, Constraint.eval, ValExpr.eval, presentCount, natOf_getD, intOf_getD, lenOf_getD,
    signOf_getD, and_true, true_and, false_implies, implies_true, Bool.false_eq_true]
  try grind

theorem IPv6.IsValid_equiv (s : String) : IPv6.IsValid s ↔ IPv6.isValid s :=
  by
  unfold IPv6.IsValid IPv6.isValid
  rw [(IPv6.IsWf_equiv s), (IPv6.SatisfiesConstraints_equiv s)]

instance IPv6.instDecidableGrammar : DecidablePred IPv6.IsWf.V6Addr := fun s =>
  @decidable_of_iff _ _ (IPv6.IsWfGrammar_equiv s) (Triptych.decIsWf IPv6.grammar (by decide) s)

instance IPv6.instDecidableIsWf : DecidablePred IPv6.IsWf := fun s =>
  @decidable_of_iff _ _ (IPv6.IsWf_equiv s).symm inferInstance

instance IPv6.instDecidableSatisfiesConstraints : DecidablePred IPv6.SatisfiesConstraints := fun s =>
  @decidable_of_iff _ _ (IPv6.SatisfiesConstraints_equiv s).symm inferInstance

instance IPv6.instDecidableIsValid : DecidablePred IPv6.IsValid := fun s => inferInstanceAs (Decidable (_ ∧ _))

theorem IPv6.computeValue_eq (s : String) :
    IPv6.computeValue s =
      (decode IPv6.grammar s).map (fun _ => IPv6.value (Triptych.componentList IPv6.grammar s "H16")) :=
  by
  unfold IPv6.computeValue Triptych.computeValueMap Triptych.componentList IPv6.value IPv6.valueFn
  cases h : decode IPv6.grammar s with
  | none => simp
  | some m => simp only [Option.map_some, natOf_getD, intOf_getD, lenOf_getD, signOf_getD, ValExpr.eval]

/- ═══════════════════════════════ parser ══════════════════════════════
The generated correct-by-construction parser `parse` (= `computeValue` gated on the
decidable `isValid`) together with its guarantees — `parse_sound`, `parse_complete`,
`parse_reject` — all AUTO-DISCHARGED here. A verified parser, no `sorry`. -/

theorem IPv6.computeValue_isSome (s : String) : IPv6.isValid s → (IPv6.computeValue s).isSome :=
  by
  intro h
  unfold IPv6.isValid IPv6.isWf Triptych.isWf at h
  unfold IPv6.computeValue Triptych.computeValueMap
  rw [Option.isSome_map]
  exact h.1.1

def IPv6.parse (s : String) :=
  Triptych.gatedParse IPv6.isValid IPv6.computeValue s

theorem IPv6.parse_sound (s : String) (i : IPv6Addr) :
    IPv6.parse s = some i → IPv6.isValid s ∧ IPv6.computeValue s = some i :=
  Triptych.gatedParse_sound _ _ s i

theorem IPv6.parse_complete (s : String) (i : IPv6Addr) :
    IPv6.isValid s → IPv6.computeValue s = some i → IPv6.parse s = some i :=
  Triptych.gatedParse_complete _ _ s i

theorem IPv6.parse_reject (s : String) : IPv6.parse s = none ↔ ¬IPv6.isValid s :=
  Triptych.gatedParse_reject _ _ IPv6.computeValue_isSome s
