/- Generated by FormatSpec from `format_spec Datetime`. -/

import FormatSpec.Examples.Datetime.parser
import FormatSpec.Examples.Datetime.grammar

open FormatSpec
open FormatSpec.Examples.Datetime

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ═══════════════════════════ soundness ═══════════════════════════
Some common proof obligations for validating YOUR OWN external parser against this
specification: `extparse_sound`, `extparse_complete`, and `extparse_reject`, stated
over the readable surface `IsValid`/`computeValue`. These are left as `sorry` —
they are claims about your parser, so you have to prove them yourself. -/

theorem Datetime.extparse_reject (s : String) : Cedar.Spec.Ext.Datetime.parse s = none ↔ ¬Datetime.IsValid s := by sorry

theorem Datetime.extparse_sound (s : String) (d : Cedar.Spec.Ext.Datetime) :
    Cedar.Spec.Ext.Datetime.parse s = some d → Datetime.IsValid s ∧ Datetime.computeValue s = some (datetimeMillis d) :=
  by sorry

theorem Datetime.extparse_complete (s : String) (d : Cedar.Spec.Ext.Datetime) :
    Datetime.IsValid s → Datetime.computeValue s = some (datetimeMillis d) → Cedar.Spec.Ext.Datetime.parse s = some d :=
  by sorry
