-- Generated by FormatSpec from `format_spec Datetime`. Do not edit by hand.

import FormatSpec.Denote
import FormatSpec.Value
import FormatSpec.Constraint
import FormatSpec.Assemble
import FormatSpec.Reconcile
import FormatSpec.Examples.Datetime.grammar

open FormatSpec
open FormatSpec.Examples.Datetime

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

-- ═══════════════════════════════ spec ═══════════════════════════════
-- The reader-facing specification: the grammar, the readable per-production
-- well-formedness predicates `IsWf.*`, the `value` function, the `Constraints`,
-- and the acceptance predicates `SatisfiesConstraints` / `IsValid` (a string is
-- VALID iff it satisfies the grammar and constraints — Cedar's wording).

def Datetime.grammar : Grammar :=
  Grammar.mk "Datetime"
    [Production.mk "Datetime"
        [[SymItem.mk (Sym.ref "Date") false],
          [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
            SymItem.mk (Sym.lit "Z") false],
          [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
            SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
          [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
            SymItem.mk (Sym.ref "Offset") false],
          [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
            SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false]],
      Production.mk "Date"
        [[SymItem.mk (Sym.ref "YYYY") false, SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "MM") false,
            SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "DD") false]],
      Production.mk "Time"
        [[SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "mm") false,
            SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "ss") false]],
      Production.mk "Offset"
        [[SymItem.mk (Sym.lit "+") false, SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.ref "mm") false],
          [SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.ref "mm") false]],
      Production.mk "SSS" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 3)) false]],
      Production.mk "YYYY" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 4)) false]],
      Production.mk "MM" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]],
      Production.mk "DD" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]],
      Production.mk "hh" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]],
      Production.mk "mm" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]],
      Production.mk "ss" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]]]

def Datetime.IsWf.YYYY (s : String) : Prop :=
  IsFixedDigits 4 s

def Datetime.IsWf.MM (s : String) : Prop :=
  IsFixedDigits 2 s

def Datetime.IsWf.DD (s : String) : Prop :=
  IsFixedDigits 2 s

def Datetime.IsWf.Date (s : String) : Prop :=
  ∃ yyyy mm dd,
    ((s = yyyy ++ "-" ++ mm ++ "-" ++ dd ∧ Datetime.IsWf.YYYY yyyy) ∧ Datetime.IsWf.MM mm) ∧ Datetime.IsWf.DD dd

def Datetime.IsWf.hh (s : String) : Prop :=
  IsFixedDigits 2 s

def Datetime.IsWf.mm (s : String) : Prop :=
  IsFixedDigits 2 s

def Datetime.IsWf.ss (s : String) : Prop :=
  IsFixedDigits 2 s

def Datetime.IsWf.Time (s : String) : Prop :=
  ∃ hh mm ss, ((s = hh ++ ":" ++ mm ++ ":" ++ ss ∧ Datetime.IsWf.hh hh) ∧ Datetime.IsWf.mm mm) ∧ Datetime.IsWf.ss ss

def Datetime.IsWf.SSS (s : String) : Prop :=
  IsFixedDigits 3 s

def Datetime.IsWf.Offset (s : String) : Prop :=
  (∃ hh mm, (s = "+" ++ hh ++ mm ∧ Datetime.IsWf.hh hh) ∧ Datetime.IsWf.mm mm) ∨
    ∃ hh mm, (s = "-" ++ hh ++ mm ∧ Datetime.IsWf.hh hh) ∧ Datetime.IsWf.mm mm

def Datetime.IsWf.Datetime (s : String) : Prop :=
  (((Datetime.IsWf.Date s ∨
          ∃ date time, (s = date ++ "T" ++ time ++ "Z" ∧ Datetime.IsWf.Date date) ∧ Datetime.IsWf.Time time) ∨
        ∃ date time sss,
          ((s = date ++ "T" ++ time ++ "." ++ sss ++ "Z" ∧ Datetime.IsWf.Date date) ∧ Datetime.IsWf.Time time) ∧
            Datetime.IsWf.SSS sss) ∨
      ∃ date time offset,
        ((s = date ++ "T" ++ time ++ offset ∧ Datetime.IsWf.Date date) ∧ Datetime.IsWf.Time time) ∧
          Datetime.IsWf.Offset offset) ∨
    ∃ date time sss offset,
      (((s = date ++ "T" ++ time ++ "." ++ sss ++ offset ∧ Datetime.IsWf.Date date) ∧ Datetime.IsWf.Time time) ∧
          Datetime.IsWf.SSS sss) ∧
        Datetime.IsWf.Offset offset

def Datetime.value (yyyy : String) (mm : String) (dd : String) (time_hh : String) (time_mm : String) (ss : String)
    (sss : String) (offset_hh : String) (offset_mm : String) (offset : String) :=
  epochMillis yyyy mm dd time_hh time_mm ss sss offset_hh offset_mm offset

def Datetime.Constraints (mm : String) (time_hh : String) (time_mm : String) (ss : String) (offset_hh : String)
    (offset_mm : String) (yyyy : String) (dd : String) : Prop :=
  (((((((1 : Int) ≤ natOf mm ∧ natOf mm ≤ (12 : Int)) ∧ (0 : Int) ≤ natOf time_hh ∧ natOf time_hh ≤ (23 : Int)) ∧
            (0 : Int) ≤ natOf time_mm ∧ natOf time_mm ≤ (59 : Int)) ∧
          (0 : Int) ≤ natOf ss ∧ natOf ss ≤ (59 : Int)) ∧
        (0 : Int) ≤ natOf offset_hh ∧ natOf offset_hh ≤ (23 : Int)) ∧
      (0 : Int) ≤ natOf offset_mm ∧ natOf offset_mm ≤ (59 : Int)) ∧
    dayBound yyyy mm dd = true

def Datetime.SatisfiesConstraints (s : String) : Prop :=
  Datetime.Constraints (FormatSpec.component Datetime.grammar s "MM")
    (FormatSpec.component Datetime.grammar s "Time.hh") (FormatSpec.component Datetime.grammar s "Time.mm")
    (FormatSpec.component Datetime.grammar s "ss") (FormatSpec.component Datetime.grammar s "Offset.hh")
    (FormatSpec.component Datetime.grammar s "Offset.mm") (FormatSpec.component Datetime.grammar s "YYYY")
    (FormatSpec.component Datetime.grammar s "DD")

abbrev Datetime.IsValid (s : String) : Prop :=
  Datetime.IsWf.Datetime s ∧ Datetime.SatisfiesConstraints s
