/- Generated by FormatSpec from `format_spec Duration`. -/

import FormatSpec.Denote
import FormatSpec.Value
import FormatSpec.Constraint
import FormatSpec.Assemble
import FormatSpec.Reconcile
import FormatSpec.Examples.Duration.spec

open FormatSpec

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ══════════════════════════════ engine ══════════════════════════════
The executable engine, constructed by interpreting the input grammar's concrete
syntax tree: the deep-embedded value/constraint ASTs plus the interpreter bundle
(`isWf`, `isValid`, `computeValue`) built on top of the total capture-extracting
`decode`. Unlike the `Prop`-level surface, these actually run — `decode`/evaluate
a string and compute its captures, validity, and value. -/

def Duration.valueExpr : ValExpr :=
  ValExpr.add
    (ValExpr.add
      (ValExpr.add
        (ValExpr.add (ValExpr.mul (ValExpr.nat "DDays") (ValExpr.lit 86400000))
          (ValExpr.mul (ValExpr.nat "DHours") (ValExpr.lit 3600000)))
        (ValExpr.mul (ValExpr.nat "DMinutes") (ValExpr.lit 60000)))
      (ValExpr.mul (ValExpr.nat "DSeconds") (ValExpr.lit 1000)))
    (ValExpr.nat "DMillis")

def Duration.valueFn : Env → Int :=
  (Duration.valueExpr).eval

def Duration.constraints : List ConstraintEntry :=
  [ConstraintEntry.dsl (Constraint.card CardOp.atLeast 1 ["Components"]),
    ConstraintEntry.dsl
      (Constraint.and (Constraint.le (ValExpr.lit (-9223372036854775808)) Duration.valueExpr)
        (Constraint.le Duration.valueExpr (ValExpr.lit 9223372036854775807)))]

abbrev Duration.isWf (s : String) : Prop :=
  FormatSpec.isWf Duration.grammar Duration.constraints s

abbrev Duration.satisfiesConstraints (s : String) : Prop :=
  FormatSpec.satisfiesConstraints Duration.grammar Duration.constraints s

abbrev Duration.isValid (s : String) : Prop :=
  Duration.isWf s ∧ Duration.satisfiesConstraints s

def Duration.computeValue (s : String) : Option Int :=
  FormatSpec.computeValue Duration.grammar Duration.valueExpr s

/- ════════════════════════════ equivalence ════════════════════════════
The auto-discharged guarantees relating the readable surface to the executable
engine: `IsWf_equiv` (+ its `Internal.matchesRef.*` lemmas) proves recognition
agrees, `computeValue_eq` proves the values agree, and the derived `DecidablePred`
instances make the surface predicates executable via the engine. No `sorry`. -/

theorem Duration.Internal.matchesRef.DDays (fuel : Nat) (s : String) :
    matchesSym Duration.grammar (fuel + 1) (Sym.ref "DDays") s ↔ Duration.IsWf.DDays s :=
  by
  rw [matchesSym,
    show
      (Duration.grammar).prod? "DDays" =
        some (Production.mk "DDays" [[SymItem.mk (Sym.term TokClass.digit LenSpec.atLeastOne) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Duration.IsWf.DDays
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Duration.Internal.matchesRef.Days (fuel : Nat) (s : String) :
    matchesSym Duration.grammar (fuel + 2) (Sym.ref "Days") s ↔ Duration.IsWf.Days s :=
  by
  rw [matchesSym,
    show
      (Duration.grammar).prod? "Days" =
        some (Production.mk "Days" [[SymItem.mk (Sym.ref "DDays") false, SymItem.mk (Sym.lit "d") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Duration.IsWf.Days
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym,
    Duration.Internal.matchesRef.DDays]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Duration.Internal.matchesRef.DHours (fuel : Nat) (s : String) :
    matchesSym Duration.grammar (fuel + 1) (Sym.ref "DHours") s ↔ Duration.IsWf.DHours s :=
  by
  rw [matchesSym,
    show
      (Duration.grammar).prod? "DHours" =
        some (Production.mk "DHours" [[SymItem.mk (Sym.term TokClass.digit LenSpec.atLeastOne) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Duration.IsWf.DHours
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Duration.Internal.matchesRef.Hours (fuel : Nat) (s : String) :
    matchesSym Duration.grammar (fuel + 2) (Sym.ref "Hours") s ↔ Duration.IsWf.Hours s :=
  by
  rw [matchesSym,
    show
      (Duration.grammar).prod? "Hours" =
        some (Production.mk "Hours" [[SymItem.mk (Sym.ref "DHours") false, SymItem.mk (Sym.lit "h") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Duration.IsWf.Hours
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym,
    Duration.Internal.matchesRef.DHours]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Duration.Internal.matchesRef.DMinutes (fuel : Nat) (s : String) :
    matchesSym Duration.grammar (fuel + 1) (Sym.ref "DMinutes") s ↔ Duration.IsWf.DMinutes s :=
  by
  rw [matchesSym,
    show
      (Duration.grammar).prod? "DMinutes" =
        some (Production.mk "DMinutes" [[SymItem.mk (Sym.term TokClass.digit LenSpec.atLeastOne) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Duration.IsWf.DMinutes
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Duration.Internal.matchesRef.Minutes (fuel : Nat) (s : String) :
    matchesSym Duration.grammar (fuel + 2) (Sym.ref "Minutes") s ↔ Duration.IsWf.Minutes s :=
  by
  rw [matchesSym,
    show
      (Duration.grammar).prod? "Minutes" =
        some (Production.mk "Minutes" [[SymItem.mk (Sym.ref "DMinutes") false, SymItem.mk (Sym.lit "m") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Duration.IsWf.Minutes
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym,
    Duration.Internal.matchesRef.DMinutes]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Duration.Internal.matchesRef.DSeconds (fuel : Nat) (s : String) :
    matchesSym Duration.grammar (fuel + 1) (Sym.ref "DSeconds") s ↔ Duration.IsWf.DSeconds s :=
  by
  rw [matchesSym,
    show
      (Duration.grammar).prod? "DSeconds" =
        some (Production.mk "DSeconds" [[SymItem.mk (Sym.term TokClass.digit LenSpec.atLeastOne) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Duration.IsWf.DSeconds
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Duration.Internal.matchesRef.Seconds (fuel : Nat) (s : String) :
    matchesSym Duration.grammar (fuel + 2) (Sym.ref "Seconds") s ↔ Duration.IsWf.Seconds s :=
  by
  rw [matchesSym,
    show
      (Duration.grammar).prod? "Seconds" =
        some (Production.mk "Seconds" [[SymItem.mk (Sym.ref "DSeconds") false, SymItem.mk (Sym.lit "s") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Duration.IsWf.Seconds
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym,
    Duration.Internal.matchesRef.DSeconds]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Duration.Internal.matchesRef.DMillis (fuel : Nat) (s : String) :
    matchesSym Duration.grammar (fuel + 1) (Sym.ref "DMillis") s ↔ Duration.IsWf.DMillis s :=
  by
  rw [matchesSym,
    show
      (Duration.grammar).prod? "DMillis" =
        some (Production.mk "DMillis" [[SymItem.mk (Sym.term TokClass.digit LenSpec.atLeastOne) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Duration.IsWf.DMillis
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Duration.Internal.matchesRef.Millis (fuel : Nat) (s : String) :
    matchesSym Duration.grammar (fuel + 2) (Sym.ref "Millis") s ↔ Duration.IsWf.Millis s :=
  by
  rw [matchesSym,
    show
      (Duration.grammar).prod? "Millis" =
        some (Production.mk "Millis" [[SymItem.mk (Sym.ref "DMillis") false, SymItem.mk (Sym.lit "ms") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Duration.IsWf.Millis
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym,
    Duration.Internal.matchesRef.DMillis]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Duration.Internal.matchesRef.Components (fuel : Nat) (s : String) :
    matchesSym Duration.grammar (fuel + 3) (Sym.ref "Components") s ↔ Duration.IsWf.Components s :=
  by
  rw [matchesSym,
    show
      (Duration.grammar).prod? "Components" =
        some
          (Production.mk "Components"
            [[SymItem.mk (Sym.ref "Days") true, SymItem.mk (Sym.ref "Hours") true, SymItem.mk (Sym.ref "Minutes") true,
                SymItem.mk (Sym.ref "Seconds") true, SymItem.mk (Sym.ref "Millis") true]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Duration.IsWf.Components
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq_opt_cons, FormatSpec.matchesSeq.eq_1,
    FormatSpec.matchesSeq.eq_2, exists_eq_left, if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc,
    FormatSpec.matchesSym, Duration.Internal.matchesRef.Days, Duration.Internal.matchesRef.Hours,
    Duration.Internal.matchesRef.Minutes, Duration.Internal.matchesRef.Seconds, Duration.Internal.matchesRef.Millis]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Duration.Internal.matchesRef.Duration (fuel : Nat) (s : String) :
    matchesSym Duration.grammar (fuel + 4) (Sym.ref "Duration") s ↔ Duration.IsWf.Duration s :=
  by
  rw [matchesSym,
    show
      (Duration.grammar).prod? "Duration" =
        some (Production.mk "Duration" [[SymItem.mk (Sym.lit "-") true, SymItem.mk (Sym.ref "Components") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Duration.IsWf.Duration
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym,
    Duration.Internal.matchesRef.Components]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Duration.IsWf_equiv (s : String) : IsWf Duration.grammar s ↔ Duration.IsWf.Duration s :=
  by
  rw [isWf_eq_isWfProd_start, IsWfProd,
    show
      (Duration.grammar).prod? (Duration.grammar).start =
        some (Production.mk "Duration" [[SymItem.mk (Sym.lit "-") true, SymItem.mk (Sym.ref "Components") false]])
      from rfl]
  have hstart :
    ∀ n,
      matchesProd Duration.grammar n
          (Production.mk "Duration" [[SymItem.mk (Sym.lit "-") true, SymItem.mk (Sym.ref "Components") false]]) s =
        matchesSym Duration.grammar (n + 1) (Sym.ref "Duration") s :=
    by
    intro n
    rw [matchesSym,
      show
        (Duration.grammar).prod? "Duration" =
          some (Production.mk "Duration" [[SymItem.mk (Sym.lit "-") true, SymItem.mk (Sym.ref "Components") false]])
        from rfl]
  show
    matchesProd Duration.grammar (Duration.grammar).prods.length
        (Production.mk "Duration" [[SymItem.mk (Sym.lit "-") true, SymItem.mk (Sym.ref "Components") false]]) s ↔
      _
  rw [hstart]
  exact Duration.Internal.matchesRef.Duration _ s

instance Duration.instDecidableIsWf : DecidablePred Duration.IsWf.Duration := fun s =>
  @decidable_of_iff _ _ (Duration.IsWf_equiv s) (FormatSpec.decIsWf Duration.grammar (by decide) s)

instance Duration.instDecidableSatisfiesConstraints : DecidablePred Duration.SatisfiesConstraints := fun s => by
  simp only [Duration.SatisfiesConstraints, Duration.Constraints, Duration.value]; exact inferInstance

instance Duration.instDecidableIsValid : DecidablePred Duration.IsValid := fun s => inferInstanceAs (Decidable (_ ∧ _))

theorem Duration.IsValid_equiv (s : String) : Duration.IsValid s ↔ Duration.isValid s :=
  by
  unfold Duration.IsValid Duration.isValid Duration.isWf Duration.satisfiesConstraints
  unfold FormatSpec.isWf FormatSpec.satisfiesConstraints
  rw [← Duration.IsWf_equiv, ← decodeSome_iff_IsWf Duration.grammar (by decide)]
  unfold Duration.SatisfiesConstraints Duration.Constraints Duration.constraints Duration.value Duration.valueExpr
  simp only [FormatSpec.component, List.forall_mem_cons, List.forall_mem_singleton, List.not_mem_nil, forall_const,
    if_true, if_false, ConstraintEntry.wfPart, ConstraintEntry.valPart, Constraint.wfPart, Constraint.valPart,
    Constraint.isValueDependent, Constraint.eval, ValExpr.eval, presentCount, natOf_getD, intOf_getD, lenOf_getD,
    signOf_getD, and_true, true_and, false_implies, implies_true, Bool.false_eq_true]
  try grind

theorem Duration.computeValue_eq (s : String) :
    Duration.computeValue s =
      (decode Duration.grammar s).map
        (fun _ =>
          Duration.value (FormatSpec.component Duration.grammar s "DDays")
            (FormatSpec.component Duration.grammar s "DHours") (FormatSpec.component Duration.grammar s "DMinutes")
            (FormatSpec.component Duration.grammar s "DSeconds") (FormatSpec.component Duration.grammar s "DMillis")) :=
  by
  unfold Duration.computeValue FormatSpec.computeValue FormatSpec.component FormatSpec.envOf Duration.value
    Duration.valueExpr
  cases h : decode Duration.grammar s with
  | none => simp
  | some m => simp only [Option.map_some, natOf_getD, intOf_getD, lenOf_getD, signOf_getD, ValExpr.eval]

/- ═══════════════════════════════ parser ══════════════════════════════
The generated correct-by-construction parser `parse` (= `computeValue` gated on the
decidable `isValid`) together with its guarantees — `parse_sound`, `parse_complete`,
`parse_reject` — all AUTO-DISCHARGED here. A verified parser, no `sorry`. -/

theorem Duration.computeValue_isSome (s : String) : Duration.isValid s → (Duration.computeValue s).isSome :=
  by
  intro h
  unfold Duration.isValid Duration.isWf FormatSpec.isWf at h
  unfold Duration.computeValue FormatSpec.computeValue
  rw [Option.isSome_map]
  exact h.1.1

def Duration.parse (s : String) :=
  FormatSpec.gatedParse Duration.isValid Duration.computeValue s

theorem Duration.parse_sound : SoundStmt Duration.isValid Duration.computeValue Duration.parse id :=
  FormatSpec.gatedParse_sound _ _

theorem Duration.parse_complete : CompleteStmt Duration.isValid Duration.computeValue Duration.parse id :=
  FormatSpec.gatedParse_complete _ _

theorem Duration.parse_reject : RejectStmt Duration.isValid Duration.parse :=
  FormatSpec.gatedParse_reject _ _ Duration.computeValue_isSome
