/- Generated by FormatSpec from `format_spec Duration`. -/

import FormatSpec.Examples.Duration.parser
import FormatSpec.Examples.Duration.grammar

open FormatSpec
open FormatSpec.Examples.Duration

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ═══════════════════════════ soundness ═══════════════════════════
Some common proof obligations for validating YOUR OWN external parser against this
specification: `extparse_sound`, `extparse_complete`, and `extparse_reject`, stated
over the readable surface `IsValid`/`computeValue`. These are left as `sorry` —
they are claims about your parser, so you have to prove them yourself. -/

theorem Duration.extparse_reject (s : String) : Cedar.Spec.Ext.Datetime.Duration.parse s = none ↔ ¬Duration.IsValid s :=
  by sorry

theorem Duration.extparse_sound (s : String) (d : Cedar.Spec.Ext.Datetime.Duration) :
    Cedar.Spec.Ext.Datetime.Duration.parse s = some d →
      Duration.IsValid s ∧ Duration.computeValue s = some (durationMillis d) :=
  by sorry

theorem Duration.extparse_complete (s : String) (d : Cedar.Spec.Ext.Datetime.Duration) :
    Duration.IsValid s →
      Duration.computeValue s = some (durationMillis d) → Cedar.Spec.Ext.Datetime.Duration.parse s = some d :=
  by sorry

theorem Duration.encode_accepted (i : Int) : Duration.isValid (millisToString i) := by sorry

theorem Duration.encode_value (i : Int) : Duration.computeValue (millisToString i) = some i := by sorry

theorem Duration.parse_toString_roundtrip (i : Int) : Duration.parse (millisToString i) = some i :=
  by
  have h :=
    FormatSpec.parse_toString_roundtrip (π := id) Duration.parse_sound Duration.parse_reject Duration.encode_accepted
      Duration.encode_value i
  simpa using h

theorem Duration.toString_injective (i i' : Int) (h : millisToString i = millisToString i') : i = i' :=
  FormatSpec.toString_injective (π := id) Duration.parse_sound Duration.parse_reject Duration.encode_accepted
    Duration.encode_value i i' h

theorem Duration.normalize_eq_iff_parse_eq (s s' : String) :
    (Duration.parse s).map millisToString = (Duration.parse s').map millisToString ↔
      Duration.parse s = Duration.parse s' :=
  by
  have h :=
    FormatSpec.normalize_eq_iff_parse_eq (π := id) Duration.parse_sound Duration.parse_reject Duration.encode_accepted
      Duration.encode_value s s'
  simpa using h

theorem Duration.extparse_toString_roundtrip (i : Int) :
    (Cedar.Spec.Ext.Datetime.Duration.parse (millisToString i)).map durationMillis = some i :=
  FormatSpec.parse_toString_roundtrip Duration.extparse_sound Duration.extparse_reject
    (fun b => (Duration.IsValid_equiv (millisToString b)).mpr (Duration.encode_accepted b)) Duration.encode_value i

theorem Duration.extparse_toString_injective (i i' : Int) (h : millisToString i = millisToString i') : i = i' :=
  FormatSpec.toString_injective Duration.extparse_sound Duration.extparse_reject
    (fun b => (Duration.IsValid_equiv (millisToString b)).mpr (Duration.encode_accepted b)) Duration.encode_value i i' h

theorem Duration.extparse_normalize_eq_iff_parse_eq (s s' : String) :
    (Cedar.Spec.Ext.Datetime.Duration.parse s).map (fun d => millisToString (durationMillis d)) =
        (Cedar.Spec.Ext.Datetime.Duration.parse s').map (fun d => millisToString (durationMillis d)) ↔
      (Cedar.Spec.Ext.Datetime.Duration.parse s).map durationMillis =
        (Cedar.Spec.Ext.Datetime.Duration.parse s').map durationMillis :=
  FormatSpec.normalize_eq_iff_parse_eq Duration.extparse_sound Duration.extparse_reject
    (fun b => (Duration.IsValid_equiv (millisToString b)).mpr (Duration.encode_accepted b)) Duration.encode_value s s'
