/- Generated by FormatSpec from `format_spec Decimal`. -/

import FormatSpec.Examples.Decimal.parser
import FormatSpec.Examples.Decimal.grammar

open FormatSpec
open FormatSpec.Examples.Decimal

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ═══════════════════════════ soundness ═══════════════════════════
Some common proof obligations for validating YOUR OWN external parser against this
specification: `extparse_sound`, `extparse_complete`, and `extparse_reject`, stated
over the readable surface `IsValid`/`computeValue`. These are left as `sorry` —
they are claims about your parser, so you have to prove them yourself. -/

theorem Decimal.extparse_reject (s : String) : Cedar.Spec.Ext.Decimal.parse s = none ↔ ¬Decimal.IsValid s := by sorry

theorem Decimal.extparse_sound (s : String) (a : _) :
    Cedar.Spec.Ext.Decimal.parse s = some a → Decimal.IsValid s ∧ Decimal.computeValue s = some (Int64.toInt a) := by
  sorry

theorem Decimal.extparse_complete (s : String) (v : _) :
    Decimal.IsValid s →
      Decimal.computeValue s = some v → ∃ a, Cedar.Spec.Ext.Decimal.parse s = some a ∧ Int64.toInt a = v :=
  by sorry
