-- Generated by FormatSpec from `format_spec Decimal`. Do not edit by hand.

import FormatSpec.Examples.Decimal.parser
import FormatSpec.Examples.Decimal.grammar

open FormatSpec
open FormatSpec.Examples.Decimal

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

-- ═══════════════════════════ soundness ═══════════════════════════
-- The parser-correctness OBLIGATIONS for the external, hand-written parser, stated
-- over the SURFACE `IsValid`/`computeValue` (`sorry`d — the ONLY proofs left to the
-- human; discharge by bridging `IsValid` to `decode` via `IsWf_equiv`).

theorem Decimal.reject_ext : RejectStmt Decimal.IsValid Cedar.Spec.Ext.Decimal.parse := by sorry

theorem Decimal.sound_ext : SoundStmt Decimal.IsValid Decimal.computeValue Cedar.Spec.Ext.Decimal.parse cedarProj := by
  sorry

theorem Decimal.complete_ext :
    CompleteStmt Decimal.IsValid Decimal.computeValue Cedar.Spec.Ext.Decimal.parse cedarProj := by sorry
