/- Generated by FormatSpec from `format_spec Decimal`. -/

import FormatSpec.Examples.Decimal.parser
import FormatSpec.Examples.Decimal.grammar

open FormatSpec
open FormatSpec.Examples.Decimal

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ═══════════════════════════ soundness ═══════════════════════════
Some common proof obligations for validating YOUR OWN external parser against this
specification: `extparse_sound`, `extparse_complete`, and `extparse_reject`, stated
over the readable surface `IsValid`/`computeValue`. These are left as `sorry` —
they are claims about your parser, so you have to prove them yourself. -/

theorem Decimal.extparse_reject (s : String) : Cedar.Spec.Ext.Decimal.parse s = none ↔ ¬Decimal.IsValid s := by sorry

theorem Decimal.extparse_sound (s : String) (d : Cedar.Spec.Ext.Decimal) :
    Cedar.Spec.Ext.Decimal.parse s = some d → Decimal.IsValid s ∧ Decimal.computeValue s = some (Int64.toInt d) := by
  sorry

theorem Decimal.extparse_complete (s : String) (d : Cedar.Spec.Ext.Decimal) :
    Decimal.IsValid s → Decimal.computeValue s = some (Int64.toInt d) → Cedar.Spec.Ext.Decimal.parse s = some d := by
  sorry

theorem Decimal.encode_accepted (i : Int) : Decimal.isValid (decimalToString i) := by sorry

theorem Decimal.encode_value (i : Int) : Decimal.computeValue (decimalToString i) = some i := by sorry

theorem Decimal.parse_toString_roundtrip (i : Int) : Decimal.parse (decimalToString i) = some i :=
  FormatSpec.gatedParse_toString_roundtrip Decimal.encode_accepted Decimal.encode_value i

theorem Decimal.toString_injective (i i' : Int) (h : decimalToString i = decimalToString i') : i = i' :=
  FormatSpec.toString_injective Decimal.encode_accepted Decimal.encode_value i i' h

theorem Decimal.normalize_eq_iff_parse_eq (s s' : String) :
    (Decimal.parse s).map decimalToString = (Decimal.parse s').map decimalToString ↔
      Decimal.parse s = Decimal.parse s' :=
  FormatSpec.normalize_eq_iff_parse_eq Decimal.encode_accepted Decimal.encode_value s s'
