/- Generated by FormatSpec from `format_spec Decimal`. Do not edit by hand. -/

import FormatSpec.Denote
import FormatSpec.Value
import FormatSpec.Constraint
import FormatSpec.Assemble
import FormatSpec.Reconcile

open FormatSpec

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ═══════════════════════════════ spec ═══════════════════════════════
The more readable specification. Each production of the input grammar becomes an
inlined well-formedness predicate `IsWf.*` written as a plain existential over the
named captures, so you can read it side-by-side with the grammar and check that it
says the same thing. `value` is the value function, `Constraints` the extra
conditions, and `IsValid` the overall acceptance predicate (well-formed ∧
constraints). This file is proof-free — it is what you cite. -/

def Decimal.grammar : Grammar :=
  Grammar.mk "Decimal"
    [Production.mk "Decimal"
        [[SymItem.mk (Sym.ref "Integer") false, SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "Fraction") false]],
      Production.mk "Integer"
        [[SymItem.mk (Sym.lit "-") true, SymItem.mk (Sym.term TokClass.digit LenSpec.atLeastOne) false]],
      Production.mk "Fraction" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.between 1 4)) false]]]

def Decimal.IsWf.Integer (s : String) : Prop :=
  (∃ rest, s = "-" ++ rest ∧ IsDigits rest) ∨ IsDigits s

def Decimal.IsWf.Fraction (s : String) : Prop :=
  IsDigitsBetween 1 4 s

def Decimal.IsWf.Decimal (s : String) : Prop :=
  ∃ integer fraction, (s = integer ++ "." ++ fraction ∧ Decimal.IsWf.Integer integer) ∧ Decimal.IsWf.Fraction fraction

def Decimal.value (integer : String) (fraction : String) : Int :=
  intOf integer * (10 : Int) ^ ((4 : Int)).toNat +
    signOf integer * natOf fraction * (10 : Int) ^ (((4 : Int) - lenOf fraction)).toNat

def Decimal.Constraints (integer : String) (fraction : String) : Prop :=
  (-9223372036854775808 : Int) ≤ Decimal.value integer fraction ∧
    Decimal.value integer fraction ≤ (9223372036854775807 : Int)

def Decimal.SatisfiesConstraints (s : String) : Prop :=
  Decimal.Constraints (FormatSpec.component Decimal.grammar s "Integer")
    (FormatSpec.component Decimal.grammar s "Fraction")

abbrev Decimal.IsValid (s : String) : Prop :=
  Decimal.IsWf.Decimal s ∧ Decimal.SatisfiesConstraints s
