/- Generated by Triptych from `triptych IPv4`. -/

import Outputs.IPv4.parser
import Inputs.IPv4
import Proofs.IPv4.RuleRegistrySoundness

open Triptych
open CedarExamples.IPv4

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- soundness · generated parser
The one serializer obligation gives the exact valid typed view produced by `ipNetToStr`.
Acceptance, value agreement, generated-parser roundtrip, injectivity, and normalization are
derived from that witness. -/

theorem IPv4.encode_view (i : IPv4Net) :
    ∃ v : IPv4.View,
      IPv4.decodeView (ipNetToStr i) = some v ∧
      IPv4.View.Valid v ∧
      IPv4.View.denotation v = i := by
  triptych_encode [IPv4.RuleRegistrySoundness.parser_ipNetToStr,
    IPv4.RuleRegistrySoundness.parser_agrees, IPv4.IsValid_view,
    IPv4.computeValue_view]

theorem IPv4.encode_accepted (i : IPv4Net) : IPv4.IsValid (ipNetToStr i) := by
  obtain ⟨v, hview, hvalidView, _⟩ := IPv4.encode_view i
  exact (IPv4.IsValid_view (ipNetToStr i)).mpr ⟨v, hview, hvalidView⟩

theorem IPv4.encode_value (i : IPv4Net) :
    IPv4.computeValue (ipNetToStr i) = some i := by
  obtain ⟨v, hview, _, hresult⟩ := IPv4.encode_view i
  rw [IPv4.computeValue_view, hview]
  exact congrArg some hresult

theorem IPv4.parse_toString_roundtrip (i : IPv4Net) : IPv4.parse (ipNetToStr i) = some i :=
  Triptych.parse_toString_roundtrip_of_encodeView
    IPv4.parse_eq_some_iff_view IPv4.encode_view i

theorem IPv4.toString_injective (i i' : IPv4Net)
    (h : ipNetToStr i = ipNetToStr i') : i = i' :=
  Triptych.toString_injective IPv4.parse_toString_roundtrip i i' h

theorem IPv4.normalize_eq_iff_parse_eq (s s' : String) :
    (IPv4.parse s).map ipNetToStr = (IPv4.parse s').map ipNetToStr ↔
      IPv4.parse s = IPv4.parse s' :=
  Triptych.normalize_eq_iff_parse_eq IPv4.parse_toString_roundtrip s s'

/- soundness · external parser
Obligations for validating YOUR OWN external parser against this specification:
`extparse_sound`, `extparse_complete`, and `extparse_reject`, stated over the readable
surface `IsValid`/`computeValue`. The scaffold marks them as user obligations because they are
claims about your parser; they are discharged below. Given them, the external printer
theorems (`extparse_toString_*`) are DISCHARGED, reusing the generated section's
derived encode projections. -/

theorem IPv4.extparse_reject (s : String) : ipv4Only s = none ↔ ¬IPv4.IsValid s := by
  triptych_auto [IPv4.RuleRegistrySoundness.parser_rejects_iff]

theorem IPv4.extparse_eq_none_iff_view (s : String) :
    ipv4Only s = none ↔
      ¬∃ v : IPv4.View, IPv4.decodeView s = some v ∧ IPv4.View.Valid v := by
  triptych_auto [IPv4.extparse_reject, IPv4.IsValid_view]

theorem IPv4.extparse_sound (s : String) (i : IPv4Net) :
    ipv4Only s = some i → IPv4.IsValid s ∧ IPv4.computeValue s = some (id i) := by
  triptych_auto [IPv4.RuleRegistrySoundness.parser_agrees, id]

theorem IPv4.extparse_complete (s : String) (i : IPv4Net) :
    IPv4.IsValid s → IPv4.computeValue s = some (id i) → ipv4Only s = some i := by
  triptych_auto [IPv4.RuleRegistrySoundness.parser_agrees, id]

theorem IPv4.extparse_eq_some_iff_view (s : String) (i : IPv4Net) :
    ipv4Only s = some i ↔
      ∃ v : IPv4.View,
        IPv4.decodeView s = some v ∧
        IPv4.View.Valid v ∧
        IPv4.View.denotation v = id i := by
  triptych_auto [IPv4.RuleRegistrySoundness.parser_agrees, IPv4.IsValid_view,
    IPv4.computeValue_view, id]

theorem IPv4.extparse_toString_roundtrip (i : IPv4Net) : ipv4Only (ipNetToStr i) = some i :=
  Triptych.parse_toString_roundtrip IPv4.extparse_complete IPv4.encode_accepted
    IPv4.encode_value i

theorem IPv4.extparse_toString_injective (i i' : IPv4Net)
    (h : ipNetToStr i = ipNetToStr i') : i = i' :=
  Triptych.toString_injective IPv4.extparse_toString_roundtrip i i' h

theorem IPv4.extparse_normalize_eq_iff_parse_eq (s s' : String) :
    (ipv4Only s).map ipNetToStr = (ipv4Only s').map ipNetToStr ↔ ipv4Only s = ipv4Only s' :=
  Triptych.normalize_eq_iff_parse_eq IPv4.extparse_toString_roundtrip s s'
