/- Generated by Triptych from `triptych Datetime`. -/

import Triptych.Architecture.GeneratedLinter
import Triptych.Architecture.Denote
import Triptych.Architecture.Derivation
import Triptych.Architecture.Value
import Triptych.Architecture.Constraint
import Triptych.Architecture.Assemble
import Triptych.Theorems.Reconcile
import Triptych.Theorems.Value
import Triptych.Theorems.DecodeLemmas
import Triptych.Theorems.Derivation
import Outputs.Datetime.spec
import Inputs.Datetime

open Triptych
open CedarExamples.Datetime

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false

/- ══════════════════════════════ engine ══════════════════════════════
The executable counterpart of the spec. `decode` walks the grammar over an input
string and returns its captured components; `computeValue` then evaluates the value
function on those captures. Generated `DecidablePred` instances make the readable
`IsWf` and `IsValid` predicates directly executable.
`decodeView` packages the exact input and value/constraint captures as a typed `View`.

The public format API stays capitalized: use `#eval decide (IsValid s)` and
`#eval computeValue s`. The equivalence section below proves that these readable
predicates execute through the generic Triptych interpreter. -/

instance Datetime.Derivation.YYYY.instDecidableValid : DecidablePred Datetime.Derivation.YYYY.Valid := fun d => by
  cases d <;> simp only [Datetime.Derivation.YYYY.Valid] <;> infer_instance

def Datetime.Derivation.YYYY.capturesWith (qual : String) : Datetime.Derivation.YYYY → Triptych.CaptureMap
  | .alt0 part0 => ([] ++ [])

instance Datetime.Derivation.MM.instDecidableValid : DecidablePred Datetime.Derivation.MM.Valid := fun d => by
  cases d <;> simp only [Datetime.Derivation.MM.Valid] <;> infer_instance

def Datetime.Derivation.MM.capturesWith (qual : String) : Datetime.Derivation.MM → Triptych.CaptureMap
  | .alt0 part0 => ([] ++ [])

instance Datetime.Derivation.DD.instDecidableValid : DecidablePred Datetime.Derivation.DD.Valid := fun d => by
  cases d <;> simp only [Datetime.Derivation.DD.Valid] <;> infer_instance

def Datetime.Derivation.DD.capturesWith (qual : String) : Datetime.Derivation.DD → Triptych.CaptureMap
  | .alt0 part0 => ([] ++ [])

instance Datetime.Derivation.Date.instDecidableValid : DecidablePred Datetime.Derivation.Date.Valid := fun d => by
  cases d <;> simp only [Datetime.Derivation.Date.Valid] <;> infer_instance

def Datetime.Derivation.Date.capturesWith (qual : String) : Datetime.Derivation.Date → Triptych.CaptureMap
  | .alt0 part0 part2 part4 =>
    (Triptych.referenceCaptures qual "YYYY" (Datetime.Derivation.YYYY.render part0) ++
        Datetime.Derivation.YYYY.capturesWith "YYYY" part0 ++
      ([] ++
        (Triptych.referenceCaptures qual "MM" (Datetime.Derivation.MM.render part2) ++
            Datetime.Derivation.MM.capturesWith "MM" part2 ++
          ([] ++
            (Triptych.referenceCaptures qual "DD" (Datetime.Derivation.DD.render part4) ++
                Datetime.Derivation.DD.capturesWith "DD" part4 ++
              [])))))

instance Datetime.Derivation.hh.instDecidableValid : DecidablePred Datetime.Derivation.hh.Valid := fun d => by
  cases d <;> simp only [Datetime.Derivation.hh.Valid] <;> infer_instance

def Datetime.Derivation.hh.capturesWith (qual : String) : Datetime.Derivation.hh → Triptych.CaptureMap
  | .alt0 part0 => ([] ++ [])

instance Datetime.Derivation.mm.instDecidableValid : DecidablePred Datetime.Derivation.mm.Valid := fun d => by
  cases d <;> simp only [Datetime.Derivation.mm.Valid] <;> infer_instance

def Datetime.Derivation.mm.capturesWith (qual : String) : Datetime.Derivation.mm → Triptych.CaptureMap
  | .alt0 part0 => ([] ++ [])

instance Datetime.Derivation.ss.instDecidableValid : DecidablePred Datetime.Derivation.ss.Valid := fun d => by
  cases d <;> simp only [Datetime.Derivation.ss.Valid] <;> infer_instance

def Datetime.Derivation.ss.capturesWith (qual : String) : Datetime.Derivation.ss → Triptych.CaptureMap
  | .alt0 part0 => ([] ++ [])

instance Datetime.Derivation.Time.instDecidableValid : DecidablePred Datetime.Derivation.Time.Valid := fun d => by
  cases d <;> simp only [Datetime.Derivation.Time.Valid] <;> infer_instance

def Datetime.Derivation.Time.capturesWith (qual : String) : Datetime.Derivation.Time → Triptych.CaptureMap
  | .alt0 part0 part2 part4 =>
    (Triptych.referenceCaptures qual "hh" (Datetime.Derivation.hh.render part0) ++
        Datetime.Derivation.hh.capturesWith "hh" part0 ++
      ([] ++
        (Triptych.referenceCaptures qual "mm" (Datetime.Derivation.mm.render part2) ++
            Datetime.Derivation.mm.capturesWith "mm" part2 ++
          ([] ++
            (Triptych.referenceCaptures qual "ss" (Datetime.Derivation.ss.render part4) ++
                Datetime.Derivation.ss.capturesWith "ss" part4 ++
              [])))))

instance Datetime.Derivation.SSS.instDecidableValid : DecidablePred Datetime.Derivation.SSS.Valid := fun d => by
  cases d <;> simp only [Datetime.Derivation.SSS.Valid] <;> infer_instance

def Datetime.Derivation.SSS.capturesWith (qual : String) : Datetime.Derivation.SSS → Triptych.CaptureMap
  | .alt0 part0 => ([] ++ [])

instance Datetime.Derivation.Offset.instDecidableValid : DecidablePred Datetime.Derivation.Offset.Valid := fun d => by
  cases d <;> simp only [Datetime.Derivation.Offset.Valid] <;> infer_instance

def Datetime.Derivation.Offset.capturesWith (qual : String) : Datetime.Derivation.Offset → Triptych.CaptureMap
  | .alt0 part1 part2 =>
    ([] ++
      (Triptych.referenceCaptures qual "hh" (Datetime.Derivation.hh.render part1) ++
          Datetime.Derivation.hh.capturesWith "hh" part1 ++
        (Triptych.referenceCaptures qual "mm" (Datetime.Derivation.mm.render part2) ++
            Datetime.Derivation.mm.capturesWith "mm" part2 ++
          [])))
  | .alt1 part1 part2 =>
    ([] ++
      (Triptych.referenceCaptures qual "hh" (Datetime.Derivation.hh.render part1) ++
          Datetime.Derivation.hh.capturesWith "hh" part1 ++
        (Triptych.referenceCaptures qual "mm" (Datetime.Derivation.mm.render part2) ++
            Datetime.Derivation.mm.capturesWith "mm" part2 ++
          [])))

instance Datetime.Derivation.Datetime.instDecidableValid : DecidablePred Datetime.Derivation.Datetime.Valid := fun d =>
  by cases d <;> simp only [Datetime.Derivation.Datetime.Valid] <;> infer_instance

def Datetime.Derivation.Datetime.capturesWith (qual : String) : Datetime.Derivation.Datetime → Triptych.CaptureMap
  | .alt0 part0 =>
    (Triptych.referenceCaptures qual "Date" (Datetime.Derivation.Date.render part0) ++
        Datetime.Derivation.Date.capturesWith "Date" part0 ++
      [])
  | .alt1 part0 part2 =>
    (Triptych.referenceCaptures qual "Date" (Datetime.Derivation.Date.render part0) ++
        Datetime.Derivation.Date.capturesWith "Date" part0 ++
      ([] ++
        (Triptych.referenceCaptures qual "Time" (Datetime.Derivation.Time.render part2) ++
            Datetime.Derivation.Time.capturesWith "Time" part2 ++
          ([] ++ []))))
  | .alt2 part0 part2 part4 =>
    (Triptych.referenceCaptures qual "Date" (Datetime.Derivation.Date.render part0) ++
        Datetime.Derivation.Date.capturesWith "Date" part0 ++
      ([] ++
        (Triptych.referenceCaptures qual "Time" (Datetime.Derivation.Time.render part2) ++
            Datetime.Derivation.Time.capturesWith "Time" part2 ++
          ([] ++
            (Triptych.referenceCaptures qual "SSS" (Datetime.Derivation.SSS.render part4) ++
                Datetime.Derivation.SSS.capturesWith "SSS" part4 ++
              ([] ++ []))))))
  | .alt3 part0 part2 part3 =>
    (Triptych.referenceCaptures qual "Date" (Datetime.Derivation.Date.render part0) ++
        Datetime.Derivation.Date.capturesWith "Date" part0 ++
      ([] ++
        (Triptych.referenceCaptures qual "Time" (Datetime.Derivation.Time.render part2) ++
            Datetime.Derivation.Time.capturesWith "Time" part2 ++
          (Triptych.referenceCaptures qual "Offset" (Datetime.Derivation.Offset.render part3) ++
              Datetime.Derivation.Offset.capturesWith "Offset" part3 ++
            []))))
  | .alt4 part0 part2 part4 part5 =>
    (Triptych.referenceCaptures qual "Date" (Datetime.Derivation.Date.render part0) ++
        Datetime.Derivation.Date.capturesWith "Date" part0 ++
      ([] ++
        (Triptych.referenceCaptures qual "Time" (Datetime.Derivation.Time.render part2) ++
            Datetime.Derivation.Time.capturesWith "Time" part2 ++
          ([] ++
            (Triptych.referenceCaptures qual "SSS" (Datetime.Derivation.SSS.render part4) ++
                Datetime.Derivation.SSS.capturesWith "SSS" part4 ++
              (Triptych.referenceCaptures qual "Offset" (Datetime.Derivation.Offset.render part5) ++
                  Datetime.Derivation.Offset.capturesWith "Offset" part5 ++
                []))))))

def Datetime.valueFn := fun m : Triptych.CaptureMap =>
  epochMillis ((Triptych.CaptureMap.toEnv m "YYYY").getD "") ((Triptych.CaptureMap.toEnv m "MM").getD "")
    ((Triptych.CaptureMap.toEnv m "DD").getD "") ((Triptych.CaptureMap.toEnv m "Time.hh").getD "")
    ((Triptych.CaptureMap.toEnv m "Time.mm").getD "") ((Triptych.CaptureMap.toEnv m "ss").getD "")
    ((Triptych.CaptureMap.toEnv m "SSS").getD "") ((Triptych.CaptureMap.toEnv m "Offset.hh").getD "")
    ((Triptych.CaptureMap.toEnv m "Offset.mm").getD "") ((Triptych.CaptureMap.toEnv m "Offset").getD "")

def Datetime.constraints : List ConstraintEntry :=
  [ConstraintEntry.dsl ConstraintPhase.wellFormed
      (Constraint.and (Constraint.le (ValExpr.lit 1) (ValExpr.nat "MM"))
        (Constraint.le (ValExpr.nat "MM") (ValExpr.lit 12))),
    ConstraintEntry.dsl ConstraintPhase.wellFormed
      (Constraint.and (Constraint.le (ValExpr.lit 0) (ValExpr.nat "Time.hh"))
        (Constraint.le (ValExpr.nat "Time.hh") (ValExpr.lit 23))),
    ConstraintEntry.dsl ConstraintPhase.wellFormed
      (Constraint.and (Constraint.le (ValExpr.lit 0) (ValExpr.nat "Time.mm"))
        (Constraint.le (ValExpr.nat "Time.mm") (ValExpr.lit 59))),
    ConstraintEntry.dsl ConstraintPhase.wellFormed
      (Constraint.and (Constraint.le (ValExpr.lit 0) (ValExpr.nat "ss"))
        (Constraint.le (ValExpr.nat "ss") (ValExpr.lit 59))),
    ConstraintEntry.dsl ConstraintPhase.wellFormed
      (Constraint.and (Constraint.le (ValExpr.lit 0) (ValExpr.nat "Offset.hh"))
        (Constraint.le (ValExpr.nat "Offset.hh") (ValExpr.lit 23))),
    ConstraintEntry.dsl ConstraintPhase.wellFormed
      (Constraint.and (Constraint.le (ValExpr.lit 0) (ValExpr.nat "Offset.mm"))
        (Constraint.le (ValExpr.nat "Offset.mm") (ValExpr.lit 59))),
    ConstraintEntry.opaqueMap ConstraintPhase.wellFormed fun m : Triptych.CaptureMap =>
      dayBound ((Triptych.CaptureMap.toEnv m "YYYY").getD "") ((Triptych.CaptureMap.toEnv m "MM").getD "")
        ((Triptych.CaptureMap.toEnv m "DD").getD "")]

def Datetime.computeValue (s : String) :=
  Triptych.computeValueMap Datetime.grammar Datetime.valueFn s

def Datetime.View.ofMap (input : String) (m : Triptych.CaptureMap) : Datetime.View :=
  Datetime.View.mk input ((Triptych.CaptureMap.toEnv m "YYYY").getD "") ((Triptych.CaptureMap.toEnv m "MM").getD "")
    ((Triptych.CaptureMap.toEnv m "DD").getD "") (Triptych.CaptureMap.toEnv m "Time.hh")
    (Triptych.CaptureMap.toEnv m "Time.mm") (Triptych.CaptureMap.toEnv m "ss") (Triptych.CaptureMap.toEnv m "SSS")
    (Triptych.CaptureMap.toEnv m "Offset.hh") (Triptych.CaptureMap.toEnv m "Offset.mm")
    (Triptych.CaptureMap.toEnv m "Offset")

def Datetime.decodeView (s : String) : Option Datetime.View :=
  (decode Datetime.grammar s).map (Datetime.View.ofMap s)

def Datetime.Derivation.Datetime.toView (d : Datetime.Derivation.Datetime) : Datetime.View :=
  Datetime.View.ofMap (Datetime.Derivation.Datetime.render d) (Datetime.Derivation.Datetime.capturesWith "" d)

/- ════════════════════════════ equivalence ════════════════════════════
The auto-discharged guarantees relating the readable surface to the executable
engine: `IsWfGrammar_equiv` proves grammar-layout agreement and `IsWf_equiv`
proves full well-formedness agreement. `computeValue_eq` proves the values agree,
while `decodeView_input`, `IsValid_view`, and `computeValue_view` expose the typed
parse view. Derived `DecidablePred` instances make the surface predicates executable
via the engine. No `sorry`. -/

theorem Datetime.Derivation.YYYY.matches (qual : String) (fuel : Nat) (d : Datetime.Derivation.YYYY)
    (hvalid : Datetime.Derivation.YYYY.Valid d) :
    Triptych.ProdMatch Datetime.grammar qual (fuel + 1)
      (Production.mk "YYYY" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 4)) false]])
      (Datetime.Derivation.YYYY.render d) (Datetime.Derivation.YYYY.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [Datetime.Derivation.YYYY.Valid] at hvalid
    have hpart0 := hvalid
    simp only [Datetime.Derivation.YYYY.render, Datetime.Derivation.YYYY.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 4)) false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              Triptych.symMatch_term Datetime.grammar qual (fuel + 1) TokClass.digit (LenSpec.exactly 4) part0 hpart0
          · exact Triptych.seqMatch_nil Datetime.grammar qual (fuel + 1))

theorem Datetime.Derivation.MM.matches (qual : String) (fuel : Nat) (d : Datetime.Derivation.MM)
    (hvalid : Datetime.Derivation.MM.Valid d) :
    Triptych.ProdMatch Datetime.grammar qual (fuel + 1)
      (Production.mk "MM" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      (Datetime.Derivation.MM.render d) (Datetime.Derivation.MM.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [Datetime.Derivation.MM.Valid] at hvalid
    have hpart0 := hvalid
    simp only [Datetime.Derivation.MM.render, Datetime.Derivation.MM.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              Triptych.symMatch_term Datetime.grammar qual (fuel + 1) TokClass.digit (LenSpec.exactly 2) part0 hpart0
          · exact Triptych.seqMatch_nil Datetime.grammar qual (fuel + 1))

theorem Datetime.Derivation.DD.matches (qual : String) (fuel : Nat) (d : Datetime.Derivation.DD)
    (hvalid : Datetime.Derivation.DD.Valid d) :
    Triptych.ProdMatch Datetime.grammar qual (fuel + 1)
      (Production.mk "DD" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      (Datetime.Derivation.DD.render d) (Datetime.Derivation.DD.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [Datetime.Derivation.DD.Valid] at hvalid
    have hpart0 := hvalid
    simp only [Datetime.Derivation.DD.render, Datetime.Derivation.DD.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              Triptych.symMatch_term Datetime.grammar qual (fuel + 1) TokClass.digit (LenSpec.exactly 2) part0 hpart0
          · exact Triptych.seqMatch_nil Datetime.grammar qual (fuel + 1))

theorem Datetime.Derivation.Date.matches (qual : String) (fuel : Nat) (d : Datetime.Derivation.Date)
    (hvalid : Datetime.Derivation.Date.Valid d) :
    Triptych.ProdMatch Datetime.grammar qual (fuel + 2)
      (Production.mk "Date"
        [[SymItem.mk (Sym.ref "YYYY") false, SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "MM") false,
            SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "DD") false]])
      (Datetime.Derivation.Date.render d) (Datetime.Derivation.Date.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 part2 part4 =>
    simp only [Datetime.Derivation.Date.Valid] at hvalid
    rcases hvalid with ⟨hpart0, hpart2, hpart4⟩
    simp only [Datetime.Derivation.Date.render, Datetime.Derivation.Date.capturesWith]
    apply
      Triptych.prodMatch_of_alt (alt :=
        [SymItem.mk (Sym.ref "YYYY") false, SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "MM") false,
          SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "DD") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              (by
                simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                  (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 1) "YYYY"
                    (Production.mk "YYYY" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 4)) false]]) (by rfl)
                    (Datetime.Derivation.YYYY.render part0) (Datetime.Derivation.YYYY.capturesWith "YYYY" part0)
                    (Datetime.Derivation.YYYY.matches "YYYY" (fuel + 0) part0 hpart0)))
          ·
            exact
              (by
                apply Triptych.seqMatch_required
                · exact Triptych.symMatch_lit Datetime.grammar qual (fuel + 2) "-"
                ·
                  exact
                    (by
                      apply Triptych.seqMatch_required
                      ·
                        exact
                          (by
                            simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                              (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 1) "MM"
                                (Production.mk "MM" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
                                (by rfl) (Datetime.Derivation.MM.render part2)
                                (Datetime.Derivation.MM.capturesWith "MM" part2)
                                (Datetime.Derivation.MM.matches "MM" (fuel + 0) part2 hpart2)))
                      ·
                        exact
                          (by
                            apply Triptych.seqMatch_required
                            · exact Triptych.symMatch_lit Datetime.grammar qual (fuel + 2) "-"
                            ·
                              exact
                                (by
                                  apply Triptych.seqMatch_required
                                  ·
                                    exact
                                      (by
                                        simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                                          (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 1) "DD"
                                            (Production.mk "DD"
                                              [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
                                            (by rfl) (Datetime.Derivation.DD.render part4)
                                            (Datetime.Derivation.DD.capturesWith "DD" part4)
                                            (Datetime.Derivation.DD.matches "DD" (fuel + 0) part4 hpart4)))
                                  · exact Triptych.seqMatch_nil Datetime.grammar qual (fuel + 2))))))

theorem Datetime.Derivation.hh.matches (qual : String) (fuel : Nat) (d : Datetime.Derivation.hh)
    (hvalid : Datetime.Derivation.hh.Valid d) :
    Triptych.ProdMatch Datetime.grammar qual (fuel + 1)
      (Production.mk "hh" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      (Datetime.Derivation.hh.render d) (Datetime.Derivation.hh.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [Datetime.Derivation.hh.Valid] at hvalid
    have hpart0 := hvalid
    simp only [Datetime.Derivation.hh.render, Datetime.Derivation.hh.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              Triptych.symMatch_term Datetime.grammar qual (fuel + 1) TokClass.digit (LenSpec.exactly 2) part0 hpart0
          · exact Triptych.seqMatch_nil Datetime.grammar qual (fuel + 1))

theorem Datetime.Derivation.mm.matches (qual : String) (fuel : Nat) (d : Datetime.Derivation.mm)
    (hvalid : Datetime.Derivation.mm.Valid d) :
    Triptych.ProdMatch Datetime.grammar qual (fuel + 1)
      (Production.mk "mm" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      (Datetime.Derivation.mm.render d) (Datetime.Derivation.mm.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [Datetime.Derivation.mm.Valid] at hvalid
    have hpart0 := hvalid
    simp only [Datetime.Derivation.mm.render, Datetime.Derivation.mm.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              Triptych.symMatch_term Datetime.grammar qual (fuel + 1) TokClass.digit (LenSpec.exactly 2) part0 hpart0
          · exact Triptych.seqMatch_nil Datetime.grammar qual (fuel + 1))

theorem Datetime.Derivation.ss.matches (qual : String) (fuel : Nat) (d : Datetime.Derivation.ss)
    (hvalid : Datetime.Derivation.ss.Valid d) :
    Triptych.ProdMatch Datetime.grammar qual (fuel + 1)
      (Production.mk "ss" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      (Datetime.Derivation.ss.render d) (Datetime.Derivation.ss.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [Datetime.Derivation.ss.Valid] at hvalid
    have hpart0 := hvalid
    simp only [Datetime.Derivation.ss.render, Datetime.Derivation.ss.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              Triptych.symMatch_term Datetime.grammar qual (fuel + 1) TokClass.digit (LenSpec.exactly 2) part0 hpart0
          · exact Triptych.seqMatch_nil Datetime.grammar qual (fuel + 1))

theorem Datetime.Derivation.Time.matches (qual : String) (fuel : Nat) (d : Datetime.Derivation.Time)
    (hvalid : Datetime.Derivation.Time.Valid d) :
    Triptych.ProdMatch Datetime.grammar qual (fuel + 2)
      (Production.mk "Time"
        [[SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "mm") false,
            SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "ss") false]])
      (Datetime.Derivation.Time.render d) (Datetime.Derivation.Time.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 part2 part4 =>
    simp only [Datetime.Derivation.Time.Valid] at hvalid
    rcases hvalid with ⟨hpart0, hpart2, hpart4⟩
    simp only [Datetime.Derivation.Time.render, Datetime.Derivation.Time.capturesWith]
    apply
      Triptych.prodMatch_of_alt (alt :=
        [SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "mm") false,
          SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "ss") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              (by
                simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                  (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 1) "hh"
                    (Production.mk "hh" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]]) (by rfl)
                    (Datetime.Derivation.hh.render part0) (Datetime.Derivation.hh.capturesWith "hh" part0)
                    (Datetime.Derivation.hh.matches "hh" (fuel + 0) part0 hpart0)))
          ·
            exact
              (by
                apply Triptych.seqMatch_required
                · exact Triptych.symMatch_lit Datetime.grammar qual (fuel + 2) ":"
                ·
                  exact
                    (by
                      apply Triptych.seqMatch_required
                      ·
                        exact
                          (by
                            simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                              (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 1) "mm"
                                (Production.mk "mm" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
                                (by rfl) (Datetime.Derivation.mm.render part2)
                                (Datetime.Derivation.mm.capturesWith "mm" part2)
                                (Datetime.Derivation.mm.matches "mm" (fuel + 0) part2 hpart2)))
                      ·
                        exact
                          (by
                            apply Triptych.seqMatch_required
                            · exact Triptych.symMatch_lit Datetime.grammar qual (fuel + 2) ":"
                            ·
                              exact
                                (by
                                  apply Triptych.seqMatch_required
                                  ·
                                    exact
                                      (by
                                        simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                                          (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 1) "ss"
                                            (Production.mk "ss"
                                              [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
                                            (by rfl) (Datetime.Derivation.ss.render part4)
                                            (Datetime.Derivation.ss.capturesWith "ss" part4)
                                            (Datetime.Derivation.ss.matches "ss" (fuel + 0) part4 hpart4)))
                                  · exact Triptych.seqMatch_nil Datetime.grammar qual (fuel + 2))))))

theorem Datetime.Derivation.SSS.matches (qual : String) (fuel : Nat) (d : Datetime.Derivation.SSS)
    (hvalid : Datetime.Derivation.SSS.Valid d) :
    Triptych.ProdMatch Datetime.grammar qual (fuel + 1)
      (Production.mk "SSS" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 3)) false]])
      (Datetime.Derivation.SSS.render d) (Datetime.Derivation.SSS.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [Datetime.Derivation.SSS.Valid] at hvalid
    have hpart0 := hvalid
    simp only [Datetime.Derivation.SSS.render, Datetime.Derivation.SSS.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 3)) false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              Triptych.symMatch_term Datetime.grammar qual (fuel + 1) TokClass.digit (LenSpec.exactly 3) part0 hpart0
          · exact Triptych.seqMatch_nil Datetime.grammar qual (fuel + 1))

theorem Datetime.Derivation.Offset.matches (qual : String) (fuel : Nat) (d : Datetime.Derivation.Offset)
    (hvalid : Datetime.Derivation.Offset.Valid d) :
    Triptych.ProdMatch Datetime.grammar qual (fuel + 2)
      (Production.mk "Offset"
        [[SymItem.mk (Sym.lit "+") false, SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.ref "mm") false],
          [SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.ref "mm") false]])
      (Datetime.Derivation.Offset.render d) (Datetime.Derivation.Offset.capturesWith qual d) :=
  by
  cases d with
  | alt0 part1 part2 =>
    simp only [Datetime.Derivation.Offset.Valid] at hvalid
    rcases hvalid with ⟨hpart1, hpart2⟩
    simp only [Datetime.Derivation.Offset.render, Datetime.Derivation.Offset.capturesWith]
    apply
      Triptych.prodMatch_of_alt (alt :=
        [SymItem.mk (Sym.lit "+") false, SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.ref "mm") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          · exact Triptych.symMatch_lit Datetime.grammar qual (fuel + 2) "+"
          ·
            exact
              (by
                apply Triptych.seqMatch_required
                ·
                  exact
                    (by
                      simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                        (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 1) "hh"
                          (Production.mk "hh" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
                          (by rfl) (Datetime.Derivation.hh.render part1)
                          (Datetime.Derivation.hh.capturesWith "hh" part1)
                          (Datetime.Derivation.hh.matches "hh" (fuel + 0) part1 hpart1)))
                ·
                  exact
                    (by
                      apply Triptych.seqMatch_required
                      ·
                        exact
                          (by
                            simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                              (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 1) "mm"
                                (Production.mk "mm" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
                                (by rfl) (Datetime.Derivation.mm.render part2)
                                (Datetime.Derivation.mm.capturesWith "mm" part2)
                                (Datetime.Derivation.mm.matches "mm" (fuel + 0) part2 hpart2)))
                      · exact Triptych.seqMatch_nil Datetime.grammar qual (fuel + 2))))
  | alt1 part1 part2 =>
    simp only [Datetime.Derivation.Offset.Valid] at hvalid
    rcases hvalid with ⟨hpart1, hpart2⟩
    simp only [Datetime.Derivation.Offset.render, Datetime.Derivation.Offset.capturesWith]
    apply
      Triptych.prodMatch_of_alt (alt :=
        [SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.ref "mm") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          · exact Triptych.symMatch_lit Datetime.grammar qual (fuel + 2) "-"
          ·
            exact
              (by
                apply Triptych.seqMatch_required
                ·
                  exact
                    (by
                      simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                        (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 1) "hh"
                          (Production.mk "hh" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
                          (by rfl) (Datetime.Derivation.hh.render part1)
                          (Datetime.Derivation.hh.capturesWith "hh" part1)
                          (Datetime.Derivation.hh.matches "hh" (fuel + 0) part1 hpart1)))
                ·
                  exact
                    (by
                      apply Triptych.seqMatch_required
                      ·
                        exact
                          (by
                            simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                              (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 1) "mm"
                                (Production.mk "mm" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
                                (by rfl) (Datetime.Derivation.mm.render part2)
                                (Datetime.Derivation.mm.capturesWith "mm" part2)
                                (Datetime.Derivation.mm.matches "mm" (fuel + 0) part2 hpart2)))
                      · exact Triptych.seqMatch_nil Datetime.grammar qual (fuel + 2))))

theorem Datetime.Derivation.Datetime.matches (qual : String) (fuel : Nat) (d : Datetime.Derivation.Datetime)
    (hvalid : Datetime.Derivation.Datetime.Valid d) :
    Triptych.ProdMatch Datetime.grammar qual (fuel + 3)
      (Production.mk "Datetime"
        [[SymItem.mk (Sym.ref "Date") false],
          [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
            SymItem.mk (Sym.lit "Z") false],
          [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
            SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
          [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
            SymItem.mk (Sym.ref "Offset") false],
          [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
            SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false]])
      (Datetime.Derivation.Datetime.render d) (Datetime.Derivation.Datetime.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [Datetime.Derivation.Datetime.Valid] at hvalid
    have hpart0 := hvalid
    simp only [Datetime.Derivation.Datetime.render, Datetime.Derivation.Datetime.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.ref "Date") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              (by
                simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                  (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 2) "Date"
                    (Production.mk "Date"
                      [[SymItem.mk (Sym.ref "YYYY") false, SymItem.mk (Sym.lit "-") false,
                          SymItem.mk (Sym.ref "MM") false, SymItem.mk (Sym.lit "-") false,
                          SymItem.mk (Sym.ref "DD") false]])
                    (by rfl) (Datetime.Derivation.Date.render part0)
                    (Datetime.Derivation.Date.capturesWith "Date" part0)
                    (Datetime.Derivation.Date.matches "Date" (fuel + 0) part0 hpart0)))
          · exact Triptych.seqMatch_nil Datetime.grammar qual (fuel + 3))
  | alt1 part0 part2 =>
    simp only [Datetime.Derivation.Datetime.Valid] at hvalid
    rcases hvalid with ⟨hpart0, hpart2⟩
    simp only [Datetime.Derivation.Datetime.render, Datetime.Derivation.Datetime.capturesWith]
    apply
      Triptych.prodMatch_of_alt (alt :=
        [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
          SymItem.mk (Sym.lit "Z") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              (by
                simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                  (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 2) "Date"
                    (Production.mk "Date"
                      [[SymItem.mk (Sym.ref "YYYY") false, SymItem.mk (Sym.lit "-") false,
                          SymItem.mk (Sym.ref "MM") false, SymItem.mk (Sym.lit "-") false,
                          SymItem.mk (Sym.ref "DD") false]])
                    (by rfl) (Datetime.Derivation.Date.render part0)
                    (Datetime.Derivation.Date.capturesWith "Date" part0)
                    (Datetime.Derivation.Date.matches "Date" (fuel + 0) part0 hpart0)))
          ·
            exact
              (by
                apply Triptych.seqMatch_required
                · exact Triptych.symMatch_lit Datetime.grammar qual (fuel + 3) "T"
                ·
                  exact
                    (by
                      apply Triptych.seqMatch_required
                      ·
                        exact
                          (by
                            simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                              (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 2) "Time"
                                (Production.mk "Time"
                                  [[SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.lit ":") false,
                                      SymItem.mk (Sym.ref "mm") false, SymItem.mk (Sym.lit ":") false,
                                      SymItem.mk (Sym.ref "ss") false]])
                                (by rfl) (Datetime.Derivation.Time.render part2)
                                (Datetime.Derivation.Time.capturesWith "Time" part2)
                                (Datetime.Derivation.Time.matches "Time" (fuel + 0) part2 hpart2)))
                      ·
                        exact
                          (by
                            apply Triptych.seqMatch_required
                            · exact Triptych.symMatch_lit Datetime.grammar qual (fuel + 3) "Z"
                            · exact Triptych.seqMatch_nil Datetime.grammar qual (fuel + 3)))))
  | alt2 part0 part2 part4 =>
    simp only [Datetime.Derivation.Datetime.Valid] at hvalid
    rcases hvalid with ⟨hpart0, hpart2, hpart4⟩
    simp only [Datetime.Derivation.Datetime.render, Datetime.Derivation.Datetime.capturesWith]
    apply
      Triptych.prodMatch_of_alt (alt :=
        [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
          SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              (by
                simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                  (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 2) "Date"
                    (Production.mk "Date"
                      [[SymItem.mk (Sym.ref "YYYY") false, SymItem.mk (Sym.lit "-") false,
                          SymItem.mk (Sym.ref "MM") false, SymItem.mk (Sym.lit "-") false,
                          SymItem.mk (Sym.ref "DD") false]])
                    (by rfl) (Datetime.Derivation.Date.render part0)
                    (Datetime.Derivation.Date.capturesWith "Date" part0)
                    (Datetime.Derivation.Date.matches "Date" (fuel + 0) part0 hpart0)))
          ·
            exact
              (by
                apply Triptych.seqMatch_required
                · exact Triptych.symMatch_lit Datetime.grammar qual (fuel + 3) "T"
                ·
                  exact
                    (by
                      apply Triptych.seqMatch_required
                      ·
                        exact
                          (by
                            simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                              (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 2) "Time"
                                (Production.mk "Time"
                                  [[SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.lit ":") false,
                                      SymItem.mk (Sym.ref "mm") false, SymItem.mk (Sym.lit ":") false,
                                      SymItem.mk (Sym.ref "ss") false]])
                                (by rfl) (Datetime.Derivation.Time.render part2)
                                (Datetime.Derivation.Time.capturesWith "Time" part2)
                                (Datetime.Derivation.Time.matches "Time" (fuel + 0) part2 hpart2)))
                      ·
                        exact
                          (by
                            apply Triptych.seqMatch_required
                            · exact Triptych.symMatch_lit Datetime.grammar qual (fuel + 3) "."
                            ·
                              exact
                                (by
                                  apply Triptych.seqMatch_required
                                  ·
                                    exact
                                      (by
                                        simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                                          (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 1)) + 1) "SSS"
                                            (Production.mk "SSS"
                                              [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 3)) false]])
                                            (by rfl) (Datetime.Derivation.SSS.render part4)
                                            (Datetime.Derivation.SSS.capturesWith "SSS" part4)
                                            (Datetime.Derivation.SSS.matches "SSS" (fuel + 1) part4 hpart4)))
                                  ·
                                    exact
                                      (by
                                        apply Triptych.seqMatch_required
                                        · exact Triptych.symMatch_lit Datetime.grammar qual (fuel + 3) "Z"
                                        · exact Triptych.seqMatch_nil Datetime.grammar qual (fuel + 3)))))))
  | alt3 part0 part2 part3 =>
    simp only [Datetime.Derivation.Datetime.Valid] at hvalid
    rcases hvalid with ⟨hpart0, hpart2, hpart3⟩
    simp only [Datetime.Derivation.Datetime.render, Datetime.Derivation.Datetime.capturesWith]
    apply
      Triptych.prodMatch_of_alt (alt :=
        [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
          SymItem.mk (Sym.ref "Offset") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              (by
                simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                  (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 2) "Date"
                    (Production.mk "Date"
                      [[SymItem.mk (Sym.ref "YYYY") false, SymItem.mk (Sym.lit "-") false,
                          SymItem.mk (Sym.ref "MM") false, SymItem.mk (Sym.lit "-") false,
                          SymItem.mk (Sym.ref "DD") false]])
                    (by rfl) (Datetime.Derivation.Date.render part0)
                    (Datetime.Derivation.Date.capturesWith "Date" part0)
                    (Datetime.Derivation.Date.matches "Date" (fuel + 0) part0 hpart0)))
          ·
            exact
              (by
                apply Triptych.seqMatch_required
                · exact Triptych.symMatch_lit Datetime.grammar qual (fuel + 3) "T"
                ·
                  exact
                    (by
                      apply Triptych.seqMatch_required
                      ·
                        exact
                          (by
                            simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                              (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 2) "Time"
                                (Production.mk "Time"
                                  [[SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.lit ":") false,
                                      SymItem.mk (Sym.ref "mm") false, SymItem.mk (Sym.lit ":") false,
                                      SymItem.mk (Sym.ref "ss") false]])
                                (by rfl) (Datetime.Derivation.Time.render part2)
                                (Datetime.Derivation.Time.capturesWith "Time" part2)
                                (Datetime.Derivation.Time.matches "Time" (fuel + 0) part2 hpart2)))
                      ·
                        exact
                          (by
                            apply Triptych.seqMatch_required
                            ·
                              exact
                                (by
                                  simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                                    (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 2) "Offset"
                                      (Production.mk "Offset"
                                        [[SymItem.mk (Sym.lit "+") false, SymItem.mk (Sym.ref "hh") false,
                                            SymItem.mk (Sym.ref "mm") false],
                                          [SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "hh") false,
                                            SymItem.mk (Sym.ref "mm") false]])
                                      (by rfl) (Datetime.Derivation.Offset.render part3)
                                      (Datetime.Derivation.Offset.capturesWith "Offset" part3)
                                      (Datetime.Derivation.Offset.matches "Offset" (fuel + 0) part3 hpart3)))
                            · exact Triptych.seqMatch_nil Datetime.grammar qual (fuel + 3)))))
  | alt4 part0 part2 part4
    part5 =>
    simp only [Datetime.Derivation.Datetime.Valid] at hvalid
    rcases hvalid with ⟨hpart0, hpart2, hpart4, hpart5⟩
    simp only [Datetime.Derivation.Datetime.render, Datetime.Derivation.Datetime.capturesWith]
    apply
      Triptych.prodMatch_of_alt (alt :=
        [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
          SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              (by
                simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                  (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 2) "Date"
                    (Production.mk "Date"
                      [[SymItem.mk (Sym.ref "YYYY") false, SymItem.mk (Sym.lit "-") false,
                          SymItem.mk (Sym.ref "MM") false, SymItem.mk (Sym.lit "-") false,
                          SymItem.mk (Sym.ref "DD") false]])
                    (by rfl) (Datetime.Derivation.Date.render part0)
                    (Datetime.Derivation.Date.capturesWith "Date" part0)
                    (Datetime.Derivation.Date.matches "Date" (fuel + 0) part0 hpart0)))
          ·
            exact
              (by
                apply Triptych.seqMatch_required
                · exact Triptych.symMatch_lit Datetime.grammar qual (fuel + 3) "T"
                ·
                  exact
                    (by
                      apply Triptych.seqMatch_required
                      ·
                        exact
                          (by
                            simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                              (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 2) "Time"
                                (Production.mk "Time"
                                  [[SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.lit ":") false,
                                      SymItem.mk (Sym.ref "mm") false, SymItem.mk (Sym.lit ":") false,
                                      SymItem.mk (Sym.ref "ss") false]])
                                (by rfl) (Datetime.Derivation.Time.render part2)
                                (Datetime.Derivation.Time.capturesWith "Time" part2)
                                (Datetime.Derivation.Time.matches "Time" (fuel + 0) part2 hpart2)))
                      ·
                        exact
                          (by
                            apply Triptych.seqMatch_required
                            · exact Triptych.symMatch_lit Datetime.grammar qual (fuel + 3) "."
                            ·
                              exact
                                (by
                                  apply Triptych.seqMatch_required
                                  ·
                                    exact
                                      (by
                                        simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                                          (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 1)) + 1) "SSS"
                                            (Production.mk "SSS"
                                              [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 3)) false]])
                                            (by rfl) (Datetime.Derivation.SSS.render part4)
                                            (Datetime.Derivation.SSS.capturesWith "SSS" part4)
                                            (Datetime.Derivation.SSS.matches "SSS" (fuel + 1) part4 hpart4)))
                                  ·
                                    exact
                                      (by
                                        apply Triptych.seqMatch_required
                                        ·
                                          exact
                                            (by
                                              simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                                                (Triptych.symMatch_ref Datetime.grammar qual (((fuel + 0)) + 2) "Offset"
                                                  (Production.mk "Offset"
                                                    [[SymItem.mk (Sym.lit "+") false, SymItem.mk (Sym.ref "hh") false,
                                                        SymItem.mk (Sym.ref "mm") false],
                                                      [SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "hh") false,
                                                        SymItem.mk (Sym.ref "mm") false]])
                                                  (by rfl) (Datetime.Derivation.Offset.render part5)
                                                  (Datetime.Derivation.Offset.capturesWith "Offset" part5)
                                                  (Datetime.Derivation.Offset.matches "Offset" (fuel + 0) part5
                                                    hpart5)))
                                        · exact Triptych.seqMatch_nil Datetime.grammar qual (fuel + 3)))))))

theorem Datetime.Derivation.Datetime.mem_fullParses (d : Datetime.Derivation.Datetime)
    (hvalid : Datetime.Derivation.Datetime.Valid d) :
    Datetime.Derivation.Datetime.capturesWith "" d ∈
      Triptych.fullParses Datetime.grammar (Datetime.Derivation.Datetime.render d) :=
  by
  apply
    Triptych.prodMatch_mem_fullParses Datetime.grammar
      (Production.mk "Datetime"
        [[SymItem.mk (Sym.ref "Date") false],
          [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
            SymItem.mk (Sym.lit "Z") false],
          [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
            SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
          [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
            SymItem.mk (Sym.ref "Offset") false],
          [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
            SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false]])
      (by rfl)
  simpa [Datetime.grammar] using (Datetime.Derivation.Datetime.matches "" 8 d hvalid)

theorem Datetime.Derivation.Datetime.decode_render_of_captureFunctional
    (hfunctional : Triptych.GrammarCaptureFunctional Datetime.grammar) (d : Datetime.Derivation.Datetime)
    (hvalid : Datetime.Derivation.Datetime.Valid d) :
    Triptych.decode Datetime.grammar (Datetime.Derivation.Datetime.render d) =
      some (Datetime.Derivation.Datetime.capturesWith "" d) :=
  Triptych.decode_eq_of_mem_fullParses hfunctional (mem_fullParses d hvalid)

theorem Datetime.decodeView_input {s : String} {v : Datetime.View} (h : Datetime.decodeView s = some v) :
    Datetime.View.input v = s := by
  unfold Datetime.decodeView at h
  rw [Option.map_eq_some_iff] at h
  obtain ⟨m, _, hv⟩ := h
  subst v
  rfl

theorem Datetime.Derivation.Datetime.decodeView_render_of_captureFunctional
    (hfunctional : Triptych.GrammarCaptureFunctional Datetime.grammar) (d : Datetime.Derivation.Datetime)
    (hvalid : Datetime.Derivation.Datetime.Valid d) :
    Datetime.decodeView (Datetime.Derivation.Datetime.render d) = some (Datetime.Derivation.Datetime.toView d) :=
  by
  unfold Datetime.decodeView Datetime.Derivation.Datetime.toView
  rw [Datetime.Derivation.Datetime.decode_render_of_captureFunctional hfunctional d hvalid]
  rfl

theorem Datetime.SatisfiesWfConstraints_of_decode {s : String} {m : Triptych.CaptureMap}
    (h : decode Datetime.grammar s = some m) :
    Datetime.SatisfiesWfConstraints s ↔
      Datetime.WfConstraints ((Triptych.CaptureMap.toEnv m "MM").getD "")
        ((Triptych.CaptureMap.toEnv m "Time.hh").getD "") ((Triptych.CaptureMap.toEnv m "Time.mm").getD "")
        ((Triptych.CaptureMap.toEnv m "ss").getD "") ((Triptych.CaptureMap.toEnv m "Offset.hh").getD "")
        ((Triptych.CaptureMap.toEnv m "Offset.mm").getD "") ((Triptych.CaptureMap.toEnv m "YYYY").getD "")
        ((Triptych.CaptureMap.toEnv m "DD").getD "") :=
  by
  unfold Datetime.SatisfiesWfConstraints
  simp only [Triptych.component_eq_of_decode h "MM", Triptych.component_eq_of_decode h "Time.hh",
    Triptych.component_eq_of_decode h "Time.mm", Triptych.component_eq_of_decode h "ss",
    Triptych.component_eq_of_decode h "Offset.hh", Triptych.component_eq_of_decode h "Offset.mm",
    Triptych.component_eq_of_decode h "YYYY", Triptych.component_eq_of_decode h "DD"]

theorem Datetime.Internal.matchesRef.YYYY (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "YYYY") s ↔ Datetime.IsWf.YYYY s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "YYYY" =
        some (Production.mk "YYYY" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 4)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.YYYY
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.MM (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "MM") s ↔ Datetime.IsWf.MM s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "MM" =
        some (Production.mk "MM" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.MM
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.DD (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "DD") s ↔ Datetime.IsWf.DD s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "DD" =
        some (Production.mk "DD" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.DD
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.Date (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 2) (Sym.ref "Date") s ↔ Datetime.IsWf.Date s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "Date" =
        some
          (Production.mk "Date"
            [[SymItem.mk (Sym.ref "YYYY") false, SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "MM") false,
                SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "DD") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.Date
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym,
    Datetime.Internal.matchesRef.YYYY, Datetime.Internal.matchesRef.MM, Datetime.Internal.matchesRef.DD]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.hh (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "hh") s ↔ Datetime.IsWf.hh s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "hh" =
        some (Production.mk "hh" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.hh
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.mm (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "mm") s ↔ Datetime.IsWf.mm s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "mm" =
        some (Production.mk "mm" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.mm
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.ss (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "ss") s ↔ Datetime.IsWf.ss s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "ss" =
        some (Production.mk "ss" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.ss
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.Time (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 2) (Sym.ref "Time") s ↔ Datetime.IsWf.Time s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "Time" =
        some
          (Production.mk "Time"
            [[SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "mm") false,
                SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "ss") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.Time
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym,
    Datetime.Internal.matchesRef.hh, Datetime.Internal.matchesRef.mm, Datetime.Internal.matchesRef.ss]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.SSS (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 1) (Sym.ref "SSS") s ↔ Datetime.IsWf.SSS s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "SSS" =
        some (Production.mk "SSS" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 3)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Datetime.IsWf.SSS
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Datetime.Internal.matchesRef.Offset (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 2) (Sym.ref "Offset") s ↔ Datetime.IsWf.Offset s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "Offset" =
        some
          (Production.mk "Offset"
            [[SymItem.mk (Sym.lit "+") false, SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.ref "mm") false],
              [SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.ref "mm") false]])
      from rfl]
  dsimp only
  unfold matchesProd Datetime.IsWf.Offset
  simp (config := { maxSteps := 1000000 }) only [List.mem_cons, List.mem_singleton, List.not_mem_nil,
    Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_or_imp, exists_eq_left, exists_eq_left, if_true,
    if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, Datetime.Internal.matchesRef.hh,
    Datetime.Internal.matchesRef.mm]
  repeat'
    first
    | apply or_congr
    | ( simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left,
          ← and_assoc, exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
        try grind [String.append_assoc, String.append_empty])

theorem Datetime.Internal.matchesRef.Datetime (fuel : Nat) (s : String) :
    matchesSym Datetime.grammar (fuel + 3) (Sym.ref "Datetime") s ↔ Datetime.IsWf.Datetime s :=
  by
  rw [matchesSym,
    show
      (Datetime.grammar).prod? "Datetime" =
        some
          (Production.mk "Datetime"
            [[SymItem.mk (Sym.ref "Date") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.ref "Offset") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false]])
      from rfl]
  dsimp only
  unfold matchesProd Datetime.IsWf.Datetime
  simp (config := { maxSteps := 1000000 }) only [List.mem_cons, List.mem_singleton, List.not_mem_nil,
    Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_or_imp, exists_eq_left, exists_eq_left, if_true,
    if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, Datetime.Internal.matchesRef.Date,
    Datetime.Internal.matchesRef.Time, Datetime.Internal.matchesRef.SSS, Datetime.Internal.matchesRef.Offset]
  repeat'
    first
    | apply or_congr
    | ( simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left,
          ← and_assoc, exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
        try grind [String.append_assoc, String.append_empty])

theorem Datetime.IsWfGrammar_equiv (s : String) : Triptych.IsWf Datetime.grammar s ↔ Datetime.IsWf.Datetime s :=
  by
  rw [isWf_eq_isWfProd_start, IsWfProd,
    show
      (Datetime.grammar).prod? (Datetime.grammar).start =
        some
          (Production.mk "Datetime"
            [[SymItem.mk (Sym.ref "Date") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.ref "Offset") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false]])
      from rfl]
  have hstart :
    ∀ n,
      matchesProd Datetime.grammar n
          (Production.mk "Datetime"
            [[SymItem.mk (Sym.ref "Date") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.ref "Offset") false],
              [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false]])
          s =
        matchesSym Datetime.grammar (n + 1) (Sym.ref "Datetime") s :=
    by
    intro n
    rw [matchesSym,
      show
        (Datetime.grammar).prod? "Datetime" =
          some
            (Production.mk "Datetime"
              [[SymItem.mk (Sym.ref "Date") false],
                [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                  SymItem.mk (Sym.lit "Z") false],
                [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                  SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
                [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                  SymItem.mk (Sym.ref "Offset") false],
                [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
                  SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false,
                  SymItem.mk (Sym.ref "Offset") false]])
        from rfl]
  show
    matchesProd Datetime.grammar (Datetime.grammar).prods.length
        (Production.mk "Datetime"
          [[SymItem.mk (Sym.ref "Date") false],
            [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
              SymItem.mk (Sym.lit "Z") false],
            [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
              SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
            [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
              SymItem.mk (Sym.ref "Offset") false],
            [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
              SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false]])
        s ↔
      _
  rw [hstart]
  exact Datetime.Internal.matchesRef.Datetime _ s

theorem Datetime.IsWf_equiv (s : String) : Datetime.IsWf s ↔ Triptych.isWf Datetime.grammar Datetime.constraints s :=
  by
  unfold Datetime.IsWf Triptych.isWf
  rw [← Datetime.IsWfGrammar_equiv, ← decodeSome_iff_IsWf Datetime.grammar (by decide)]
  unfold Datetime.SatisfiesWfConstraints Datetime.WfConstraints Datetime.constraints
  simp only [Triptych.component, Triptych.componentList, Triptych.envOf, Triptych.captureMapOf, List.forall_mem_cons,
    List.forall_mem_singleton, List.not_mem_nil, forall_const, ConstraintEntry.wfPart, Constraint.eval, ValExpr.eval,
    presentCount, natOf_getD, intOf_getD, lenOf_getD, countOf_getD, signOf_getD, Env.countVal, and_true, true_and,
    false_implies, implies_true, Bool.false_eq_true]
  try grind

theorem Datetime.IsValid_equiv (s : String) :
    Datetime.IsValid s ↔
      Triptych.isWf Datetime.grammar Datetime.constraints s ∧
        Triptych.satisfiesConstraints Datetime.grammar Datetime.constraints s :=
  by
  unfold Datetime.IsValid
  rw [(Datetime.IsWf_equiv s)]
  unfold Triptych.satisfiesConstraints Triptych.captureMapOf Datetime.constraints
  simp only [List.forall_mem_cons, List.forall_mem_singleton, List.not_mem_nil, ConstraintEntry.valPart, false_implies,
    true_and, and_true]
  constructor
  · intro h
    exact ⟨h, fun _ => True.intro⟩
  · exact And.left

instance Datetime.instDecidableGrammar : DecidablePred Datetime.IsWf.Datetime := fun s =>
  @decidable_of_iff _ _ (Datetime.IsWfGrammar_equiv s) (Triptych.decIsWf Datetime.grammar (by decide) s)

instance Datetime.instDecidableIsWf : DecidablePred Datetime.IsWf := fun s =>
  @decidable_of_iff _ _ (Datetime.IsWf_equiv s).symm inferInstance

instance Datetime.instDecidableIsValid : DecidablePred Datetime.IsValid := fun s => inferInstance

theorem Datetime.View.wfConstraints_of_decode {s : String} {m : Triptych.CaptureMap}
    (h : decode Datetime.grammar s = some m) :
    Datetime.SatisfiesWfConstraints s ↔ Datetime.View.WfConstraints (Datetime.View.ofMap s m) :=
  by
  rw [Datetime.SatisfiesWfConstraints_of_decode h]
  rfl

theorem Datetime.IsValid_view (s : String) :
    Datetime.IsValid s ↔ ∃ v : Datetime.View, Datetime.decodeView s = some v ∧ Datetime.View.Valid v :=
  by
  constructor
  · intro hvalid
    have hengine := (Datetime.IsValid_equiv s).mp hvalid
    have hsome : (decode Datetime.grammar s).isSome = true := by exact hengine.1.1
    obtain ⟨m, hm⟩ := Option.isSome_iff_exists.mp hsome
    refine ⟨Datetime.View.ofMap s m, ?_, ?_⟩
    · unfold Datetime.decodeView
      simp [hm]
    · exact (Datetime.View.wfConstraints_of_decode hm).mp hvalid.2
  · rintro ⟨v, hview, hvalid⟩
    unfold Datetime.decodeView at hview
    rw [Option.map_eq_some_iff] at hview
    obtain ⟨m, hm, hv⟩ := hview
    subst v
    have hdecoded : (decode Datetime.grammar s).isSome = true := by simp [hm]
    have hgrammar :=
      (Datetime.IsWfGrammar_equiv s).mp ((decodeSome_iff_IsWf Datetime.grammar (by decide) s).mp hdecoded)
    exact ⟨hgrammar, (Datetime.View.wfConstraints_of_decode hm).mpr hvalid⟩

theorem Datetime.computeValue_eq (s : String) :
    Datetime.computeValue s =
      (decode Datetime.grammar s).map
        (fun _ =>
          Datetime.value (Triptych.component Datetime.grammar s "YYYY") (Triptych.component Datetime.grammar s "MM")
            (Triptych.component Datetime.grammar s "DD") (Triptych.component Datetime.grammar s "Time.hh")
            (Triptych.component Datetime.grammar s "Time.mm") (Triptych.component Datetime.grammar s "ss")
            (Triptych.component Datetime.grammar s "SSS") (Triptych.component Datetime.grammar s "Offset.hh")
            (Triptych.component Datetime.grammar s "Offset.mm") (Triptych.component Datetime.grammar s "Offset")) :=
  by
  unfold Datetime.computeValue Triptych.computeValueMap Triptych.component Triptych.envOf Triptych.captureMapOf
    Datetime.value Datetime.valueFn
  cases h : decode Datetime.grammar s with
  | none => simp
  | some m => simp [natOf_getD, intOf_getD, lenOf_getD, countOf_getD, signOf_getD, Env.countVal, ValExpr.eval]

theorem Datetime.computeValue_of_decode {s : String} {m : Triptych.CaptureMap}
    (h : decode Datetime.grammar s = some m) :
    Datetime.computeValue s =
      some
        (Datetime.value ((Triptych.CaptureMap.toEnv m "YYYY").getD "") ((Triptych.CaptureMap.toEnv m "MM").getD "")
          ((Triptych.CaptureMap.toEnv m "DD").getD "") ((Triptych.CaptureMap.toEnv m "Time.hh").getD "")
          ((Triptych.CaptureMap.toEnv m "Time.mm").getD "") ((Triptych.CaptureMap.toEnv m "ss").getD "")
          ((Triptych.CaptureMap.toEnv m "SSS").getD "") ((Triptych.CaptureMap.toEnv m "Offset.hh").getD "")
          ((Triptych.CaptureMap.toEnv m "Offset.mm").getD "") ((Triptych.CaptureMap.toEnv m "Offset").getD "")) :=
  by
  rw [Datetime.computeValue_eq, h]
  simp only [Option.map_some, Triptych.component_eq_of_decode h "YYYY", Triptych.component_eq_of_decode h "MM",
    Triptych.component_eq_of_decode h "DD", Triptych.component_eq_of_decode h "Time.hh",
    Triptych.component_eq_of_decode h "Time.mm", Triptych.component_eq_of_decode h "ss",
    Triptych.component_eq_of_decode h "SSS", Triptych.component_eq_of_decode h "Offset.hh",
    Triptych.component_eq_of_decode h "Offset.mm", Triptych.component_eq_of_decode h "Offset"]

theorem Datetime.computeValue_view (s : String) :
    Datetime.computeValue s = (Datetime.decodeView s).map Datetime.View.denotation :=
  by
  unfold Datetime.decodeView
  cases h : decode Datetime.grammar s with
  |
    none =>
    rw [show Datetime.computeValue s = none by
        rw [Datetime.computeValue_eq, h]
        rfl]
    rfl
  | some m =>
    rw [Datetime.computeValue_of_decode h]
    simp only [Option.map_some]
    rfl

/- ═══════════════════════════════ parser ══════════════════════════════
The generated correct-by-construction parser `parse` (= `computeValue` gated on the
decidable `IsValid`) together with its guarantees — `parse_sound`, `parse_complete`,
`parse_reject`, `parse_view`, and typed `parse_eq_some_iff_view` /
`parse_eq_none_iff_view` normal forms — all AUTO-DISCHARGED here.
When an external parser is declared, `checkedExtParse` additionally validates each
external result against this parser and ships an AUTO-DISCHARGED soundness theorem.
A verified parser, no `sorry`. -/

theorem Datetime.computeValue_isSome (s : String) : Datetime.IsValid s → (Datetime.computeValue s).isSome :=
  by
  intro h
  have hengine := (Datetime.IsValid_equiv s).mp h
  unfold Triptych.isWf at hengine
  unfold Datetime.computeValue Triptych.computeValueMap
  rw [Option.isSome_map]
  exact hengine.1.1

def Datetime.parse (s : String) :=
  Triptych.gatedParseOfSpec Datetime.IsValid Datetime.computeValue millisToDatetime s

theorem Datetime.parse_sound (s : String) (d : Cedar.Spec.Ext.Datetime) :
    Datetime.parse s = some d → Datetime.IsValid s ∧ (Datetime.computeValue s).map millisToDatetime = some d :=
  Triptych.gatedParseOfSpec_sound _ _ _ s d

theorem Datetime.parse_complete (s : String) (d : Cedar.Spec.Ext.Datetime) :
    Datetime.IsValid s → (Datetime.computeValue s).map millisToDatetime = some d → Datetime.parse s = some d :=
  Triptych.gatedParseOfSpec_complete _ _ _ s d

theorem Datetime.parse_reject (s : String) : Datetime.parse s = none ↔ ¬Datetime.IsValid s :=
  Triptych.gatedParseOfSpec_reject _ _ _ Datetime.computeValue_isSome s

theorem Datetime.parse_view (s : String) :
    Datetime.parse s =
      if decide (Datetime.IsValid s) then (Datetime.decodeView s).map (millisToDatetime ∘ Datetime.View.denotation)
      else none :=
  by
  unfold Datetime.parse Triptych.gatedParseOfSpec Triptych.gatedParse
  rw [Datetime.computeValue_view]
  split <;> simp [Option.map_map]

theorem Datetime.parse_eq_some_iff_view (s : String) (d : Cedar.Spec.Ext.Datetime) :
    Datetime.parse s = some d ↔
      ∃ decodedView : Datetime.View,
        Datetime.decodeView s = some decodedView ∧
          Datetime.View.Valid decodedView ∧ millisToDatetime (Datetime.View.denotation decodedView) = d :=
  by
  constructor
  · intro hparse
    obtain ⟨hvalid, hvalue⟩ := Datetime.parse_sound s d hparse
    obtain ⟨decodedView, hview, hvalidView⟩ := (Datetime.IsValid_view s).mp hvalid
    refine ⟨decodedView, hview, hvalidView, ?_⟩
    rw [Datetime.computeValue_view, hview] at hvalue
    simpa using Option.some.inj hvalue
  · rintro ⟨decodedView, hview, hvalidView, hvalue⟩
    apply Datetime.parse_complete s d
    · exact (Datetime.IsValid_view s).mpr ⟨decodedView, hview, hvalidView⟩
    · rw [Datetime.computeValue_view, hview]
      simpa using congrArg some hvalue

theorem Datetime.parse_eq_none_iff_view (s : String) :
    Datetime.parse s = none ↔ ¬∃ v : Datetime.View, Datetime.decodeView s = some v ∧ Datetime.View.Valid v :=
  by
  rw [Datetime.parse_reject]
  constructor
  · intro hinvalid ⟨v, hview, hvalidView⟩
    exact hinvalid ((Datetime.IsValid_view s).mpr ⟨v, hview, hvalidView⟩)
  · intro hnoview hvalid
    exact hnoview ((Datetime.IsValid_view s).mp hvalid)

def Datetime.checkedExtParse (s : String) : Option Cedar.Spec.Ext.Datetime :=
  Triptych.checkedExternalParse Datetime.IsValid Datetime.computeValue Cedar.Spec.Ext.Datetime.parse datetimeMillis s

theorem Datetime.checkedExtParse_eq_some_iff (s : String) (d : Cedar.Spec.Ext.Datetime) :
    Datetime.checkedExtParse s = some d ↔
      Cedar.Spec.Ext.Datetime.parse s = some d ∧
        Datetime.IsValid s ∧ Datetime.computeValue s = some (datetimeMillis d) :=
  Triptych.checkedExternalParse_eq_some_iff Datetime.IsValid Datetime.computeValue Cedar.Spec.Ext.Datetime.parse
    datetimeMillis s d

theorem Datetime.checkedExtParse_sound (s : String) (d : Cedar.Spec.Ext.Datetime) :
    Datetime.checkedExtParse s = some d → Datetime.IsValid s ∧ Datetime.computeValue s = some (datetimeMillis d) :=
  Triptych.checkedExternalParse_sound Datetime.IsValid Datetime.computeValue Cedar.Spec.Ext.Datetime.parse
    datetimeMillis s d

theorem Datetime.checkedExtParse_sound_view (s : String) (d : Cedar.Spec.Ext.Datetime) :
    Datetime.checkedExtParse s = some d →
      ∃ v : Datetime.View,
        Datetime.decodeView s = some v ∧ Datetime.View.Valid v ∧ Datetime.View.denotation v = datetimeMillis d :=
  by
  intro hparse
  obtain ⟨hvalid, hvalue⟩ := Datetime.checkedExtParse_sound s d hparse
  obtain ⟨v, hview, hvalidView⟩ := (Datetime.IsValid_view s).mp hvalid
  refine ⟨v, hview, hvalidView, ?_⟩
  rw [Datetime.computeValue_view, hview] at hvalue
  exact Option.some.inj hvalue
