/- Generated by Triptych from `triptych Datetime`. -/

import Triptych.Architecture.Denote
import Triptych.Architecture.Derivation
import Triptych.Architecture.Value
import Triptych.Architecture.Constraint
import Triptych.Architecture.Assemble
import Triptych.Theorems.Reconcile
import Triptych.Theorems.Value
import Inputs.Datetime

open Triptych
open CedarExamples.Datetime

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ═══════════════════════════════ spec ═══════════════════════════════
The more readable specification. Each production of the input grammar becomes an
inlined well-formedness predicate `IsWf.*` written as a plain existential over the
named captures, so you can read it side-by-side with the grammar and check that it
says the same thing. When present, `WfConstraints` contains capture-derived format
conditions and `Constraints` contains conditions that explicitly mention the final
`value`. Empty phases are omitted; `IsWf` and `IsValid` specialize accordingly.
This file is proof-free — it is what you cite. -/

def Datetime.grammar : Grammar :=
  Grammar.mk "Datetime"
    [Production.mk "Datetime"
        [[SymItem.mk (Sym.ref "Date") false],
          [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
            SymItem.mk (Sym.lit "Z") false],
          [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
            SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.lit "Z") false],
          [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
            SymItem.mk (Sym.ref "Offset") false],
          [SymItem.mk (Sym.ref "Date") false, SymItem.mk (Sym.lit "T") false, SymItem.mk (Sym.ref "Time") false,
            SymItem.mk (Sym.lit ".") false, SymItem.mk (Sym.ref "SSS") false, SymItem.mk (Sym.ref "Offset") false]],
      Production.mk "Date"
        [[SymItem.mk (Sym.ref "YYYY") false, SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "MM") false,
            SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "DD") false]],
      Production.mk "Time"
        [[SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "mm") false,
            SymItem.mk (Sym.lit ":") false, SymItem.mk (Sym.ref "ss") false]],
      Production.mk "Offset"
        [[SymItem.mk (Sym.lit "+") false, SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.ref "mm") false],
          [SymItem.mk (Sym.lit "-") false, SymItem.mk (Sym.ref "hh") false, SymItem.mk (Sym.ref "mm") false]],
      Production.mk "SSS" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 3)) false]],
      Production.mk "YYYY" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 4)) false]],
      Production.mk "MM" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]],
      Production.mk "DD" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]],
      Production.mk "hh" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]],
      Production.mk "mm" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]],
      Production.mk "ss" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.exactly 2)) false]]]

inductive Datetime.Derivation.YYYY where
  | alt0 (part0 : String)
  deriving Repr, DecidableEq

def Datetime.Derivation.YYYY.render : Datetime.Derivation.YYYY → String
  | .alt0 part0 => (part0 ++ "")

def Datetime.Derivation.YYYY.Valid : Datetime.Derivation.YYYY → Prop
  | .alt0 part0 => matchesTerm TokClass.digit (LenSpec.exactly 4) part0

inductive Datetime.Derivation.MM where
  | alt0 (part0 : String)
  deriving Repr, DecidableEq

def Datetime.Derivation.MM.render : Datetime.Derivation.MM → String
  | .alt0 part0 => (part0 ++ "")

def Datetime.Derivation.MM.Valid : Datetime.Derivation.MM → Prop
  | .alt0 part0 => matchesTerm TokClass.digit (LenSpec.exactly 2) part0

inductive Datetime.Derivation.DD where
  | alt0 (part0 : String)
  deriving Repr, DecidableEq

def Datetime.Derivation.DD.render : Datetime.Derivation.DD → String
  | .alt0 part0 => (part0 ++ "")

def Datetime.Derivation.DD.Valid : Datetime.Derivation.DD → Prop
  | .alt0 part0 => matchesTerm TokClass.digit (LenSpec.exactly 2) part0

inductive Datetime.Derivation.Date where
  | alt0 (part0 : Datetime.Derivation.YYYY) (part2 : Datetime.Derivation.MM) (part4 : Datetime.Derivation.DD)
  deriving Repr, DecidableEq

def Datetime.Derivation.Date.render : Datetime.Derivation.Date → String
  | .alt0 part0 part2 part4 =>
    (Datetime.Derivation.YYYY.render part0 ++
      ("-" ++ (Datetime.Derivation.MM.render part2 ++ ("-" ++ (Datetime.Derivation.DD.render part4 ++ "")))))

def Datetime.Derivation.Date.Valid : Datetime.Derivation.Date → Prop
  | .alt0 part0 part2 part4 =>
    (Datetime.Derivation.YYYY.Valid part0 ∧ (Datetime.Derivation.MM.Valid part2 ∧ Datetime.Derivation.DD.Valid part4))

inductive Datetime.Derivation.hh where
  | alt0 (part0 : String)
  deriving Repr, DecidableEq

def Datetime.Derivation.hh.render : Datetime.Derivation.hh → String
  | .alt0 part0 => (part0 ++ "")

def Datetime.Derivation.hh.Valid : Datetime.Derivation.hh → Prop
  | .alt0 part0 => matchesTerm TokClass.digit (LenSpec.exactly 2) part0

inductive Datetime.Derivation.mm where
  | alt0 (part0 : String)
  deriving Repr, DecidableEq

def Datetime.Derivation.mm.render : Datetime.Derivation.mm → String
  | .alt0 part0 => (part0 ++ "")

def Datetime.Derivation.mm.Valid : Datetime.Derivation.mm → Prop
  | .alt0 part0 => matchesTerm TokClass.digit (LenSpec.exactly 2) part0

inductive Datetime.Derivation.ss where
  | alt0 (part0 : String)
  deriving Repr, DecidableEq

def Datetime.Derivation.ss.render : Datetime.Derivation.ss → String
  | .alt0 part0 => (part0 ++ "")

def Datetime.Derivation.ss.Valid : Datetime.Derivation.ss → Prop
  | .alt0 part0 => matchesTerm TokClass.digit (LenSpec.exactly 2) part0

inductive Datetime.Derivation.Time where
  | alt0 (part0 : Datetime.Derivation.hh) (part2 : Datetime.Derivation.mm) (part4 : Datetime.Derivation.ss)
  deriving Repr, DecidableEq

def Datetime.Derivation.Time.render : Datetime.Derivation.Time → String
  | .alt0 part0 part2 part4 =>
    (Datetime.Derivation.hh.render part0 ++
      (":" ++ (Datetime.Derivation.mm.render part2 ++ (":" ++ (Datetime.Derivation.ss.render part4 ++ "")))))

def Datetime.Derivation.Time.Valid : Datetime.Derivation.Time → Prop
  | .alt0 part0 part2 part4 =>
    (Datetime.Derivation.hh.Valid part0 ∧ (Datetime.Derivation.mm.Valid part2 ∧ Datetime.Derivation.ss.Valid part4))

inductive Datetime.Derivation.SSS where
  | alt0 (part0 : String)
  deriving Repr, DecidableEq

def Datetime.Derivation.SSS.render : Datetime.Derivation.SSS → String
  | .alt0 part0 => (part0 ++ "")

def Datetime.Derivation.SSS.Valid : Datetime.Derivation.SSS → Prop
  | .alt0 part0 => matchesTerm TokClass.digit (LenSpec.exactly 3) part0

inductive Datetime.Derivation.Offset where
  | alt0 (part1 : Datetime.Derivation.hh) (part2 : Datetime.Derivation.mm)
  | alt1 (part1 : Datetime.Derivation.hh) (part2 : Datetime.Derivation.mm)
  deriving Repr, DecidableEq

def Datetime.Derivation.Offset.render : Datetime.Derivation.Offset → String
  | .alt0 part1 part2 => ("+" ++ (Datetime.Derivation.hh.render part1 ++ (Datetime.Derivation.mm.render part2 ++ "")))
  | .alt1 part1 part2 => ("-" ++ (Datetime.Derivation.hh.render part1 ++ (Datetime.Derivation.mm.render part2 ++ "")))

def Datetime.Derivation.Offset.Valid : Datetime.Derivation.Offset → Prop
  | .alt0 part1 part2 => (Datetime.Derivation.hh.Valid part1 ∧ Datetime.Derivation.mm.Valid part2)
  | .alt1 part1 part2 => (Datetime.Derivation.hh.Valid part1 ∧ Datetime.Derivation.mm.Valid part2)

inductive Datetime.Derivation.Datetime where
  | alt0 (part0 : Datetime.Derivation.Date)
  | alt1 (part0 : Datetime.Derivation.Date) (part2 : Datetime.Derivation.Time)
  | alt2 (part0 : Datetime.Derivation.Date) (part2 : Datetime.Derivation.Time) (part4 : Datetime.Derivation.SSS)
  | alt3 (part0 : Datetime.Derivation.Date) (part2 : Datetime.Derivation.Time) (part3 : Datetime.Derivation.Offset)
  |
  alt4 (part0 : Datetime.Derivation.Date) (part2 : Datetime.Derivation.Time) (part4 : Datetime.Derivation.SSS)
    (part5 : Datetime.Derivation.Offset)
  deriving Repr, DecidableEq

def Datetime.Derivation.Datetime.render : Datetime.Derivation.Datetime → String
  | .alt0 part0 => (Datetime.Derivation.Date.render part0 ++ "")
  | .alt1 part0 part2 =>
    (Datetime.Derivation.Date.render part0 ++ ("T" ++ (Datetime.Derivation.Time.render part2 ++ ("Z" ++ ""))))
  | .alt2 part0 part2 part4 =>
    (Datetime.Derivation.Date.render part0 ++
      ("T" ++
        (Datetime.Derivation.Time.render part2 ++ ("." ++ (Datetime.Derivation.SSS.render part4 ++ ("Z" ++ ""))))))
  | .alt3 part0 part2 part3 =>
    (Datetime.Derivation.Date.render part0 ++
      ("T" ++ (Datetime.Derivation.Time.render part2 ++ (Datetime.Derivation.Offset.render part3 ++ ""))))
  | .alt4 part0 part2 part4 part5 =>
    (Datetime.Derivation.Date.render part0 ++
      ("T" ++
        (Datetime.Derivation.Time.render part2 ++
          ("." ++ (Datetime.Derivation.SSS.render part4 ++ (Datetime.Derivation.Offset.render part5 ++ ""))))))

def Datetime.Derivation.Datetime.Valid : Datetime.Derivation.Datetime → Prop
  | .alt0 part0 => Datetime.Derivation.Date.Valid part0
  | .alt1 part0 part2 => (Datetime.Derivation.Date.Valid part0 ∧ Datetime.Derivation.Time.Valid part2)
  | .alt2 part0 part2 part4 =>
    (Datetime.Derivation.Date.Valid part0 ∧
      (Datetime.Derivation.Time.Valid part2 ∧ Datetime.Derivation.SSS.Valid part4))
  | .alt3 part0 part2 part3 =>
    (Datetime.Derivation.Date.Valid part0 ∧
      (Datetime.Derivation.Time.Valid part2 ∧ Datetime.Derivation.Offset.Valid part3))
  | .alt4 part0 part2 part4 part5 =>
    (Datetime.Derivation.Date.Valid part0 ∧
      (Datetime.Derivation.Time.Valid part2 ∧
        (Datetime.Derivation.SSS.Valid part4 ∧ Datetime.Derivation.Offset.Valid part5)))

def Datetime.IsWf.YYYY (s : String) : Prop :=
  IsFixedDigits 4 s

def Datetime.IsWf.MM (s : String) : Prop :=
  IsFixedDigits 2 s

def Datetime.IsWf.DD (s : String) : Prop :=
  IsFixedDigits 2 s

def Datetime.IsWf.Date (s : String) : Prop :=
  ∃ yyyy mm dd,
    ((s = yyyy ++ "-" ++ mm ++ "-" ++ dd ∧ Datetime.IsWf.YYYY yyyy) ∧ Datetime.IsWf.MM mm) ∧ Datetime.IsWf.DD dd

def Datetime.IsWf.hh (s : String) : Prop :=
  IsFixedDigits 2 s

def Datetime.IsWf.mm (s : String) : Prop :=
  IsFixedDigits 2 s

def Datetime.IsWf.ss (s : String) : Prop :=
  IsFixedDigits 2 s

def Datetime.IsWf.Time (s : String) : Prop :=
  ∃ hh mm ss, ((s = hh ++ ":" ++ mm ++ ":" ++ ss ∧ Datetime.IsWf.hh hh) ∧ Datetime.IsWf.mm mm) ∧ Datetime.IsWf.ss ss

def Datetime.IsWf.SSS (s : String) : Prop :=
  IsFixedDigits 3 s

def Datetime.IsWf.Offset (s : String) : Prop :=
  (∃ hh mm, (s = "+" ++ hh ++ mm ∧ Datetime.IsWf.hh hh) ∧ Datetime.IsWf.mm mm) ∨
    ∃ hh mm, (s = "-" ++ hh ++ mm ∧ Datetime.IsWf.hh hh) ∧ Datetime.IsWf.mm mm

def Datetime.IsWf.Datetime (s : String) : Prop :=
  (((Datetime.IsWf.Date s ∨
          ∃ date time, (s = date ++ "T" ++ time ++ "Z" ∧ Datetime.IsWf.Date date) ∧ Datetime.IsWf.Time time) ∨
        ∃ date time sss,
          ((s = date ++ "T" ++ time ++ "." ++ sss ++ "Z" ∧ Datetime.IsWf.Date date) ∧ Datetime.IsWf.Time time) ∧
            Datetime.IsWf.SSS sss) ∨
      ∃ date time offset,
        ((s = date ++ "T" ++ time ++ offset ∧ Datetime.IsWf.Date date) ∧ Datetime.IsWf.Time time) ∧
          Datetime.IsWf.Offset offset) ∨
    ∃ date time sss offset,
      (((s = date ++ "T" ++ time ++ "." ++ sss ++ offset ∧ Datetime.IsWf.Date date) ∧ Datetime.IsWf.Time time) ∧
          Datetime.IsWf.SSS sss) ∧
        Datetime.IsWf.Offset offset

def Datetime.value (yyyy : String) (mm : String) (dd : String) (time_hh : String) (time_mm : String) (ss : String)
    (sss : String) (offset_hh : String) (offset_mm : String) (offset : String) :=
  epochMillis yyyy mm dd time_hh time_mm ss sss offset_hh offset_mm offset

def Datetime.WfConstraints (mm : String) (time_hh : String) (time_mm : String) (ss : String) (offset_hh : String)
    (offset_mm : String) (yyyy : String) (dd : String) : Prop :=
  (((((((1 : Int) ≤ natOf mm ∧ natOf mm ≤ (12 : Int)) ∧ (0 : Int) ≤ natOf time_hh ∧ natOf time_hh ≤ (23 : Int)) ∧
            (0 : Int) ≤ natOf time_mm ∧ natOf time_mm ≤ (59 : Int)) ∧
          (0 : Int) ≤ natOf ss ∧ natOf ss ≤ (59 : Int)) ∧
        (0 : Int) ≤ natOf offset_hh ∧ natOf offset_hh ≤ (23 : Int)) ∧
      (0 : Int) ≤ natOf offset_mm ∧ natOf offset_mm ≤ (59 : Int)) ∧
    dayBound yyyy mm dd = true

def Datetime.SatisfiesWfConstraints (s : String) : Prop :=
  Datetime.WfConstraints (Triptych.component Datetime.grammar s "MM") (Triptych.component Datetime.grammar s "Time.hh")
    (Triptych.component Datetime.grammar s "Time.mm") (Triptych.component Datetime.grammar s "ss")
    (Triptych.component Datetime.grammar s "Offset.hh") (Triptych.component Datetime.grammar s "Offset.mm")
    (Triptych.component Datetime.grammar s "YYYY") (Triptych.component Datetime.grammar s "DD")

abbrev Datetime.IsWf (s : String) : Prop :=
  Datetime.IsWf.Datetime s ∧ Datetime.SatisfiesWfConstraints s

abbrev Datetime.IsValid (s : String) : Prop :=
  Datetime.IsWf s

structure Datetime.View where
  input : String
  yyyy : String
  mm : String
  dd : String
  time_hh : Option String
  time_mm : Option String
  ss : Option String
  sss : Option String
  offset_hh : Option String
  offset_mm : Option String
  offset : Option String

def Datetime.View.WfConstraints (v : Datetime.View) : Prop :=
  Datetime.WfConstraints (Datetime.View.mm v) ((Datetime.View.time_hh v).getD "") ((Datetime.View.time_mm v).getD "")
    ((Datetime.View.ss v).getD "") ((Datetime.View.offset_hh v).getD "") ((Datetime.View.offset_mm v).getD "")
    (Datetime.View.yyyy v) (Datetime.View.dd v)

abbrev Datetime.View.Valid (v : Datetime.View) : Prop :=
  Datetime.View.WfConstraints v

def Datetime.View.denotation (v : Datetime.View) :=
  Datetime.value (Datetime.View.yyyy v) (Datetime.View.mm v) (Datetime.View.dd v) ((Datetime.View.time_hh v).getD "")
    ((Datetime.View.time_mm v).getD "") ((Datetime.View.ss v).getD "") ((Datetime.View.sss v).getD "")
    ((Datetime.View.offset_hh v).getD "") ((Datetime.View.offset_mm v).getD "") ((Datetime.View.offset v).getD "")
