/- Generated by Triptych from `triptych Graph`. -/

import Triptych.Architecture.Denote
import Triptych.Architecture.Derivation
import Triptych.Architecture.Value
import Triptych.Architecture.Constraint
import Triptych.Architecture.Assemble
import Triptych.Theorems.Reconcile
import Triptych.Theorems.Value
import Triptych.Theorems.DecodeLemmas
import Triptych.Theorems.Derivation
import Triptych.Theorems.RelationalParser
import Triptych.Theorems.Unambiguity
import Graph.spec
import Graph.grammar

open Triptych
open GraphExample

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ══════════════════════════════ engine ══════════════════════════════
The executable counterpart of the spec. `decode` walks the grammar over an input
string and returns its captured components; `computeValue` then evaluates the value
function on those captures, and `isWf`/`isValid` decide well-formedness/acceptance.
`decodeView` packages the exact input and value/constraint captures as a typed `View`.

Naming convention: CAPITALIZED `IsWf.*`/`IsValid` are the surface `Prop`s you READ
and reason about; lowercase `isWf`/`isValid` are the engine's executable deciders you
RUN (`#eval isValid s`, `#eval computeValue s`). The `equivalence` section below
proves the two describe the same language and value. -/

instance Graph.Derivation.Cells.instDecidableValid : DecidablePred Graph.Derivation.Cells.Valid := fun d => by
  cases d <;> simp only [Graph.Derivation.Cells.Valid] <;> infer_instance

def Graph.Derivation.Cells.capturesWith (qual : String) : Graph.Derivation.Cells → Triptych.CaptureMap
  | .alt0 part0 => ([] ++ [])

instance Graph.Derivation.Adj.instDecidableValid : DecidablePred Graph.Derivation.Adj.Valid := fun d => by
  cases d <;> simp only [Graph.Derivation.Adj.Valid] <;> infer_instance

def Graph.Derivation.Adj.capturesWith (qual : String) : Graph.Derivation.Adj → Triptych.CaptureMap
  | .alt0 part0 =>
    (Triptych.referenceCaptures qual "Cells" (Graph.Derivation.Cells.render part0) ++
        Graph.Derivation.Cells.capturesWith "Cells" part0 ++
      [])

def Graph.valueFn := fun m : Triptych.CaptureMap => toGraph ((Triptych.CaptureMap.toEnv m "Cells").getD "")

def Graph.constraints : List ConstraintEntry :=
  [ConstraintEntry.opaqueMap ConstraintPhase.wellFormed fun m : Triptych.CaptureMap =>
      isTriangular ((Triptych.CaptureMap.toEnv m "Cells").getD "")]

abbrev Graph.isWf (s : String) : Prop :=
  Triptych.isWf Graph.grammar Graph.constraints s

abbrev Graph.satisfiesConstraints (s : String) : Prop :=
  Triptych.satisfiesConstraints Graph.grammar Graph.constraints s

abbrev Graph.isValid (s : String) : Prop :=
  Graph.isWf s ∧ Graph.satisfiesConstraints s

def Graph.computeValue (s : String) :=
  Triptych.computeValueMap Graph.grammar Graph.valueFn s

def Graph.View.ofMap (input : String) (m : Triptych.CaptureMap) : Graph.View :=
  Graph.View.mk input ((Triptych.CaptureMap.toEnv m "Cells").getD "")

def Graph.decodeView (s : String) : Option Graph.View :=
  (decode Graph.grammar s).map (Graph.View.ofMap s)

def Graph.Derivation.Adj.toView (d : Graph.Derivation.Adj) : Graph.View :=
  Graph.View.ofMap (Graph.Derivation.Adj.render d) (Graph.Derivation.Adj.capturesWith "" d)

/- ════════════════════════════ equivalence ════════════════════════════
The auto-discharged guarantees relating the readable surface to the executable
engine: `IsWfGrammar_equiv` proves grammar-layout agreement and `IsWf_equiv`
proves full well-formedness agreement. `computeValue_eq` proves the values agree,
while `decodeView_input`, `IsValid_view`, and `computeValue_view` expose the typed
parse view. Derived `DecidablePred` instances make the surface predicates executable
via the engine. No `sorry`. -/

theorem Graph.grammarDecodeUnique : GrammarDecodeUnique Graph.grammar :=
  GrammarDecodeUnique.of_staticUnique Graph.grammar (by decide)

theorem Graph.grammarCaptureFunctional : GrammarCaptureFunctional Graph.grammar :=
  GrammarCaptureFunctional.of_unique Graph.grammar Graph.grammarDecodeUnique

theorem Graph.Derivation.Cells.matches (qual : String) (fuel : Nat) (d : Graph.Derivation.Cells)
    (hvalid : Graph.Derivation.Cells.Valid d) :
    Triptych.ProdMatch Graph.grammar qual (fuel + 1)
      (Production.mk "Cells" [[SymItem.mk (Sym.term TokClass.bit (LenSpec.atLeastOne)) false]])
      (Graph.Derivation.Cells.render d) (Graph.Derivation.Cells.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [Graph.Derivation.Cells.Valid] at hvalid
    have hpart0 := hvalid
    simp only [Graph.Derivation.Cells.render, Graph.Derivation.Cells.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.term TokClass.bit (LenSpec.atLeastOne)) false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          · exact Triptych.symMatch_term Graph.grammar qual (fuel + 1) TokClass.bit (LenSpec.atLeastOne) part0 hpart0
          · exact Triptych.seqMatch_nil Graph.grammar qual (fuel + 1))

theorem Graph.Derivation.Adj.matches (qual : String) (fuel : Nat) (d : Graph.Derivation.Adj)
    (hvalid : Graph.Derivation.Adj.Valid d) :
    Triptych.ProdMatch Graph.grammar qual (fuel + 2) (Production.mk "Adj" [[SymItem.mk (Sym.ref "Cells") false]])
      (Graph.Derivation.Adj.render d) (Graph.Derivation.Adj.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [Graph.Derivation.Adj.Valid] at hvalid
    have hpart0 := hvalid
    simp only [Graph.Derivation.Adj.render, Graph.Derivation.Adj.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.ref "Cells") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              (by
                simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                  (Triptych.symMatch_ref Graph.grammar qual (((fuel + 0)) + 1) "Cells"
                    (Production.mk "Cells" [[SymItem.mk (Sym.term TokClass.bit (LenSpec.atLeastOne)) false]]) (by rfl)
                    (Graph.Derivation.Cells.render part0) (Graph.Derivation.Cells.capturesWith "Cells" part0)
                    (Graph.Derivation.Cells.matches "Cells" (fuel + 0) part0 hpart0)))
          · exact Triptych.seqMatch_nil Graph.grammar qual (fuel + 2))

theorem Graph.Derivation.Adj.mem_fullParses (d : Graph.Derivation.Adj) (hvalid : Graph.Derivation.Adj.Valid d) :
    Graph.Derivation.Adj.capturesWith "" d ∈ Triptych.fullParses Graph.grammar (Graph.Derivation.Adj.render d) :=
  by
  apply
    Triptych.prodMatch_mem_fullParses Graph.grammar (Production.mk "Adj" [[SymItem.mk (Sym.ref "Cells") false]])
      (by rfl)
  simpa [Graph.grammar] using (Graph.Derivation.Adj.matches "" 0 d hvalid)

theorem Graph.Derivation.Adj.decode_render_of_captureFunctional
    (hfunctional : Triptych.GrammarCaptureFunctional Graph.grammar) (d : Graph.Derivation.Adj)
    (hvalid : Graph.Derivation.Adj.Valid d) :
    Triptych.decode Graph.grammar (Graph.Derivation.Adj.render d) = some (Graph.Derivation.Adj.capturesWith "" d) :=
  Triptych.decode_eq_of_mem_fullParses hfunctional (mem_fullParses d hvalid)

theorem Graph.Derivation.Adj.decode_render (d : Graph.Derivation.Adj) (hvalid : Graph.Derivation.Adj.Valid d) :
    Triptych.decode Graph.grammar (Graph.Derivation.Adj.render d) = some (Graph.Derivation.Adj.capturesWith "" d) :=
  decode_render_of_captureFunctional Graph.grammarCaptureFunctional d hvalid

theorem Graph.grammarValueCoherent : GrammarValueCoherent Graph.grammar Graph.valueFn :=
  GrammarValueCoherent.of_captureFunctional Graph.grammar Graph.valueFn Graph.grammarCaptureFunctional

theorem Graph.decodeView_input {s : String} {v : Graph.View} (h : Graph.decodeView s = some v) :
    Graph.View.input v = s := by
  unfold Graph.decodeView at h
  rw [Option.map_eq_some_iff] at h
  obtain ⟨m, _, hv⟩ := h
  subst v
  rfl

theorem Graph.Derivation.Adj.decodeView_render_of_captureFunctional
    (hfunctional : Triptych.GrammarCaptureFunctional Graph.grammar) (d : Graph.Derivation.Adj)
    (hvalid : Graph.Derivation.Adj.Valid d) :
    Graph.decodeView (Graph.Derivation.Adj.render d) = some (Graph.Derivation.Adj.toView d) :=
  by
  unfold Graph.decodeView Graph.Derivation.Adj.toView
  rw [Graph.Derivation.Adj.decode_render_of_captureFunctional hfunctional d hvalid]
  rfl

theorem Graph.Derivation.Adj.decodeView_render (d : Graph.Derivation.Adj) (hvalid : Graph.Derivation.Adj.Valid d) :
    Graph.decodeView (Graph.Derivation.Adj.render d) = some (Graph.Derivation.Adj.toView d) :=
  decodeView_render_of_captureFunctional Graph.grammarCaptureFunctional d hvalid

theorem Graph.SatisfiesWfConstraints_of_decode {s : String} {m : Triptych.CaptureMap}
    (h : decode Graph.grammar s = some m) :
    Graph.SatisfiesWfConstraints s ↔ Graph.WfConstraints ((Triptych.CaptureMap.toEnv m "Cells").getD "") :=
  by
  unfold Graph.SatisfiesWfConstraints
  simp only [Triptych.component_eq_of_decode h "Cells"]

theorem Graph.Internal.matchesRef.Cells (fuel : Nat) (s : String) :
    matchesSym Graph.grammar (fuel + 1) (Sym.ref "Cells") s ↔ Graph.IsWf.Cells s :=
  by
  rw [matchesSym,
    show
      (Graph.grammar).prod? "Cells" =
        some (Production.mk "Cells" [[SymItem.mk (Sym.term TokClass.bit LenSpec.atLeastOne) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Graph.IsWf.Cells
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsBits_matchesTerm,
    IsFixedBits_matchesTerm, IsBitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Graph.Internal.matchesRef.Adj (fuel : Nat) (s : String) :
    matchesSym Graph.grammar (fuel + 2) (Sym.ref "Adj") s ↔ Graph.IsWf.Adj s :=
  by
  rw [matchesSym,
    show (Graph.grammar).prod? "Adj" = some (Production.mk "Adj" [[SymItem.mk (Sym.ref "Cells") false]]) from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Graph.IsWf.Adj
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym,
    Graph.Internal.matchesRef.Cells]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Graph.IsWfGrammar_equiv (s : String) : Triptych.IsWf Graph.grammar s ↔ Graph.IsWf.Adj s :=
  by
  rw [isWf_eq_isWfProd_start, IsWfProd,
    show (Graph.grammar).prod? (Graph.grammar).start = some (Production.mk "Adj" [[SymItem.mk (Sym.ref "Cells") false]])
      from rfl]
  have hstart :
    ∀ n,
      matchesProd Graph.grammar n (Production.mk "Adj" [[SymItem.mk (Sym.ref "Cells") false]]) s =
        matchesSym Graph.grammar (n + 1) (Sym.ref "Adj") s :=
    by
    intro n
    rw [matchesSym,
      show (Graph.grammar).prod? "Adj" = some (Production.mk "Adj" [[SymItem.mk (Sym.ref "Cells") false]]) from rfl]
  show
    matchesProd Graph.grammar (Graph.grammar).prods.length (Production.mk "Adj" [[SymItem.mk (Sym.ref "Cells") false]])
        s ↔
      _
  rw [hstart]
  exact Graph.Internal.matchesRef.Adj _ s

theorem Graph.IsWf_equiv (s : String) : Graph.IsWf s ↔ Graph.isWf s :=
  by
  unfold Graph.IsWf Graph.isWf Triptych.isWf
  rw [← Graph.IsWfGrammar_equiv, ← decodeSome_iff_IsWf Graph.grammar (by decide)]
  unfold Graph.SatisfiesWfConstraints Graph.WfConstraints Graph.constraints
  simp only [Triptych.component, Triptych.componentList, Triptych.envOf, Triptych.captureMapOf, List.forall_mem_cons,
    List.forall_mem_singleton, List.not_mem_nil, forall_const, ConstraintEntry.wfPart, Constraint.eval, ValExpr.eval,
    presentCount, natOf_getD, intOf_getD, lenOf_getD, countOf_getD, signOf_getD, Env.countVal, and_true, true_and,
    false_implies, implies_true, Bool.false_eq_true]
  try grind

theorem Graph.IsValid_equiv (s : String) : Graph.IsValid s ↔ Graph.isValid s :=
  by
  unfold Graph.IsValid Graph.isValid
  rw [(Graph.IsWf_equiv s)]
  unfold Graph.satisfiesConstraints Triptych.satisfiesConstraints Triptych.captureMapOf Graph.constraints
  simp only [List.forall_mem_cons, List.forall_mem_singleton, List.not_mem_nil, ConstraintEntry.valPart, false_implies,
    true_and, and_true]
  constructor
  · intro h
    exact ⟨h, fun _ => True.intro⟩
  · exact And.left

instance Graph.instDecidableGrammar : DecidablePred Graph.IsWf.Adj := fun s =>
  @decidable_of_iff _ _ (Graph.IsWfGrammar_equiv s) (Triptych.decIsWf Graph.grammar (by decide) s)

instance Graph.instDecidableIsWf : DecidablePred Graph.IsWf := fun s =>
  @decidable_of_iff _ _ (Graph.IsWf_equiv s).symm inferInstance

instance Graph.instDecidableIsValid : DecidablePred Graph.IsValid := fun s => inferInstance

theorem Graph.View.wfConstraints_of_decode {s : String} {m : Triptych.CaptureMap}
    (h : decode Graph.grammar s = some m) :
    Graph.SatisfiesWfConstraints s ↔ Graph.View.WfConstraints (Graph.View.ofMap s m) :=
  by
  rw [Graph.SatisfiesWfConstraints_of_decode h]
  rfl

theorem Graph.IsValid_view (s : String) :
    Graph.IsValid s ↔ ∃ v : Graph.View, Graph.decodeView s = some v ∧ Graph.View.Valid v :=
  by
  constructor
  · intro hvalid
    have hengine : Graph.isValid s := (Graph.IsValid_equiv s).mp hvalid
    have hsome : (decode Graph.grammar s).isSome = true := by exact hengine.1.1
    obtain ⟨m, hm⟩ := Option.isSome_iff_exists.mp hsome
    refine ⟨Graph.View.ofMap s m, ?_, ?_⟩
    · unfold Graph.decodeView
      simp [hm]
    · exact (Graph.View.wfConstraints_of_decode hm).mp hvalid.2
  · rintro ⟨v, hview, hvalid⟩
    unfold Graph.decodeView at hview
    rw [Option.map_eq_some_iff] at hview
    obtain ⟨m, hm, hv⟩ := hview
    subst v
    have hdecoded : (decode Graph.grammar s).isSome = true := by simp [hm]
    have hgrammar := (Graph.IsWfGrammar_equiv s).mp ((decodeSome_iff_IsWf Graph.grammar (by decide) s).mp hdecoded)
    exact ⟨hgrammar, (Graph.View.wfConstraints_of_decode hm).mpr hvalid⟩

theorem Graph.computeValue_eq (s : String) :
    Graph.computeValue s =
      (decode Graph.grammar s).map (fun _ => Graph.value (Triptych.component Graph.grammar s "Cells")) :=
  by
  unfold Graph.computeValue Triptych.computeValueMap Triptych.component Triptych.envOf Triptych.captureMapOf Graph.value
    Graph.valueFn
  cases h : decode Graph.grammar s with
  | none => simp
  | some m => simp [natOf_getD, intOf_getD, lenOf_getD, countOf_getD, signOf_getD, Env.countVal, ValExpr.eval]

theorem Graph.computeValue_of_decode {s : String} {m : Triptych.CaptureMap} (h : decode Graph.grammar s = some m) :
    Graph.computeValue s = some (Graph.value ((Triptych.CaptureMap.toEnv m "Cells").getD "")) :=
  by
  rw [Graph.computeValue_eq, h]
  simp only [Option.map_some, Triptych.component_eq_of_decode h "Cells"]

theorem Graph.computeValue_view (s : String) : Graph.computeValue s = (Graph.decodeView s).map Graph.View.denotation :=
  by
  unfold Graph.decodeView
  cases h : decode Graph.grammar s with
  |
    none =>
    rw [show Graph.computeValue s = none by
        rw [Graph.computeValue_eq, h]
        rfl]
    rfl
  | some m =>
    rw [Graph.computeValue_of_decode h]
    simp only [Option.map_some]
    rfl

/- ═══════════════════════════════ parser ══════════════════════════════
The generated correct-by-construction parser `parse` (= `computeValue` gated on the
decidable `isValid`) together with its guarantees — `parse_sound`, `parse_complete`,
`parse_reject`, `parse_view`, and typed `parse_eq_some_iff_view` /
`parse_eq_none_iff_view` normal forms — all AUTO-DISCHARGED here.
When an external parser is declared, `checkedExtParse` additionally validates each
external result against this parser and ships an AUTO-DISCHARGED soundness theorem.
A verified parser, no `sorry`. -/

theorem Graph.computeValue_isSome (s : String) : Graph.isValid s → (Graph.computeValue s).isSome :=
  by
  intro h
  unfold Graph.isValid Graph.isWf Triptych.isWf at h
  unfold Graph.computeValue Triptych.computeValueMap
  rw [Option.isSome_map]
  exact h.1.1

def Graph.parse (s : String) :=
  Triptych.gatedParse Graph.isValid Graph.computeValue s

theorem Graph.parse_sound (s : String) (g : Graph) :
    Graph.parse s = some g → Graph.isValid s ∧ Graph.computeValue s = some g :=
  Triptych.gatedParse_sound _ _ s g

theorem Graph.parse_complete (s : String) (g : Graph) :
    Graph.isValid s → Graph.computeValue s = some g → Graph.parse s = some g :=
  Triptych.gatedParse_complete _ _ s g

theorem Graph.parse_reject (s : String) : Graph.parse s = none ↔ ¬Graph.isValid s :=
  Triptych.gatedParse_reject _ _ Graph.computeValue_isSome s

theorem Graph.parse_view (s : String) :
    Graph.parse s = if decide (Graph.isValid s) then (Graph.decodeView s).map Graph.View.denotation else none :=
  by
  unfold Graph.parse Triptych.gatedParse
  rw [Graph.computeValue_view]

theorem Graph.parse_eq_some_iff_view (s : String) (g : Graph) :
    Graph.parse s = some g ↔
      ∃ v : Graph.View, Graph.decodeView s = some v ∧ Graph.View.Valid v ∧ Graph.View.denotation v = g :=
  by
  constructor
  · intro hparse
    obtain ⟨hvalidEngine, hvalue⟩ := Graph.parse_sound s g hparse
    have hvalidSurface := (Graph.IsValid_equiv s).mpr hvalidEngine
    obtain ⟨v, hview, hvalidView⟩ := (Graph.IsValid_view s).mp hvalidSurface
    refine ⟨v, hview, hvalidView, ?_⟩
    rw [Graph.computeValue_view, hview] at hvalue
    exact Option.some.inj hvalue
  · rintro ⟨v, hview, hvalidView, hvalue⟩
    apply Graph.parse_complete s g
    · exact (Graph.IsValid_equiv s).mp ((Graph.IsValid_view s).mpr ⟨v, hview, hvalidView⟩)
    · rw [Graph.computeValue_view, hview]
      exact congrArg some hvalue

theorem Graph.parse_eq_none_iff_view (s : String) :
    Graph.parse s = none ↔ ¬∃ v : Graph.View, Graph.decodeView s = some v ∧ Graph.View.Valid v :=
  by
  rw [Graph.parse_reject]
  constructor
  · intro hinvalid ⟨v, hview, hvalidView⟩
    exact hinvalid ((Graph.IsValid_equiv s).mp ((Graph.IsValid_view s).mpr ⟨v, hview, hvalidView⟩))
  · intro hnoview hvalidEngine
    have hvalidSurface := (Graph.IsValid_equiv s).mpr hvalidEngine
    exact hnoview ((Graph.IsValid_view s).mp hvalidSurface)

theorem Graph.parse_iff_denotes (s : String) (g : Graph) :
    Graph.parse s = some g ↔
      Triptych.Denotes Graph.grammar (Triptych.CaptureAccepts Graph.constraints) Graph.valueFn s g :=
  by
  unfold Graph.parse Graph.computeValue
  exact
    Triptych.gatedParseMap_eq_some_iff_denotes Graph.grammar Graph.constraints Graph.valueFn
      Graph.grammarCaptureFunctional s g
