/- Generated by Triptych from `triptych Graph`. -/

import Triptych.Architecture.Denote
import Triptych.Architecture.Value
import Triptych.Architecture.Constraint
import Triptych.Architecture.Assemble
import Triptych.Theorems.Reconcile
import Graph.grammar

open Triptych
open GraphExample

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ═══════════════════════════════ spec ═══════════════════════════════
The more readable specification. Each production of the input grammar becomes an
inlined well-formedness predicate `IsWf.*` written as a plain existential over the
named captures, so you can read it side-by-side with the grammar and check that it
says the same thing. When present, `WfConstraints` contains capture-derived format
conditions and `Constraints` contains conditions that explicitly mention the final
`value`. Empty phases are omitted; `IsWf` and `IsValid` specialize accordingly.
This file is proof-free — it is what you cite. -/

def Graph.grammar : Grammar :=
  Grammar.mk "Adj"
    [Production.mk "Adj" [[SymItem.mk (Sym.ref "Cells") false]],
      Production.mk "Cells" [[SymItem.mk (Sym.term TokClass.bit LenSpec.atLeastOne) false]]]

def Graph.IsWf.Cells (s : String) : Prop :=
  IsBits s

def Graph.IsWf.Adj (s : String) : Prop :=
  Graph.IsWf.Cells s

def Graph.value (cells : String) :=
  toGraph cells

def Graph.WfConstraints (cells : String) : Prop :=
  isTriangular cells = true

def Graph.SatisfiesWfConstraints (s : String) : Prop :=
  Graph.WfConstraints (Triptych.component Graph.grammar s "Cells")

abbrev Graph.IsWf (s : String) : Prop :=
  Graph.IsWf.Adj s ∧ Graph.SatisfiesWfConstraints s

abbrev Graph.IsValid (s : String) : Prop :=
  Graph.IsWf s

structure Graph.View where
  input : String
  cells : String

def Graph.View.WfConstraints (v : Graph.View) : Prop :=
  Graph.WfConstraints (Graph.View.cells v)

abbrev Graph.View.Valid (v : Graph.View) : Prop :=
  Graph.View.WfConstraints v

def Graph.View.denotation (v : Graph.View) :=
  Graph.value (Graph.View.cells v)
