/- Generated by Triptych from `triptych Decimal`. -/

import Triptych.Architecture.Denote
import Triptych.Architecture.Derivation
import Triptych.Architecture.Value
import Triptych.Architecture.Constraint
import Triptych.Architecture.Assemble
import Triptych.Theorems.Reconcile
import Triptych.Theorems.Value
import Triptych.Theorems.DecodeLemmas
import Triptych.Theorems.Derivation
import Triptych.Theorems.RelationalParser
import Triptych.Theorems.Unambiguity
import Outputs.Decimal.spec
import Inputs.Decimal

open Triptych
open CedarExamples.Decimal

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- ══════════════════════════════ engine ══════════════════════════════
The executable counterpart of the spec. `decode` walks the grammar over an input
string and returns its captured components; `computeValue` then evaluates the value
function on those captures. Generated `DecidablePred` instances make the readable
`IsWf` and `IsValid` predicates directly executable.
`decodeView` packages the exact input and value/constraint captures as a typed `View`.

The public format API stays capitalized: use `#eval decide (IsValid s)` and
`#eval computeValue s`. The equivalence section below proves that these readable
predicates execute through the generic Triptych interpreter. -/

instance Decimal.Derivation.Sign.instDecidableValid : DecidablePred Decimal.Derivation.Sign.Valid := fun d => by
  cases d <;> simp only [Decimal.Derivation.Sign.Valid] <;> infer_instance

def Decimal.Derivation.Sign.capturesWith (qual : String) : Decimal.Derivation.Sign → Triptych.CaptureMap
  | .alt0 part0 => (Triptych.capturesOptional (fun entry => []) part0 ++ [])

instance Decimal.Derivation.Natural.instDecidableValid : DecidablePred Decimal.Derivation.Natural.Valid := fun d => by
  cases d <;> simp only [Decimal.Derivation.Natural.Valid] <;> infer_instance

def Decimal.Derivation.Natural.capturesWith (qual : String) : Decimal.Derivation.Natural → Triptych.CaptureMap
  | .alt0 part0 => ([] ++ [])

instance Decimal.Derivation.Fraction.instDecidableValid : DecidablePred Decimal.Derivation.Fraction.Valid := fun d => by
  cases d <;> simp only [Decimal.Derivation.Fraction.Valid] <;> infer_instance

def Decimal.Derivation.Fraction.capturesWith (qual : String) : Decimal.Derivation.Fraction → Triptych.CaptureMap
  | .alt0 part0 => ([] ++ [])

instance Decimal.Derivation.Decimal.instDecidableValid : DecidablePred Decimal.Derivation.Decimal.Valid := fun d => by
  cases d <;> simp only [Decimal.Derivation.Decimal.Valid] <;> infer_instance

def Decimal.Derivation.Decimal.capturesWith (qual : String) : Decimal.Derivation.Decimal → Triptych.CaptureMap
  | .alt0 part0 part1 part3 =>
    (Triptych.referenceCaptures qual "Sign" (Decimal.Derivation.Sign.render part0) ++
        Decimal.Derivation.Sign.capturesWith "Sign" part0 ++
      (Triptych.referenceCaptures qual "Natural" (Decimal.Derivation.Natural.render part1) ++
          Decimal.Derivation.Natural.capturesWith "Natural" part1 ++
        ([] ++
          (Triptych.referenceCaptures qual "Fraction" (Decimal.Derivation.Fraction.render part3) ++
              Decimal.Derivation.Fraction.capturesWith "Fraction" part3 ++
            []))))

def Decimal.valueExpr : ValExpr :=
  ValExpr.mul (ValExpr.signOf "Sign")
    (ValExpr.add (ValExpr.mul (ValExpr.nat "Natural") (ValExpr.pow (ValExpr.lit 10) (ValExpr.lit 4)))
      (ValExpr.mul (ValExpr.nat "Fraction")
        (ValExpr.pow (ValExpr.lit 10) (ValExpr.sub (ValExpr.lit 4) (ValExpr.len "Fraction")))))

def Decimal.valueFn : Env → Int :=
  (Decimal.valueExpr).eval

def Decimal.constraints : List ConstraintEntry :=
  [ConstraintEntry.dsl ConstraintPhase.value
      (Constraint.and (Constraint.le (ValExpr.lit (-9223372036854775808)) Decimal.valueExpr)
        (Constraint.le Decimal.valueExpr (ValExpr.lit 9223372036854775807)))]

def Decimal.computeValue (s : String) : Option Int :=
  Triptych.computeValue Decimal.grammar Decimal.valueExpr s

def Decimal.View.ofMap (input : String) (m : Triptych.CaptureMap) : Decimal.View :=
  Decimal.View.mk input ((Triptych.CaptureMap.toEnv m "Sign").getD "") ((Triptych.CaptureMap.toEnv m "Natural").getD "")
    ((Triptych.CaptureMap.toEnv m "Fraction").getD "")

def Decimal.decodeView (s : String) : Option Decimal.View :=
  (decode Decimal.grammar s).map (Decimal.View.ofMap s)

def Decimal.Derivation.Decimal.toView (d : Decimal.Derivation.Decimal) : Decimal.View :=
  Decimal.View.ofMap (Decimal.Derivation.Decimal.render d) (Decimal.Derivation.Decimal.capturesWith "" d)

/- ════════════════════════════ equivalence ════════════════════════════
The auto-discharged guarantees relating the readable surface to the executable
engine: `IsWfGrammar_equiv` proves grammar-layout agreement and `IsWf_equiv`
proves full well-formedness agreement. `computeValue_eq` proves the values agree,
while `decodeView_input`, `IsValid_view`, and `computeValue_view` expose the typed
parse view. Derived `DecidablePred` instances make the surface predicates executable
via the engine. No `sorry`. -/

theorem Decimal.grammarDecodeUnique : GrammarDecodeUnique Decimal.grammar :=
  GrammarDecodeUnique.of_staticUnique Decimal.grammar (by decide)

theorem Decimal.grammarCaptureFunctional : GrammarCaptureFunctional Decimal.grammar :=
  GrammarCaptureFunctional.of_unique Decimal.grammar Decimal.grammarDecodeUnique

theorem Decimal.Derivation.Sign.matches (qual : String) (fuel : Nat) (d : Decimal.Derivation.Sign)
    (hvalid : Decimal.Derivation.Sign.Valid d) :
    Triptych.ProdMatch Decimal.grammar qual (fuel + 1) (Production.mk "Sign" [[SymItem.mk (Sym.lit "-") true]])
      (Decimal.Derivation.Sign.render d) (Decimal.Derivation.Sign.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [Decimal.Derivation.Sign.Valid] at hvalid
    have hpart0 := hvalid
    simp only [Decimal.Derivation.Sign.render, Decimal.Derivation.Sign.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.lit "-") true])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_optional (valid := fun entry => True)
          · exact hpart0
          · intro entry hentry
            exact Triptych.symMatch_lit Decimal.grammar qual (fuel + 1) "-"
          · exact Triptych.seqMatch_nil Decimal.grammar qual (fuel + 1))

theorem Decimal.Derivation.Natural.matches (qual : String) (fuel : Nat) (d : Decimal.Derivation.Natural)
    (hvalid : Decimal.Derivation.Natural.Valid d) :
    Triptych.ProdMatch Decimal.grammar qual (fuel + 1)
      (Production.mk "Natural" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.atLeastOne)) false]])
      (Decimal.Derivation.Natural.render d) (Decimal.Derivation.Natural.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [Decimal.Derivation.Natural.Valid] at hvalid
    have hpart0 := hvalid
    simp only [Decimal.Derivation.Natural.render, Decimal.Derivation.Natural.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.term TokClass.digit (LenSpec.atLeastOne)) false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              Triptych.symMatch_term Decimal.grammar qual (fuel + 1) TokClass.digit (LenSpec.atLeastOne) part0 hpart0
          · exact Triptych.seqMatch_nil Decimal.grammar qual (fuel + 1))

theorem Decimal.Derivation.Fraction.matches (qual : String) (fuel : Nat) (d : Decimal.Derivation.Fraction)
    (hvalid : Decimal.Derivation.Fraction.Valid d) :
    Triptych.ProdMatch Decimal.grammar qual (fuel + 1)
      (Production.mk "Fraction" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.between 1 4)) false]])
      (Decimal.Derivation.Fraction.render d) (Decimal.Derivation.Fraction.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 =>
    simp only [Decimal.Derivation.Fraction.Valid] at hvalid
    have hpart0 := hvalid
    simp only [Decimal.Derivation.Fraction.render, Decimal.Derivation.Fraction.capturesWith]
    apply Triptych.prodMatch_of_alt (alt := [SymItem.mk (Sym.term TokClass.digit (LenSpec.between 1 4)) false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              Triptych.symMatch_term Decimal.grammar qual (fuel + 1) TokClass.digit (LenSpec.between 1 4) part0 hpart0
          · exact Triptych.seqMatch_nil Decimal.grammar qual (fuel + 1))

theorem Decimal.Derivation.Decimal.matches (qual : String) (fuel : Nat) (d : Decimal.Derivation.Decimal)
    (hvalid : Decimal.Derivation.Decimal.Valid d) :
    Triptych.ProdMatch Decimal.grammar qual (fuel + 2)
      (Production.mk "Decimal"
        [[SymItem.mk (Sym.ref "Sign") false, SymItem.mk (Sym.ref "Natural") false, SymItem.mk (Sym.lit ".") false,
            SymItem.mk (Sym.ref "Fraction") false]])
      (Decimal.Derivation.Decimal.render d) (Decimal.Derivation.Decimal.capturesWith qual d) :=
  by
  cases d with
  | alt0 part0 part1 part3 =>
    simp only [Decimal.Derivation.Decimal.Valid] at hvalid
    rcases hvalid with ⟨hpart0, hpart1, hpart3⟩
    simp only [Decimal.Derivation.Decimal.render, Decimal.Derivation.Decimal.capturesWith]
    apply
      Triptych.prodMatch_of_alt (alt :=
        [SymItem.mk (Sym.ref "Sign") false, SymItem.mk (Sym.ref "Natural") false, SymItem.mk (Sym.lit ".") false,
          SymItem.mk (Sym.ref "Fraction") false])
    · simp
    ·
      exact
        (by
          apply Triptych.seqMatch_required
          ·
            exact
              (by
                simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                  (Triptych.symMatch_ref Decimal.grammar qual (((fuel + 0)) + 1) "Sign"
                    (Production.mk "Sign" [[SymItem.mk (Sym.lit "-") true]]) (by rfl)
                    (Decimal.Derivation.Sign.render part0) (Decimal.Derivation.Sign.capturesWith "Sign" part0)
                    (Decimal.Derivation.Sign.matches "Sign" (fuel + 0) part0 hpart0)))
          ·
            exact
              (by
                apply Triptych.seqMatch_required
                ·
                  exact
                    (by
                      simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                        (Triptych.symMatch_ref Decimal.grammar qual (((fuel + 0)) + 1) "Natural"
                          (Production.mk "Natural" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.atLeastOne)) false]])
                          (by rfl) (Decimal.Derivation.Natural.render part1)
                          (Decimal.Derivation.Natural.capturesWith "Natural" part1)
                          (Decimal.Derivation.Natural.matches "Natural" (fuel + 0) part1 hpart1)))
                ·
                  exact
                    (by
                      apply Triptych.seqMatch_required
                      · exact Triptych.symMatch_lit Decimal.grammar qual (fuel + 2) "."
                      ·
                        exact
                          (by
                            apply Triptych.seqMatch_required
                            ·
                              exact
                                (by
                                  simpa only [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
                                    (Triptych.symMatch_ref Decimal.grammar qual (((fuel + 0)) + 1) "Fraction"
                                      (Production.mk "Fraction"
                                        [[SymItem.mk (Sym.term TokClass.digit (LenSpec.between 1 4)) false]])
                                      (by rfl) (Decimal.Derivation.Fraction.render part3)
                                      (Decimal.Derivation.Fraction.capturesWith "Fraction" part3)
                                      (Decimal.Derivation.Fraction.matches "Fraction" (fuel + 0) part3 hpart3)))
                            · exact Triptych.seqMatch_nil Decimal.grammar qual (fuel + 2)))))

theorem Decimal.Derivation.Decimal.mem_fullParses (d : Decimal.Derivation.Decimal)
    (hvalid : Decimal.Derivation.Decimal.Valid d) :
    Decimal.Derivation.Decimal.capturesWith "" d ∈
      Triptych.fullParses Decimal.grammar (Decimal.Derivation.Decimal.render d) :=
  by
  apply
    Triptych.prodMatch_mem_fullParses Decimal.grammar
      (Production.mk "Decimal"
        [[SymItem.mk (Sym.ref "Sign") false, SymItem.mk (Sym.ref "Natural") false, SymItem.mk (Sym.lit ".") false,
            SymItem.mk (Sym.ref "Fraction") false]])
      (by rfl)
  simpa [Decimal.grammar] using (Decimal.Derivation.Decimal.matches "" 2 d hvalid)

theorem Decimal.Derivation.Decimal.decode_render_of_captureFunctional
    (hfunctional : Triptych.GrammarCaptureFunctional Decimal.grammar) (d : Decimal.Derivation.Decimal)
    (hvalid : Decimal.Derivation.Decimal.Valid d) :
    Triptych.decode Decimal.grammar (Decimal.Derivation.Decimal.render d) =
      some (Decimal.Derivation.Decimal.capturesWith "" d) :=
  Triptych.decode_eq_of_mem_fullParses hfunctional (mem_fullParses d hvalid)

theorem Decimal.Derivation.Decimal.decode_render (d : Decimal.Derivation.Decimal)
    (hvalid : Decimal.Derivation.Decimal.Valid d) :
    Triptych.decode Decimal.grammar (Decimal.Derivation.Decimal.render d) =
      some (Decimal.Derivation.Decimal.capturesWith "" d) :=
  decode_render_of_captureFunctional Decimal.grammarCaptureFunctional d hvalid

theorem Decimal.grammarValueCoherent :
    GrammarValueCoherent Decimal.grammar (fun m : CaptureMap => Decimal.valueFn m.toEnv) :=
  GrammarValueCoherent.of_captureFunctional Decimal.grammar (fun m : CaptureMap => Decimal.valueFn m.toEnv)
    Decimal.grammarCaptureFunctional

theorem Decimal.decodeView_input {s : String} {v : Decimal.View} (h : Decimal.decodeView s = some v) :
    Decimal.View.input v = s := by
  unfold Decimal.decodeView at h
  rw [Option.map_eq_some_iff] at h
  obtain ⟨m, _, hv⟩ := h
  subst v
  rfl

theorem Decimal.Derivation.Decimal.decodeView_render_of_captureFunctional
    (hfunctional : Triptych.GrammarCaptureFunctional Decimal.grammar) (d : Decimal.Derivation.Decimal)
    (hvalid : Decimal.Derivation.Decimal.Valid d) :
    Decimal.decodeView (Decimal.Derivation.Decimal.render d) = some (Decimal.Derivation.Decimal.toView d) :=
  by
  unfold Decimal.decodeView Decimal.Derivation.Decimal.toView
  rw [Decimal.Derivation.Decimal.decode_render_of_captureFunctional hfunctional d hvalid]
  rfl

theorem Decimal.Derivation.Decimal.decodeView_render (d : Decimal.Derivation.Decimal)
    (hvalid : Decimal.Derivation.Decimal.Valid d) :
    Decimal.decodeView (Decimal.Derivation.Decimal.render d) = some (Decimal.Derivation.Decimal.toView d) :=
  decodeView_render_of_captureFunctional Decimal.grammarCaptureFunctional d hvalid

theorem Decimal.SatisfiesConstraints_of_decode {s : String} {m : Triptych.CaptureMap}
    (h : decode Decimal.grammar s = some m) :
    Decimal.SatisfiesConstraints s ↔
      Decimal.Constraints ((Triptych.CaptureMap.toEnv m "Sign").getD "")
        ((Triptych.CaptureMap.toEnv m "Natural").getD "") ((Triptych.CaptureMap.toEnv m "Fraction").getD "") :=
  by
  unfold Decimal.SatisfiesConstraints
  simp only [Triptych.component_eq_of_decode h "Sign", Triptych.component_eq_of_decode h "Natural",
    Triptych.component_eq_of_decode h "Fraction"]

theorem Decimal.Internal.matchesRef.Sign (fuel : Nat) (s : String) :
    matchesSym Decimal.grammar (fuel + 1) (Sym.ref "Sign") s ↔ Decimal.IsWf.Sign s :=
  by
  rw [matchesSym,
    show (Decimal.grammar).prod? "Sign" = some (Production.mk "Sign" [[SymItem.mk (Sym.lit "-") true]]) from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Decimal.IsWf.Sign
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Decimal.Internal.matchesRef.Natural (fuel : Nat) (s : String) :
    matchesSym Decimal.grammar (fuel + 1) (Sym.ref "Natural") s ↔ Decimal.IsWf.Natural s :=
  by
  rw [matchesSym,
    show
      (Decimal.grammar).prod? "Natural" =
        some (Production.mk "Natural" [[SymItem.mk (Sym.term TokClass.digit LenSpec.atLeastOne) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Decimal.IsWf.Natural
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Decimal.Internal.matchesRef.Fraction (fuel : Nat) (s : String) :
    matchesSym Decimal.grammar (fuel + 1) (Sym.ref "Fraction") s ↔ Decimal.IsWf.Fraction s :=
  by
  rw [matchesSym,
    show
      (Decimal.grammar).prod? "Fraction" =
        some (Production.mk "Fraction" [[SymItem.mk (Sym.term TokClass.digit (LenSpec.between 1 4)) false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Decimal.IsWf.Fraction
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym, IsDigits_matchesTerm,
    IsFixedDigits_matchesTerm, IsDigitsBetween_matchesTerm]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Decimal.Internal.matchesRef.Decimal (fuel : Nat) (s : String) :
    matchesSym Decimal.grammar (fuel + 2) (Sym.ref "Decimal") s ↔ Decimal.IsWf.Decimal s :=
  by
  rw [matchesSym,
    show
      (Decimal.grammar).prod? "Decimal" =
        some
          (Production.mk "Decimal"
            [[SymItem.mk (Sym.ref "Sign") false, SymItem.mk (Sym.ref "Natural") false, SymItem.mk (Sym.lit ".") false,
                SymItem.mk (Sym.ref "Fraction") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Decimal.IsWf.Decimal
  simp (config := { maxSteps := 1000000 }) only [Triptych.matchesSeq.eq_1, Triptych.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, Triptych.matchesSym,
    Decimal.Internal.matchesRef.Sign, Decimal.Internal.matchesRef.Natural, Decimal.Internal.matchesRef.Fraction]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Decimal.IsWfGrammar_equiv (s : String) : Triptych.IsWf Decimal.grammar s ↔ Decimal.IsWf.Decimal s :=
  by
  rw [isWf_eq_isWfProd_start, IsWfProd,
    show
      (Decimal.grammar).prod? (Decimal.grammar).start =
        some
          (Production.mk "Decimal"
            [[SymItem.mk (Sym.ref "Sign") false, SymItem.mk (Sym.ref "Natural") false, SymItem.mk (Sym.lit ".") false,
                SymItem.mk (Sym.ref "Fraction") false]])
      from rfl]
  have hstart :
    ∀ n,
      matchesProd Decimal.grammar n
          (Production.mk "Decimal"
            [[SymItem.mk (Sym.ref "Sign") false, SymItem.mk (Sym.ref "Natural") false, SymItem.mk (Sym.lit ".") false,
                SymItem.mk (Sym.ref "Fraction") false]])
          s =
        matchesSym Decimal.grammar (n + 1) (Sym.ref "Decimal") s :=
    by
    intro n
    rw [matchesSym,
      show
        (Decimal.grammar).prod? "Decimal" =
          some
            (Production.mk "Decimal"
              [[SymItem.mk (Sym.ref "Sign") false, SymItem.mk (Sym.ref "Natural") false, SymItem.mk (Sym.lit ".") false,
                  SymItem.mk (Sym.ref "Fraction") false]])
        from rfl]
  show
    matchesProd Decimal.grammar (Decimal.grammar).prods.length
        (Production.mk "Decimal"
          [[SymItem.mk (Sym.ref "Sign") false, SymItem.mk (Sym.ref "Natural") false, SymItem.mk (Sym.lit ".") false,
              SymItem.mk (Sym.ref "Fraction") false]])
        s ↔
      _
  rw [hstart]
  exact Decimal.Internal.matchesRef.Decimal _ s

theorem Decimal.IsWf_equiv (s : String) : Decimal.IsWf s ↔ Triptych.isWf Decimal.grammar Decimal.constraints s :=
  by
  unfold Decimal.IsWf Triptych.isWf
  rw [← Decimal.IsWfGrammar_equiv, ← decodeSome_iff_IsWf Decimal.grammar (by decide)]
  unfold Decimal.constraints
  simp only [Triptych.component, Triptych.componentList, Triptych.envOf, Triptych.captureMapOf, List.forall_mem_cons,
    List.forall_mem_singleton, List.not_mem_nil, forall_const, ConstraintEntry.wfPart, Constraint.eval, ValExpr.eval,
    presentCount, natOf_getD, intOf_getD, lenOf_getD, countOf_getD, signOf_getD, Env.countVal, and_true, true_and,
    false_implies, implies_true, Bool.false_eq_true]
  try grind

theorem Decimal.SatisfiesConstraints_equiv (s : String) :
    Decimal.SatisfiesConstraints s ↔ Triptych.satisfiesConstraints Decimal.grammar Decimal.constraints s :=
  by
  unfold Triptych.satisfiesConstraints
  unfold Decimal.SatisfiesConstraints Decimal.Constraints Decimal.constraints Decimal.value Decimal.valueExpr
  simp only [Triptych.component, Triptych.envOf, Triptych.captureMapOf, List.forall_mem_cons, List.forall_mem_singleton,
    List.not_mem_nil, forall_const, ConstraintEntry.valPart, Constraint.eval, ValExpr.eval, presentCount, natOf_getD,
    intOf_getD, lenOf_getD, countOf_getD, signOf_getD, Env.countVal, and_true, true_and, false_implies, implies_true,
    Bool.false_eq_true]
  try grind

theorem Decimal.IsValid_equiv (s : String) :
    Decimal.IsValid s ↔
      Triptych.isWf Decimal.grammar Decimal.constraints s ∧
        Triptych.satisfiesConstraints Decimal.grammar Decimal.constraints s :=
  by
  unfold Decimal.IsValid
  rw [(Decimal.IsWf_equiv s), (Decimal.SatisfiesConstraints_equiv s)]

instance Decimal.instDecidableGrammar : DecidablePred Decimal.IsWf.Decimal := fun s =>
  @decidable_of_iff _ _ (Decimal.IsWfGrammar_equiv s) (Triptych.decIsWf Decimal.grammar (by decide) s)

instance Decimal.instDecidableIsWf : DecidablePred Decimal.IsWf := fun s =>
  @decidable_of_iff _ _ (Decimal.IsWf_equiv s).symm inferInstance

instance Decimal.instDecidableSatisfiesConstraints : DecidablePred Decimal.SatisfiesConstraints := fun s =>
  @decidable_of_iff _ _ (Decimal.SatisfiesConstraints_equiv s).symm inferInstance

instance Decimal.instDecidableIsValid : DecidablePred Decimal.IsValid := fun s => inferInstance

theorem Decimal.View.constraints_of_decode {s : String} {m : Triptych.CaptureMap}
    (h : decode Decimal.grammar s = some m) :
    Decimal.SatisfiesConstraints s ↔ Decimal.View.Constraints (Decimal.View.ofMap s m) :=
  by
  rw [Decimal.SatisfiesConstraints_of_decode h]
  rfl

theorem Decimal.IsValid_view (s : String) :
    Decimal.IsValid s ↔ ∃ v : Decimal.View, Decimal.decodeView s = some v ∧ Decimal.View.Valid v :=
  by
  constructor
  · intro hvalid
    have hengine := (Decimal.IsValid_equiv s).mp hvalid
    have hsome : (decode Decimal.grammar s).isSome = true := by exact hengine.1.1
    obtain ⟨m, hm⟩ := Option.isSome_iff_exists.mp hsome
    refine ⟨Decimal.View.ofMap s m, ?_, ?_⟩
    · unfold Decimal.decodeView
      simp [hm]
    · exact (Decimal.View.constraints_of_decode hm).mp hvalid.2
  · rintro ⟨v, hview, hvalid⟩
    unfold Decimal.decodeView at hview
    rw [Option.map_eq_some_iff] at hview
    obtain ⟨m, hm, hv⟩ := hview
    subst v
    have hdecoded : (decode Decimal.grammar s).isSome = true := by simp [hm]
    have hgrammar := (Decimal.IsWfGrammar_equiv s).mp ((decodeSome_iff_IsWf Decimal.grammar (by decide) s).mp hdecoded)
    exact ⟨hgrammar, (Decimal.View.constraints_of_decode hm).mpr hvalid⟩

theorem Decimal.computeValue_eq (s : String) :
    Decimal.computeValue s =
      (decode Decimal.grammar s).map
        (fun _ =>
          Decimal.value (Triptych.component Decimal.grammar s "Sign") (Triptych.component Decimal.grammar s "Natural")
            (Triptych.component Decimal.grammar s "Fraction")) :=
  by
  unfold Decimal.computeValue Triptych.computeValue Triptych.component Triptych.envOf Triptych.captureMapOf
    Decimal.value Decimal.valueExpr
  cases h : decode Decimal.grammar s with
  | none => simp
  | some m => simp [natOf_getD, intOf_getD, lenOf_getD, countOf_getD, signOf_getD, Env.countVal, ValExpr.eval]

theorem Decimal.computeValue_of_decode {s : String} {m : Triptych.CaptureMap} (h : decode Decimal.grammar s = some m) :
    Decimal.computeValue s =
      some
        (Decimal.value ((Triptych.CaptureMap.toEnv m "Sign").getD "") ((Triptych.CaptureMap.toEnv m "Natural").getD "")
          ((Triptych.CaptureMap.toEnv m "Fraction").getD "")) :=
  by
  rw [Decimal.computeValue_eq, h]
  simp only [Option.map_some, Triptych.component_eq_of_decode h "Sign", Triptych.component_eq_of_decode h "Natural",
    Triptych.component_eq_of_decode h "Fraction"]

theorem Decimal.computeValue_view (s : String) :
    Decimal.computeValue s = (Decimal.decodeView s).map Decimal.View.denotation :=
  by
  unfold Decimal.decodeView
  cases h : decode Decimal.grammar s with
  |
    none =>
    rw [show Decimal.computeValue s = none by
        rw [Decimal.computeValue_eq, h]
        rfl]
    rfl
  | some m =>
    rw [Decimal.computeValue_of_decode h]
    simp only [Option.map_some]
    rfl

/- ═══════════════════════════════ parser ══════════════════════════════
The generated correct-by-construction parser `parse` (= `computeValue` gated on the
decidable `IsValid`) together with its guarantees — `parse_sound`, `parse_complete`,
`parse_reject`, `parse_view`, and typed `parse_eq_some_iff_view` /
`parse_eq_none_iff_view` normal forms — all AUTO-DISCHARGED here.
When an external parser is declared, `checkedExtParse` additionally validates each
external result against this parser and ships an AUTO-DISCHARGED soundness theorem.
A verified parser, no `sorry`. -/

theorem Decimal.computeValue_isSome (s : String) : Decimal.IsValid s → (Decimal.computeValue s).isSome :=
  by
  intro h
  have hengine := (Decimal.IsValid_equiv s).mp h
  unfold Triptych.isWf at hengine
  unfold Decimal.computeValue Triptych.computeValue
  rw [Option.isSome_map]
  exact hengine.1.1

def Decimal.parse (s : String) :=
  Triptych.gatedParseOfSpec Decimal.IsValid Decimal.computeValue Int64.ofInt s

theorem Decimal.parse_sound (s : String) (i : Int64) :
    Decimal.parse s = some i → Decimal.IsValid s ∧ (Decimal.computeValue s).map Int64.ofInt = some i :=
  Triptych.gatedParseOfSpec_sound _ _ _ s i

theorem Decimal.parse_complete (s : String) (i : Int64) :
    Decimal.IsValid s → (Decimal.computeValue s).map Int64.ofInt = some i → Decimal.parse s = some i :=
  Triptych.gatedParseOfSpec_complete _ _ _ s i

theorem Decimal.parse_reject (s : String) : Decimal.parse s = none ↔ ¬Decimal.IsValid s :=
  Triptych.gatedParseOfSpec_reject _ _ _ Decimal.computeValue_isSome s

theorem Decimal.parse_view (s : String) :
    Decimal.parse s =
      if decide (Decimal.IsValid s) then (Decimal.decodeView s).map (Int64.ofInt ∘ Decimal.View.denotation) else none :=
  by
  unfold Decimal.parse Triptych.gatedParseOfSpec Triptych.gatedParse
  rw [Decimal.computeValue_view]
  split <;> simp [Option.map_map]

theorem Decimal.parse_eq_some_iff_view (s : String) (i : Int64) :
    Decimal.parse s = some i ↔
      ∃ v : Decimal.View,
        Decimal.decodeView s = some v ∧ Decimal.View.Valid v ∧ Int64.ofInt (Decimal.View.denotation v) = i :=
  by
  constructor
  · intro hparse
    obtain ⟨hvalid, hvalue⟩ := Decimal.parse_sound s i hparse
    obtain ⟨v, hview, hvalidView⟩ := (Decimal.IsValid_view s).mp hvalid
    refine ⟨v, hview, hvalidView, ?_⟩
    rw [Decimal.computeValue_view, hview] at hvalue
    simpa using Option.some.inj hvalue
  · rintro ⟨v, hview, hvalidView, hvalue⟩
    apply Decimal.parse_complete s i
    · exact (Decimal.IsValid_view s).mpr ⟨v, hview, hvalidView⟩
    · rw [Decimal.computeValue_view, hview]
      simpa using congrArg some hvalue

theorem Decimal.parse_eq_none_iff_view (s : String) :
    Decimal.parse s = none ↔ ¬∃ v : Decimal.View, Decimal.decodeView s = some v ∧ Decimal.View.Valid v :=
  by
  rw [Decimal.parse_reject]
  constructor
  · intro hinvalid ⟨v, hview, hvalidView⟩
    exact hinvalid ((Decimal.IsValid_view s).mpr ⟨v, hview, hvalidView⟩)
  · intro hnoview hvalid
    exact hnoview ((Decimal.IsValid_view s).mp hvalid)

theorem Decimal.parse_iff_denotes (s : String) (i : Int64) :
    Decimal.parse s = some i ↔
      Triptych.Denotes Decimal.grammar (Triptych.CaptureAccepts Decimal.constraints)
        (Int64.ofInt ∘ fun m : Triptych.CaptureMap => Decimal.valueFn m.toEnv) s i :=
  by
  unfold Decimal.parse Decimal.computeValue Triptych.computeValue
  simpa only [Triptych.gatedParseOfSpec, Triptych.gatedParse, Triptych.computeValueF, decide_eq_true_eq,
    Decimal.IsValid_equiv, Decimal.valueFn] using
    Triptych.gatedParseOfSpecF_eq_some_iff_denotes Decimal.grammar Decimal.constraints Decimal.valueFn Int64.ofInt
      Decimal.grammarCaptureFunctional s i

def Decimal.checkedExtParse (s : String) : Option Cedar.Spec.Ext.Decimal :=
  Triptych.checkedExternalParse Decimal.IsValid Decimal.computeValue Cedar.Spec.Ext.Decimal.parse Int64.toInt s

theorem Decimal.checkedExtParse_eq_some_iff (s : String) (d : Cedar.Spec.Ext.Decimal) :
    Decimal.checkedExtParse s = some d ↔
      Cedar.Spec.Ext.Decimal.parse s = some d ∧ Decimal.IsValid s ∧ Decimal.computeValue s = some (Int64.toInt d) :=
  Triptych.checkedExternalParse_eq_some_iff Decimal.IsValid Decimal.computeValue Cedar.Spec.Ext.Decimal.parse
    Int64.toInt s d

theorem Decimal.checkedExtParse_sound (s : String) (d : Cedar.Spec.Ext.Decimal) :
    Decimal.checkedExtParse s = some d → Decimal.IsValid s ∧ Decimal.computeValue s = some (Int64.toInt d) :=
  Triptych.checkedExternalParse_sound Decimal.IsValid Decimal.computeValue Cedar.Spec.Ext.Decimal.parse Int64.toInt s d

theorem Decimal.checkedExtParse_sound_view (s : String) (d : Cedar.Spec.Ext.Decimal) :
    Decimal.checkedExtParse s = some d →
      ∃ v : Decimal.View,
        Decimal.decodeView s = some v ∧ Decimal.View.Valid v ∧ Decimal.View.denotation v = Int64.toInt d :=
  by
  intro hparse
  obtain ⟨hvalid, hvalue⟩ := Decimal.checkedExtParse_sound s d hparse
  obtain ⟨v, hview, hvalidView⟩ := (Decimal.IsValid_view s).mp hvalid
  refine ⟨v, hview, hvalidView, ?_⟩
  rw [Decimal.computeValue_view, hview] at hvalue
  exact Option.some.inj hvalue
