/- Generated by Triptych from `triptych Decimal`. -/

import Outputs.Decimal.parser
import Inputs.Decimal
import Proofs.Decimal.RuleRegistrySoundness
import Cedar.Thm.Ext.Decimal

open Triptych
open CedarExamples.Decimal

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- soundness · generated parser
The one serializer obligation gives the exact valid typed view produced by `decimalToStr`.
Acceptance, value/conversion agreement, generated-parser roundtrip, injectivity, and
normalization are derived from that witness. -/

theorem Decimal.toSpec_ofSpec (s : String) (v : Int) :
    Decimal.IsValid s → Decimal.computeValue s = some v → Int64.toInt (Int64.ofInt v) = v := by
  intro hvalid hvalue
  obtain ⟨view, hview, hvalidView⟩ := (Decimal.IsValid_view s).mp hvalid
  have hdenotation : Decimal.View.denotation view = v := by
    rw [Decimal.computeValue_view, hview] at hvalue
    exact Option.some.inj hvalue
  have hbounds :
      (-9223372036854775808 : Int) ≤ v ∧ v ≤ (9223372036854775807 : Int) := by
    unfold Decimal.View.Valid Decimal.View.Constraints Decimal.Constraints at hvalidView
    change
      (-9223372036854775808 : Int) ≤ Decimal.View.denotation view ∧
        Decimal.View.denotation view ≤ (9223372036854775807 : Int) at hvalidView
    rw [hdenotation] at hvalidView
    exact hvalidView
  exact Int64.toInt_ofInt_of_le (by omega) (by omega)

theorem Decimal.parse_sound_toSpec (s : String) (i : Int64) :
    Decimal.parse s = some i →
      Decimal.IsValid s ∧ Decimal.computeValue s = some (Int64.toInt i) :=
  Triptych.gatedParseOfSpec_sound_toSpec
    Decimal.IsValid Decimal.computeValue Int64.ofInt Int64.toInt Decimal.toSpec_ofSpec s i

theorem Decimal.encode_view (i : Int64) :
    ∃ v : Decimal.View,
      Decimal.decodeView (decimalToStr i) = some v ∧
      Decimal.View.Valid v ∧
      Int64.ofInt (Decimal.View.denotation v) = i := by
  triptych_encode [Cedar.Thm.Decimal.parse_toString_roundtrip,
    Decimal.RuleRegistrySoundness.parser_agrees, Decimal.IsValid_view,
    Decimal.computeValue_view, Int64.ofInt_toInt i]

theorem Decimal.encode_accepted (i : Int64) : Decimal.IsValid (decimalToStr i) := by
  obtain ⟨v, hview, hvalidView, _⟩ := Decimal.encode_view i
  exact (Decimal.IsValid_view (decimalToStr i)).mpr ⟨v, hview, hvalidView⟩

theorem Decimal.encode_value (i : Int64) :
    Decimal.computeValue (decimalToStr i) = some (Int64.toInt i) := by
  obtain ⟨v, hview, _, hresult⟩ := Decimal.encode_view i
  have hvalue :
      Decimal.computeValue (decimalToStr i) = some (Decimal.View.denotation v) := by
    rw [Decimal.computeValue_view, hview]
    rfl
  have hinverse :=
    Decimal.toSpec_ofSpec
      (decimalToStr i) (Decimal.View.denotation v) (Decimal.encode_accepted i) hvalue
  rw [hresult] at hinverse
  rw [hvalue]
  exact congrArg some hinverse.symm

theorem Decimal.ofSpec_toSpec (i : Int64) : Int64.ofInt (Int64.toInt i) = i := by
  obtain ⟨v, hview, _, hresult⟩ := Decimal.encode_view i
  have hvalue :
      Decimal.computeValue (decimalToStr i) = some (Decimal.View.denotation v) := by
    rw [Decimal.computeValue_view, hview]
    rfl
  have hinverse :=
    Decimal.toSpec_ofSpec
      (decimalToStr i) (Decimal.View.denotation v) (Decimal.encode_accepted i) hvalue
  rw [hresult] at hinverse
  rw [hinverse, hresult]

theorem Decimal.parse_toString_roundtrip (i : Int64) :
    Decimal.parse (decimalToStr i) = some i :=
  Triptych.parse_toString_roundtrip_of_encodeView
    Decimal.parse_eq_some_iff_view Decimal.encode_view i

theorem Decimal.toString_injective (i i' : Int64)
    (h : decimalToStr i = decimalToStr i') : i = i' :=
  Triptych.toString_injective Decimal.parse_toString_roundtrip i i' h

theorem Decimal.normalize_eq_iff_parse_eq (s s' : String) :
    (Decimal.parse s).map decimalToStr = (Decimal.parse s').map decimalToStr ↔
      Decimal.parse s = Decimal.parse s' :=
  Triptych.normalize_eq_iff_parse_eq Decimal.parse_toString_roundtrip s s'

/- soundness · external parser
Obligations for validating YOUR OWN external parser against this specification:
`extparse_sound`, `extparse_complete`, and `extparse_reject`, stated over the readable
surface `IsValid`/`computeValue`. Registered successful-path rules proved directly from
Cedar's executable parser discharge them below; no Cedar Decimal correctness theorem is used.
The external printer theorems (`extparse_toString_*`) then follow, reusing the generated
section's derived encode projections. -/

theorem Decimal.extparse_reject (s : String) :
    Cedar.Spec.Ext.Decimal.parse s = none ↔ ¬Decimal.IsValid s := by
  triptych_auto [Decimal.RuleRegistrySoundness.parser_rejects_iff]

theorem Decimal.extparse_eq_none_iff_view (s : String) :
    Cedar.Spec.Ext.Decimal.parse s = none ↔
      ¬∃ v : Decimal.View, Decimal.decodeView s = some v ∧ Decimal.View.Valid v := by
  triptych_auto [Decimal.extparse_reject, Decimal.IsValid_view]

theorem Decimal.extparse_sound (s : String) (d : Cedar.Spec.Ext.Decimal) :
    Cedar.Spec.Ext.Decimal.parse s = some d →
      Decimal.IsValid s ∧ Decimal.computeValue s = some (Int64.toInt d) := by
  triptych_auto [Decimal.RuleRegistrySoundness.parser_agrees]

theorem Decimal.extparse_complete (s : String) (d : Cedar.Spec.Ext.Decimal) :
    Decimal.IsValid s → Decimal.computeValue s = some (Int64.toInt d) →
      Cedar.Spec.Ext.Decimal.parse s = some d := by
  triptych_auto [Decimal.RuleRegistrySoundness.parser_agrees]

theorem Decimal.extparse_eq_some_iff_view (s : String) (d : Cedar.Spec.Ext.Decimal) :
    Cedar.Spec.Ext.Decimal.parse s = some d ↔
      ∃ v : Decimal.View,
        Decimal.decodeView s = some v ∧
        Decimal.View.Valid v ∧
        Decimal.View.denotation v = Int64.toInt d := by
  triptych_auto [Decimal.RuleRegistrySoundness.parser_agrees, Decimal.IsValid_view,
    Decimal.computeValue_view]

theorem Decimal.extparse_toString_roundtrip (i : Int64) :
    Cedar.Spec.Ext.Decimal.parse (decimalToStr i) = some i :=
  Triptych.parse_toString_roundtrip Decimal.extparse_complete Decimal.encode_accepted
    Decimal.encode_value i

theorem Decimal.extparse_toString_injective (i i' : Int64)
    (h : decimalToStr i = decimalToStr i') : i = i' :=
  Triptych.toString_injective Decimal.extparse_toString_roundtrip i i' h

theorem Decimal.extparse_normalize_eq_iff_parse_eq (s s' : String) :
    (Cedar.Spec.Ext.Decimal.parse s).map decimalToStr =
        (Cedar.Spec.Ext.Decimal.parse s').map decimalToStr ↔
      Cedar.Spec.Ext.Decimal.parse s = Cedar.Spec.Ext.Decimal.parse s' :=
  Triptych.normalize_eq_iff_parse_eq Decimal.extparse_toString_roundtrip s s'
