/- Generated by Triptych from `triptych IPv6`. -/

import Outputs.IPv6.parser
import Inputs.IPv6
import Proofs.IPv6.RuleRegistrySoundness
import Triptych.Automation.ExternalParser

open Triptych
open CedarExamples.IPv6

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/- soundness · generated parser
The one serializer obligation gives the exact valid typed view produced by `ipNetToStr`.
Acceptance, value agreement, generated-parser roundtrip, injectivity, and normalization are
derived from that witness. -/

theorem IPv6.encode_view (i : IPv6Net) :
    ∃ v : IPv6.View,
      IPv6.decodeView (ipNetToStr i) = some v ∧
      IPv6.View.Valid v ∧
      IPv6.View.denotation v = i := by
  triptych_encode [IPv6.RuleRegistrySoundness.parser_ipNetToStr,
    IPv6.RuleRegistrySoundness.parser_agrees, IPv6.IsValid_view,
    IPv6.computeValue_view]

theorem IPv6.encode_accepted (i : IPv6Net) : IPv6.IsValid (ipNetToStr i) := by
  obtain ⟨v, hview, hvalidView, _⟩ := IPv6.encode_view i
  exact (IPv6.IsValid_view (ipNetToStr i)).mpr ⟨v, hview, hvalidView⟩

theorem IPv6.encode_value (i : IPv6Net) :
    IPv6.computeValue (ipNetToStr i) = some i := by
  obtain ⟨v, hview, _, hresult⟩ := IPv6.encode_view i
  rw [IPv6.computeValue_view, hview]
  exact congrArg some hresult

theorem IPv6.parse_toString_roundtrip (i : IPv6Net) :
    IPv6.parse (ipNetToStr i) = some i :=
  Triptych.parse_toString_roundtrip_of_encodeView
    IPv6.parse_eq_some_iff_view IPv6.encode_view i

theorem IPv6.toString_injective (i i' : IPv6Net)
    (h : ipNetToStr i = ipNetToStr i') : i = i' :=
  Triptych.toString_injective IPv6.parse_toString_roundtrip i i' h

theorem IPv6.normalize_eq_iff_parse_eq (s s' : String) :
    (IPv6.parse s).map ipNetToStr = (IPv6.parse s').map ipNetToStr ↔
      IPv6.parse s = IPv6.parse s' :=
  Triptych.normalize_eq_iff_parse_eq IPv6.parse_toString_roundtrip s s'

/- soundness · external parser
Obligations for validating YOUR OWN external parser against this specification:
`extparse_sound`, `extparse_complete`, and `extparse_reject`, stated over the readable
surface `IsValid`/`computeValue`. Format-specific agreement and rejection theorems are proved
separately using reusable parser rules and grammar-view proofs, then applied directly below.
The generated `checkedExtParse` is already sound without these proofs when the spec value has
decidable equality. The external printer theorems (`extparse_toString_*`) are also DISCHARGED,
reusing the generated section's derived encode projections. -/

theorem IPv6.extparse_reject (s : String) : ipv6Only s = none ↔ ¬IPv6.IsValid s := by
  simpa only using IPv6.RuleRegistrySoundness.parser_rejects_iff s

theorem IPv6.extparse_eq_none_iff_view (s : String) :
    ipv6Only s = none ↔
      ¬∃ v : IPv6.View, IPv6.decodeView s = some v ∧ IPv6.View.Valid v := by
  simp only [IPv6.extparse_reject, IPv6.IsValid_view]

theorem IPv6.extparse_sound (s : String) (i : IPv6Net) :
    ipv6Only s = some i → IPv6.IsValid s ∧ IPv6.computeValue s = some (id i) := by
  simpa only [id] using (IPv6.RuleRegistrySoundness.parser_agrees s i).mp

theorem IPv6.checkedExtParse_eq_extparse : IPv6.checkedExtParse = ipv6Only :=
  Triptych.checkedExternalParse_eq_of_sound
    IPv6.IsValid IPv6.computeValue ipv6Only id IPv6.extparse_sound

theorem IPv6.extparse_complete (s : String) (i : IPv6Net) :
    IPv6.IsValid s → IPv6.computeValue s = some (id i) → ipv6Only s = some i := by
  intro hvalid hvalue
  exact (IPv6.RuleRegistrySoundness.parser_agrees s i).mpr ⟨hvalid, hvalue⟩

theorem IPv6.extparse_eq_some_iff_view (s : String) (i : IPv6Net) :
    ipv6Only s = some i ↔
      ∃ v : IPv6.View,
        IPv6.decodeView s = some v ∧
        IPv6.View.Valid v ∧
        IPv6.View.denotation v = id i := by
  simp only [IPv6.RuleRegistrySoundness.parser_agrees, IPv6.IsValid_view,
    IPv6.computeValue_view, Triptych.Automation.exists_valid_and_map_eq_some_iff, id]

theorem IPv6.extparse_toString_roundtrip (i : IPv6Net) :
    ipv6Only (ipNetToStr i) = some i :=
  Triptych.parse_toString_roundtrip IPv6.extparse_complete IPv6.encode_accepted
    IPv6.encode_value i

theorem IPv6.extparse_toString_injective (i i' : IPv6Net)
    (h : ipNetToStr i = ipNetToStr i') : i = i' :=
  Triptych.toString_injective IPv6.extparse_toString_roundtrip i i' h

theorem IPv6.extparse_normalize_eq_iff_parse_eq (s s' : String) :
    (ipv6Only s).map ipNetToStr = (ipv6Only s').map ipNetToStr ↔
      ipv6Only s = ipv6Only s' :=
  Triptych.normalize_eq_iff_parse_eq IPv6.extparse_toString_roundtrip s s'
